---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: dragonfly-operator
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: dragonfly-repo
  releaseName: dragonfly
  targetNamespace: db
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    crds:
      install: true
      keep: true
