---
apiVersion: helmv2.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonflydb
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: dragonflydb
      version: "1.4.15"
      sourceRef:
        kind: HelmRepository
        name: dragonflydb-repo
  targetNamespace: dragonflydb
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
