---
# yaml-language-server: $schema=https://k8s-schemas-cjso.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: dragonfly-oci
    namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  targetNamespace: db
  values:
    crds:
      install: true
      keep: true
    storage:
      enabled: false # if data should persist in the future
      # schedule: "* * * * *" # Example cron schedule

    # Add any other prod-specific overrides here
    # replicas: 1
    # resources:
    #   requests:
    #     cpu: 100m
    #     memory: 256Mi
