---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: external-secrets
      version: 0.20.4
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  maxHistory: 2
  targetNamespace: platform
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
