---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo-runner
  namespace: flux-system
spec:
  targetNamespace: forgejo-runner
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: app-template
        namespace: flux-system
  interval: 1h
  values:
    controllers:
      forgejo-runner:
        containers:
          app:
            image:
              repository: data.forgejo.org/forgejo/runner
              tag: "13.1.0"
            command:
              - forgejo-runner
              - daemon
              - --config
              - /etc/forgejo-runner/config.yaml
