---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: flux-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      version: "1.10.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
  targetNamespace: longhorn-system
  install:
    createNamespace: true
  values:
    persistence:
      defaultClass: true
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
