---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-base
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/dev/platform
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
