keys:
  - &EnderDragon age1zjduq5gd3mu24cqypn65lpj8f67075xsgeztsddarrgs8jyv5qtqs22guk
  - &flux age1e2ww68t6ekwk3d6c6k7u6wswnutsuqtht75yseerf7nynsvj6ezq3wtwk7
creation_rules:
  - path_regex: '[^/]\.yaml$'
    key_groups:
      - age:
          - *EnderDragon
          - *flux
