---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-rclone-config
  namespace: blog
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: garage-rclone-config
    template:
      data:
        rclone.conf: |
          [garage]
          type = s3
          provider = Other
          access_key_id = {{ .S3_ACCESS_KEY }}
          secret_access_key = {{ .S3_SECRET_KEY }}
          endpoint = http://garage-garage.garage.svc.cluster.local:3900
          acl = private
  data:
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: "/applications/garage/S3_ACCESS_KEY"
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: "/applications/garage/S3_SECRET_KEY"
