---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  values:
    resources:
      requests:
        cpu: "300m"
        memory: "256Mi"
      limits:
        memory: "512Mi"
