---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-cluster-secretstore
spec:
  provider:
    infisical:
      hostAPI: https://infisical.home.voldemota.xyz
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-credentials
            key: client-id
            namespace: secrets
          clientSecret:
            name: infisical-credentials
            key: client-secret
            namespace: secrets
      secretsScope:
        projectSlug: 27ae3980-af3e-4488-a4f0-23ad96a59ee4
        environmentSlug: dev
        secretsPath: "/"
