---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-cluster-secretstore
spec:
  provider:
    infisical:
      hostAPI: https://infisical.${INTERNAL_ADDRESS}
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-credentials
            key: client-id
            namespace: secrets
          clientSecret:
            name: infisical-credentials
            key: client-secret
            namespace: secrets
      secretsScope:
        projectSlug: overworld-cluster
        environmentSlug: dev
        secretsPath: "/"
