---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 00-base
  namespace: flux-system
spec:
  interval: 2m30s
  path: ../../infrastructure/overlays/prod/00-base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
