---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 03-backends
  namespace: flux-system
spec:
  interval: 2m30s
  path: ../../infrastructure/overlays/prod/03-backends
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: 02-storage
  healthChecks:
    # TODO: check this one in the helm release
    - apiVersion: apps/v1
      kind: DaemonSet
      name: longhorn-manager
      namespace: longhorn-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: base-config
