---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ../../infrastructure/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
