---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform-prod-controllers
  namespace: flux-system
spec:
  interval: 10m
  path: ../../infrastructure/overlays/prod/controllers/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: platform-controller
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager-controller
      namespace: cert-manager
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
    - apiVersion: apps/v1
      kind: Deployment
      name: sealed-secrets-controller
      namespace: sealed-secrets
