---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-infisical-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgDDozvT2ZMPm3Xt7lnc3m4/xgPxxWHkDyb+eIdYHaq1+01JPIf1/RjLywSCol1W9nQRDEhUkGXoFM1pqHXcUPeRl0KW34YSa1uaopI3a86DEO4pJDQHkgJ5IAT2qaiFUUGdnL+XyjpiHxFnEpO8wAgi6YU2zBEvzYG6YRbDQbkDIPfHNHvcWyvS4aSkqXOkrYVVt5sPeg2lMid2KnTv6VB71r6y3lRiX4qPQhoLq/7Yu9yyrRvPwpbMvG0QrVEmXz5B1Dtkhlxl5hJdHrmLTVajJKOlcuhUoaSs7LCVeS2jiG3aA0X1ccLmCF72xIGcVjdzNHP8LPFKNEYevPWfGk18TQvP80ERdusBJVyYw+nD1PAH/jHmo0KBRl7kaYggX8ZX2qaCU6la0qgfwpd1gRAcuShkNkTJW47wibLKYRIndHnqxKftWF3rvrdUKIxOEv5niYJECMc6oszei6tPIiBJefeGK/FhwVlp/nH1wg8XRPktwCJ9WUeVcPNOQneKimgLNlzugybNnEGWtojNEJ25NdJzaq6n/VfA9Yex5BoByyn4xM3JcBVNlLrG+gFbJuaVs7QpDk9mWr4kWbiKWP0ZwRxEyzPuaTmz6ok2ruFpVcnDO8SUlcl5EtZe4lF7E0cE06ElEs33l7vEMKjOFR1eGqAh8b9/CNMZL1kqvg9KQBdiKLZqmuOFrdFKJ6hR8TRouGmM4tVoO8ZVHEReCdNc2PE=
    username: AgCbhfdtCpviqqsgDtTHNu8OTwZQW0t/WySqWc2rcjoeZvCA7uPGa3njM8IfcXi25yqew7gAhUdtNGa6+JKOn7B0aeDG+1dKPTg5Gooe05TP5N/6k/ChyjF6w/W97FZSnWaOzIsFI9hNsVHHHsZ1s5lY+FRv11cU/RtiQ2kPtiauElnu+7l/tkcfp9Qk3hc6LCuvhbI9dC7nFuLbDiJBuHE6cbcmKgOcyWfv3Gi7IYO4jhl0z47OOEnzYYpcwpLUQGrKx0t111E4+aFvM1WH9gmFqwv566jtcggNEgJGLLOF0Jqj9U6itWAew7DOCxq3E/Evld0KDEqDACIh/USOygXeMb/SPW61H63fnTuM4HQ0hWEbM4TVkfuD1JwRavPzgKy0J9f+/bHRVgHJMN/8XRkz28aHt1BwXD4nQPohpsUaPCVJeS4LrzQbV3fAXE6KTJ897pLTMz/GvazW8NpmjOJJ8bg8tCXJ2utMqK+5PTLyqw2N01GXKv1eWXbHAOaVfYaj/w8/MJ8plVI/MkXzUdqum644r9fEw3YJ0mKdskeV/r++kwOXt9mbrGm3UYzpHzv4Ym9VmqdSKITj473aBgWazWU6k8WFTsvSf/RPE6UcAtiqD/P/DDbve8grMOtcYKS3liPzO6NYz1y1s0mR0yZ2NVdD/gqSNWMCmKRNOJ/6gRqkceINFBqsjMr0pq/ronqPhMaHICxEt3o=
  template:
    metadata:
      name: psql-infisical-creds
      namespace: secrets
    type: kubernetes.io/basic-auth
