---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-infisical-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgA8doP4BuDMwLLSMvrO04MTPgShXv64IMLJ70ZPq0miXM1K6gAuDHPs/GZQWc1l4/5bJbrRzCZj6I54mODixODLzjGWCd9U5sb+LXo8GjOuF2J4U1JO0zRnt24cgusgrkWyYy+maXZ8n5nssC6NUzDdF5B95KB2Pyf/9o16cGIEjKOuIaP+rA0TYsdUQ6hBYnxHmzNuCUwSfaHjqIaddakLOOZl85I3/mEu+xj300VKOJMRNNa8HSbdxayY3/8x899NsI8nqKEhutso8fwsbsWZAX1/5GW9Jad4svBWyBOMmChjzW9y3uMkxkAMayORe1/tD7GfexXDEuDdl6g9n7U0xwoSFM/LWwRcECP4E4Q9S+sjTe9geXvIiLykY4IKG5TgektrFmmigsj6MuBUWf2UNQ2nFwNDVFQ+qFBCgxmht8vqpcU4yo2gxLsWMzyMzwWXZ4PraCvre0UZT1Aw/Ra2mcnTRquksQJp3DAkCZE9kDIuPb9N7BLsQIkF2f11NQ95qrgrtgnmN6h8VO7kHu/Yd0LFOEnO0COfCGlRunH2igjoe7XOlFyy5uXuXeBEOI9gMGuUpbajlwfajcnV7PSnOpPK4hq8cdoLdNJbQfppcHqLQaytpjt2KnrKgG1iwCcIsRVYKzHZj2F/8H7wRr8QZ7S7sXPyOMye5gKou6NPbcSqEqwafVg+ZPRDBNNB7uStgdgACGqrCbpcEPC/Tdxn4vM=
    username: AgBSyyGcRwV6WCsr6NPhQjrcJCHdtr5L5yJYr9O2PX70VY2OSJCTBYIgZzh2kjdIPqGJb6yh5TOHxVPPxW497CDe4RVc78tXfTuqECOZa/8kjfut9QpejkPvObrXpJt7yev2GIydJTYOqSObxDuJT0Yb5A0BiksvcwZ9Fzr33HRvb73md3laTp2DSqC1yA5KuJWAQ9e3XZ4AE0P6Xd7QVDhQxTmZPGAFftCVbFhqorDfWxHLdjNhPtifDRJ5wRCHeBwV9mmlUopakRNXFj/fAcswjuoGnLxo7vr1rDO8qmRd+Uxv0xY7pt0n/1CezcQhph8VeiWADEBAYUGhnyiCKImk4z5tXdaefZd0+UphcGG555FV08MD9UQcURJMxdbqu1nJn5qUTBi9BuG5EtI7oFugb7NkRDByA0bxzbw/o9/SDQt/miv7FKV4GDURW8t+82lnXIMYVC/ZllkLCwlLnpMFbaZGgkfuwpz5tMIS7r3lIKqwm5RNuRD0byEJTKDC4uoi82e1tHw6zy37mbdOs5FPX9Eqyk+YAcxwHG6gNnbUKsSJBtsWIoXqD6TN5ybFe8DyyMu/4gRYdz3aVjGRNQKJCt3M6ZGEs4+FfIHeLEkz75oIv5TZ7r3Hquziha4BHNsk/8+qByIoyB9xS8s3UhVJcgFI9QBuGMmAd14iyIE8zNmyHZ15g0DSZJqEHyt9pMQe4o4LmUkoNso=
  template:
    metadata:
      name: psql-infisical-creds
      namespace: secrets
    type: kubernetes.io/basic-auth
