---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-infisical-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgC0OFE/eC+c12Vzwvch2g4+NWHG87GyTEoOGO/yr52HdgIXS/4hMlhRcNDf9Hvc+dtIFvM89gbgDBI+CXN8nzaYzXNN9+Fo4CLUZwLx5EaU4/2oCqpirUipY8bknWEvPH3ioVzmTWbSIQ6011OaMIjJGBhTnseGQL/ijPAE8Vk84USgP1VwxYmN2pSLAOcQopnjKe4AsrYDbbxBxxZIDNf61fOai94tHBV/masu30n4uxlis4EFMiZi1K6ogLPlmpkkhHh8qIVAE2elLJLiaRu3xI6Y3shQOpR+1cSPlQ7PiPaIXAeItnScznA3xRs0OzHk17SYOKYeX8s17pbAh+o+3VYgNOaUXopHacblEioij954T2qjyOWSYMBn6P+gQPwz0bS5jtI+laCpaAr82DcIf/VD5iKOYEDsViglFZgNiYJICXXJZt2EU6BN65sxKoMdr7C2ItRlZjS0xtjdiRbxRWKg+kOzvR6K+u9pPqsQblOD7Sj2HFozUQK1z5v1bq4T9oUwK6H6CGRLYZLDtrkWWfPzd8hMoWni/x8qb90V+VW2T/5utCr1QcQ0vCT9WpLffYHvjmuC3jO2xqdFF61DWPPpsKMGx0m2o9RYXarcX+QkVjNSwEn3oQeWFaiJThO1RzEwT1ZFQ4P1P1/BEb1SfQtxec4I1JyXM7KiuTYCVUKDLpiElQSAslJ51oYINNyaaeuuPo3jrxD002bMXjnYSa4=
    username: AgArk+eUw4kVVlrZa6QRRYrWv9Q9M3K/tie73SImeMX9ZwFV/VJZVVi56+dNuciYJsNS5/EeRaWJG6LOuEletXgsD7Sz10HtzS/0QNKKJiI5jGhpmYBw/zEJobJEVMXiz9DWRzODKM3JajoFZydkPInZIfemoZ+/4CHRMYwwUqrvU3KPDaTfoDHESPMw37a3CYcYQagHn7ypmLnTHojiMCXI5MJ+DdMAt+rELPv0TwdRBikukkQcNtK0xH0+uVjk4/56bmITuIogn2vWw5oGV2cl9uJaOUdKVjGn6llz27PxpxYmI9oCvzdv4m2D7BhPH9jrfuYRTZnuIj7LLYZmDONEj1J5TIJdw0t7qrEgH59xxOy4+I1Fmf/OGYqjt3pY9dQ1yoTBc63/ONEwSYSJLJJ5+SU9qb0Jnl5HWj2ri12vf5/UDNIoOqOlnLSQpilx8htZ4Ghh8gPy1adiv7bY2hztQDI8o0c0wX+Et1iJT27m2Y02ZK4lHe2uT1Og5YxLMijQ9A+hHn8ShFDaKHfNUTDwoc8Q11yO6X753JlXf1OMwAaLZuYYltOq3GvTWefBFCWtJOGFYo9SuEE0hKV3zqoWA+d1uqw03l0+h/Fu4LxUbzBdnY6cui103dq0qH/PaDgMl/AnAsNWnKzFd3jOvJjsuuEtGNnvOZGIVH2k1egiWlDRP8AcJXz26z7quk0pDtS0ILhDGANTCmk=
  template:
    metadata:
      name: psql-infisical-creds
      namespace: secrets
    type: kubernetes.io/basic-auth
