---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name docmost-db-creds
  namespace: db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: "/databases/docmost-db"
