---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/dragonflydb.io/dragonfly_v1alpha1.json
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: dragonfly
  namespace: db
spec:
  image: ghcr.io/dragonflydb/dragonfly:ubuntu-v1.33.1-amd64
  replicas: 2
  args:
    - --v=2
    - --proactor_threads=1
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      memory: 512Mi
