---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-db-creds
  namespace: db
spec:
  encryptedData:
    password: AgCzNxaAIlDMidE/nmmrLoOvygzEzJrmFVZ/YNF76KI6fj5qgA2ahGwtAvKl+MEC4SreJbzEY8x1D/7dQBCb7WzBR6XAs4xXKxXDXiV6sdyRPbhKqy9/Hy4oyAk7ca+VxvtyoK/IA8kVVsXI4/sgvs+Tt19UlRDns/FzWiuyDlZocrUiUPb7D28OmJnQsgbWrhXUiBYTGNeLltGrXmtzUA2/IqcBdzuMwSUr17c1K/oRpU9F23oCzfhoEv95c3aq7W3tKbZ401dlfOwtj8rb0qXebQZuNYBDcVvZV5XmoSskc/wVexH5D6Idm41vWAnLa4S6r93q2McBUKb/EKFLvJpV3nBWilX6894Di5g14KZw/KHKCkXnc2gNaPlXwvpcTidcjQgF3E1c2SzaW1j+y8bEX30AYUVw7WwXnXczYe9NcGzTKAl0YX3F30w+SlYHfAntvuX6Kc5qBzpIYOGIosHntX4PyYISbPcqbO1u8Z48BP9RK0H5mfhHnMVVSlA97J9a32U6LymCVQWP0zltj7T5EGKBI+yqqokZ/8V2+tQ7rPqf1d8pp6VMMIVym9MHDUDeZ4K8JQtV9GZ2EoHzN6v0t66Xh11cdqWJgC2Rh/eqqDD42D5OuIQq+S0T39PCD+IpRYn4Sl9fPf8k+sB8JA2NH5maNrZMqPicKPbvJtqxZXln3vQ6bf/mu+TLaeHzfid69DNLorVorg==
  template:
    metadata:
      name: immich-db-creds
      namespace: db
    type: Opaque
