---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql-cluster
  namespace: db
spec:
  instances: 2
  storage:
    size: 2Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      encoding: UTF8
  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        passwordSecret:
          name: immich-db-creds
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 200m
      memory: "1Gi"
    limits:
      cpu: 1000m
      memory: "1.5Gi"
