---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql-cluster
  namespace: db
spec:
  instances: 2
  storage:
    size: 2Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: appdb
      owner: appuser
      encoding: UTF8
  monitoring:
    enablePodMonitor: true
