---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: psql-creds
  namespace: db
spec:
  encryptedData:
    password: AgC+0MhHYujLikO/d27gn8CJsOYp9FJ1vA4tgg0QLO7IC4iwUddKaRGiuBqTEsQTmvXqJ/KhVwWMuxpvWU+mS262Xy3HaMBP93qV9xrYyhKZAW4YJAHfwZqP1rxu1RR5puIv/4+ZI2GXJtX9UClkOjxAETpl+XNr8qgnPN7kcH9ow84rHn1jtrIQKUJqwsYXwdO33ZelbqcYMycRBYQBCcsJXPY+UtM0RJEIeLbFYodOgmen+liXbySRV8zPy2g05UgVvHKcnKkG1z3Es6W9qeBPOnMxCQE0aGr0+IcUBN5jFghi/Igp0iRNYUT7y58ZyccAD4K/Q5gIJVnlir3UFje6LF8B10mUuzlz5AjdrgldTiJOuQl3wHHfom2/HOJ6Tyi5c1CcHXCaa8wk89NM48Z8UimYkz3mn65RRhpdNMV8xH30/0Ad0OevoFTmjtwRv5xYFXvhkIjq+5/xxDuZgr3sKJ4HfKQdYFP6DsACTx5jnLGsRiPsHt7hhmo0hqzvlnWz9GC7B8tny1qBtl4XgycvEAcoy4zsWNrB7Ur0TqkqyXTZWR+hEWbwqYuPBzY1i3OeyJ0MqvV3Uw5tIsVnVTLJjDtN9MXgqFK6bkyrn/65YHxzfg/OYv7WXqycK0I8cSw8L99cStvAvPI+ydn95xktBwi1AT7A4jBZxIeg9CxUQR2mPAIJDqVhX4tV8v/AjuWUeYoB+6FfrA+ADuI2BgDW0cbKek2Lg2F/BN/iv2FjpxxrMd9XAVjZhYBj9K9Avjs=
    username: AgBydosMielNSYoHUYxwQipzaN9BtXrist4Z8zTnCYtlNOwo2Pa/VLThIr4srviGC/Tvlz+jPUSc4kfK1f2d2I+77cy5OYc5W8ZhU6FwIbzXhOQGfZsjeQOwoqZ6Yc10d78yTxmEdedQzImIdYOa1Q1Mo+cq0fz4SzJoXozwsFxGlvHcafH6OmQYLWkaHLsvubue/r4a9X2plDT1YGItO/3FrT8aWFWbhq1pHIcvQ8dmzDIg6e+Xw6NYajGxNgw1E8DSOVZ9OewSbNHigQSEgXmZbJXoLKevU0aKthfjFFIolxmJGXlD02EH8HsPO9pW68sE5rT/MTkiD6eNsidr6Z5jNvMQgm3TvyLMaTEtdP7UClI0zoR/R5fhBSnNWktgjJSFcQhkZYhbfKTnb/nV2v/jbCphFRbvWTkcYk12hdu0ljR8e8i3ojAdOLT/gF91BWFil6d49QrdI2fl9QWges8tENxGupvit20mUQukQq9EseoJQfFIkQcilG+0xgvy7pdmVhKAhyQYWjWbgTQLRRsX9WyP02uTzRP4+365bMtAiGWjLCgnANMkYC5cq6fdEDAZwkMDBWCxiS/Avu+1IqlUjvQAkiLTHYRbEEl1VZyKKahywM/oGglQVZEZyGiHGB3wwrMrUq+C1yEBXc8He/XaYNTDuZQy1VrwcY0HdTBOI4SaPJZWDtmeMhjnO+D9MzkgzDewodopHFA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: psql-creds
      namespace: db
    type: Opaque
