---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-creds
  namespace: db
spec:
  encryptedData:
    password: AgAA6BhOsgNx5F8QUeLoS49kdvnT0+XF+srKLTSYeqcYQXF7oMBGIm9zCKZMzlMVdkD3ffsa/xqgOfJ6icxS9NwouxCw0WNrjC+zBMqw5vP6v7DCbbn87qCSnjfZWaAet2sqsyZJm637Ou5xYTOnlPs76eij8PJNbz2QtftZM2lo/jurPYeYsB3ju3H+NiRlaveVGYKevH8mhEeTzyDgGN4qyZz0ENC0g9TDDOKXJanNrVs4GsmgiLmJT7LIjJOrLf8yS9sSqPZvn+WBsuFhJ4h8/ENYiNy3nbnp8ZOAylu6xanFLw8KNI61yThnz3Xsxz6fmrjeX1J449hGbA4n4mJSLMKEQCE1O4lr7kQTGwLrkvHb5lSDnkKtOL/WsxndIjNGh8jGYrS4yY7TTppcAuubCqJxesAGun6Da47VHM7QJVlv3l+QMXrwHyKQEBP84Gg8R834JwSX9XuhjkAmUaT+jm15k/22/KpKITR6VLqzlegn0K405fCt1U9ASInjnZHjDqT9HasePqVSITgaHioilz73LO1DDP/KDQ/bflyO/mdo1bxgqkAr54spVxsRJrtbCq6LHaB2Zp5t9vbWErsPsoyE5BYoMz+ORjDahCEs/LQszas3eimrctDsUKmVSsjh0KJnvJSHD+pherHbLyPllhxqfCWzMAhK+gCE/PM+RcC1qwFNshzFrf0M2Ler1mWkfXCNMD6vnO3Pg91Rzyf1mWs=
    username: AgBuvUMRayp/l3SLdl/xP2/JZZh3CmmhMylhkmfT5F00GrJ7gRQwvtpIbc0NZJj5uYY3FO8Q46vTiOssNNaU9l7xeCx1E3FvDLXiqrrFuUiT3VDtm8eU4/1ebPlmKE+Tol140wOgO/4h0M1rrEnHtZrIkMAa9uWuuCbKBBh5+iescFUqBsI3Q22Bv5ewlDSwTWcWd3trDZFUi4OxGgrl7a6Q0DCQ03BrqvtjP5LQkjvx21YtaaTaLM03AX4moLNcRKFNhEJFVV+9AwUxbeLWgqB86pUTw9dz+7Z1eKVG83z2k4v3aTiet5eGgjQ6my1tIUU1PDxfcf8UR/uUR7ltWKLkyhiMtyCBEFNJMNHjTsnjc1wjz8v6OvOlnOwgpdMQxcqsPq/0xAg0SjCs/qxhROtOlYmvTXlaLVcyovoGV05hqnGE6ywytnwnJU8P5gzgN4YJMxYclGRQ7Y5J9mrOc+TT8sdsX5LB4yi0pKrCIs1xH9i7wIwdPfXZpz6lpL1kNF0iVWG1dIBYwDcuMf+TdOolwMMvISzEJQt/fhFM+3DDGw23V+/g26fxcDzbSlSSnZ812OV+vMa+104ETlJh/oDUWcVKepGdZgWSh+A5By8Cxd+JN1Au/VvWLIFxbOAndeBd+ODQSF/15Z3qSXNKjObZ6kHnUXumr/HC3me2hnKaT8MJDYpJkfGvy3l/xYHF+TzERhklld0S4g==
  template:
    metadata:
      name: psql-creds
      namespace: db
    type: kubernetes.io/basic-auth
