---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-creds
  namespace: db
spec:
  encryptedData:
    password: AgDBtr3pi5oYbjsoj3BVsSycwvuLxOWiEoraO42PE8E93PJVfyA39cV+dnn2BjBoNsIwaBGpLj0lka4ru7o5JUpW6dqkH7vYu5t8oGS+gAYtrVISbrZ87uCmePma5r90hVKcU5gunmcWAs6Pis69/vYyRx3/vcH9KxBc5q2xDCoPqybCxsoq5jGgT87XkHch1S3jWx0lI/q4/rUCq+T+SXsZD7fubmTMUXudhCj7Y9P9IvG5Hof6jrAju9aDTAjaznpwSuvO8rpFM1BkYcRv8F22uS1H1GA/S01e9takEEtexQVJYfmYmlVWwTxFbQFn0zCnVZTLOuUeoQSwukxL+HZXc2NLe24OSGrErK8a1sTxhPww0gzX3TwKxsxehhKYv8AcUmWuTH6KFHbuEom9KD4Lwslr7IBA1J2cQGQDYW7u8QLdr0R8ARRYkmPyAyo8vqlVolo8OQXp15KGOeaB5Kqp05/By/NaXTkDJYJ0yA6dSGY0HIflhHnbLbrS9IEDXIquPy8s78N7JJN87LgZmzVhPnjegqkBXigdsnwPK8Jl8KWdfdCBICMya6H/09JPcOmwMdEfNfjPRnAj6gmTjp65+YS6K7WUpiI+aZoiKjv2PGWikca83n21FVY8Ccr67y3epg26ed4yQYjGTTRksUePaqqtiQOZTn1yIqgTDdbziVSqGrj1b19KsNZqxyH83wIoYYDzFo/VSeXyf5npHDfgzG8=
    username: AgBVbfON5mpaPvbij4s/8A8gkPC+GRKpew0eEizZ11hbVjNSx8BhC9FjIRAuB5neHRNOKIGV1e4N4aRTynTaFYZoTXt4NF2LPpg2Iizhgrtzu/khVr9+KChwkCJLN1WHDs6ATfXO2FtgNR3v5KkUk9G5NZQtyjSDiXvFDASl9z/KqwLdSRFTJ0/Te9g7RyUdDwcY/0DXgxchAc3yxxRizM4Hogo0QQlv2uNzfCXPwyAZv0IhOE703Ij4HjSvOfDcTVlC37/A02NmWRfllt8tq64d6RrCjHhQl3QD1Ye7cgChMDf0/Tf+M5hcXCUf2dByN0lweky7wQcVM+zrmCjKpQUkAlO7+nqq7+aK4csIY8JdJ+nDoNgIOf4QsOfDKGFauVIpGJYJ4tSW4oXGiKKBJhinrPLw+hUNDONR57vQvTukCmLhyZeuDrGDHW3T51EFCuAY4rbOlnw0zCp9SDw1BoKNjHsbDd6z4I2/J+fM0CynOjAk4fP93LDzYVF7SA0O8ydTgJBTFXDM9UrNSSkqa9sG0Nk0icLhg6D4ZQxjKu7RIwkdtAbu9rtL9cEG/U0P6u0XntZYBbvbwWUJKCwLz+NNV/sDJxqivnlML0qx01YcDjtqbCwCjk7lrF0LryXMVa0xi6W+f+HBuRNKLh+RI7r5ALEUnzN4Dq6ef70HHexihblnJWEBroiHvtOXrFgpdh/Y4k3RpUJQyQ==
  template:
    metadata:
      name: psql-creds
      namespace: db
    type: kubernetes.io/basic-auth
