---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-creds
  namespace: db
spec:
  encryptedData:
    password: AgAdC8T2ShXeyADIFz7KFQhCUzRPnRxTVQSi3toPHZxhI1eiRprVVYXBuIJ+kXMeExmzbPcEgsIpdqWtR6AORqpM3LYTphClVJ0LPUXxYBjExcFhZAiQOJN/rZBRySC1xMxrCG21CxonTjwlnIGUJ6uoUKr4kXtWgfAsYJyTvo1YYhNrKfFCnBzPiE2TSnsE9hJNU91bejZ90si2fSmiH53kv/top0pIiZ9kVH87dR+T6Ga6759xFhRuQqfv5Nd1HI92BCUmxq7+eDG3bWSRdcmzUVHCuLq7LyoHk4eYImJXRRITr/liaCg97ofDEqWUQzC9OZ5VePZ6XnftDW+D8O90Qx2LpZmJ/47cisKLyVNiy0hGW38ry0Rn3V/EbCnbRJ0U1mMyF+q7QIvKoG+/cP3P7LtHQkbOlQUod4ql3L/OldyIRWXSKBZPO7cq0qSSX2hkIdn1aV8p0fPwDxBWV9p+mzDx37bre3ovo9pjEDfaU6NIO8myDtmYwSgbfzSwNgb/nMT0po4yIv/JF+w8WyDPAYHFoz/ZxnxIO1s48yKZjfp8BUf/vcjSBJJVAe9m1r3e1VjfZhXLexh/83HonsOoYMojvVzB0Y3l7SvVCODMlCxJoXQw/alvBtgtMUx4SADZriwQqRR7qq8m5Or+YfdZgrQOs9eCFfFVKWO2VyMuAhxt7njzAj876eTiCW4UvZtI/UM9wnW/Nd7RWnZaCc42rjg=
    username: AgCurEPD7nFsl/S9zXntgbkdQXohtOzB0ltmHkdabX68SwfXKfIdfFjYzxMr4vvAdMBJW6+4hCDEKZJmccYf0fVpitmAPZri3wpG4EG2MNY1a7W33QaoE0d72Q9PEexJ8UDorylGsupvtN9A5VYEKmOJiDnoaPxEfzvMghfnuASjL/MYUCHjx2l53sGr86D1SROe7Zai6MniRPHgNpgQWxALeGcyNDTcPgXSv3ZZpaxe0UZvN0/h12xbQnYyIyXt6qPvWzkH1b+DQA+9f+OG5Bz+biQje+dc6l2AGl0iYj+Dsl/vRicQzpzMSfFEQM/vv0jds/ibH0AT+GWmhwS+JdcNB0PvXLgSrc8CwBBFBOHq8oPmWq/ZiwvJp5XkyOqk5X1XrgN4yKyrUuzNj8uN8NpnyihLezn/xT4CZycMqDir38+h8vRCBQp4+aoqTdFzNLt/OJ7KeBSlZ+wNWD0yjEVg4JjEACTjjEskAlfeEVJxgdrbfODK3PgIFvMYXREXU6yj5+Z99JjkQBTfO0JppJGan8agiEBqLGNaDuPZk53OMb3w2oUp4bHaub+HsQrbM5gm7WWRDp/zveo2R4JgFb6dEh5+ffX9F4usqA0C/rlF2z75TqCcppi9cgK2L8dfflu55o/hxYsAO+xoYOI7XZbOkuEAylz32UESTCZPBNqRwAsugw8wi8+ue8LM+c7+hGZdwJ04yXgfsQ==
  template:
    metadata:
      name: psql-creds
      namespace: db
    type: kubernetes.io/basic-auth
