---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-runner-secret
  namespace: forgejo-runner
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: infisical-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: "/apps/forgejo-runner/TOKEN"
    - secretKey: uuid
      remoteRef:
        key: "/apps/forgejo-runner/UUID"
