---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-runner-secret
  namespace: forgejo-runner
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: infisical-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: |
          log:
            level: info
          runner:
            capacity: 2
            envs:
              DEBIAN_FRONTEND: noninteractive
          server:
            connections:
              main:
                url: "http://git.${INTERNAL_ADDRESS}"
                uuid: "{{ .uuid }}"
                token: "{{ .token }}"
                labels:
                  - "ubuntu-latest:docker://node:24-bookworm"
                  - "default:docker://node:24-bookworm":
  data:
    - secretKey: token
      remoteRef:
        key: "/apps/forgejo-runner/TOKEN"
    - secretKey: uuid
      remoteRef:
        key: "/apps/forgejo-runner/UUID"
