---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: local-path-provisioner
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/rancher/local-path-provisioner/charts
  ref:
    tag: v0.0.34
