---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql-cluster
  namespace: musmgr
spec:
  instances: 1
  storage:
    size: 2Gi
    storageClass: local-path
  bootstrap:
    initdb: {}
  managed:
    roles:
      - name: musmgr
        ensure: present
        login: true
        passwordSecret:
          name: musmgr-db-creds
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 200m
      memory: "1Gi"
    limits:
      cpu: 1000m
      memory: "1.5Gi"
