---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql-cluster
  namespace: platform
spec:
  instances: 1
  storage:
    size: 2Gi
    storageClass: local-path
  bootstrap:
    initdb: {}
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 200m
      memory: "1Gi"
    limits:
      cpu: 1000m
      memory: "1.5Gi"
