---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cert-manager-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBlIhVohl/xwAlpoMc2+OxxBTQHpACdX4HRhVYYe3oJgNGWQRx2DnBBDwP3DUZVIclqLXKrre30SA21uNz/yCKJYdVrs2v799PxKuM4nKHEGwyAFSQ+Rz5hhVe/aiv7MmZR4cu3WW7SLeEPDOl4pbPFgoDZx9b3fbo+KQq2G8ho8pxlD6DFo2ITOP29cWLIC0H9bbr0OWHJRQv/OSTZKoB2BCuWi65xHoQnVzLgfreVWC4kDZAwb5mwgmaW0P8nolKv3hAy4MPO+4gG917CYJvGEv5LUt4Fp3K0AMoJfIxCfYr9tG1+CC1S5skbqyQ11u3wIyIZ9JMQyfg3huwyYFgnt2d0+5bs4a+4MAr4TtMko7b54D0dCBqBs9br1g77KIzH+HfoLmWvNudBq7ciQ26n+QCpvqXvO0Fa+kBqOQBUa7cLBJ3gGm8G6KVX81AvYRugoOnpM6tRY1NUDlEahIqcX50hnU4q/4kYY0QP4eP9KQo2x6UxaZ6/mEogcEtQsMFHmUAuLhka/5GwroVHV1zl/BhVBnYWYbOGGwwxh0Z/G0m/3fL5GNHK5U4ot8c7WMWFhsZzYjD4djO9I/nAkdB/fAFMdcQ9+XwJV9I2332Bwt7OQCWbXB1RfIYkb9CZaPT9dBL2Kt8JD2Tqf7ev3icfyzk+UGy50Df60cm7N3aXC2sqnt/E0txxSp6B/zS+M3/6kpeVY5+wQRk4Pq5rUb9C/ZZFWJh8rXAlyfO2ubvt9Gp8Auxlcuh/kw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cert-manager-token
      namespace: cert-manager
    type: Opaque
