---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cert-manager-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgDTdv9rIH1bPHr+a9G+yALk2evLahfykoCSBdymMRYGioFLgnneS+tD/u+aWRGKYTvX67s4WldSNjtCMt66u8n9T881ltbk84N28ujCp3ODx1XGrxX3w4CnaPSH73JxZ/gZk2l0S0eYEbeFcBveJ+/9L7Y5H8ZsdLmvqr3im7gUOcmGCoGR5btwd0WIbOo7cixahKnHThD0G0bNQ0ZIU5nPskFOp/uxPnDdAv4KjAhQiLOuU3sQFdERng23JNV/gLX7x/FMUw+BazC7Oz57Hct0B43TSu1++ndv8xpheLIXCHU6IJguCM/wG3Hw0sMvpb9eqHUiQlOADcO9EMmbxuMbAHm058h3OolPrDW7AXxwyhTCU3MVOdZ3qw8a2045fyEjeFnt7GviSCqJFvDs6v62K2uUvFPTT8OuyoF3BrU9syfwnCAFb3PmG9pWGlL8pJ6IapOk1ySC0Fwi51sgQpQxYrWamSTipaXyEhH2SPUcJkavN9cPEzGdUepnPLVowDIX8D1/7b4uC8r3R2b2JLn/Lxql7HorsfjaA1LorBR7/FqnA3pSBaojoWHq7NbZCQJulxEDQYPEVMSR61bbyvGan+sCi7oqAWLqLlRrq0JfG3EorVm7gXWJ5Z3WaY9xma7xOGDDtU17GXPshZcQIQagkUgOAsvsDqQqJUyCiNGicE6Ks/FelLY1a2DM89D9IzeGx2r3KLeVPmorqXTuYPkKUarwN9WmEK/i6qiWAAZkqojaLrHuO4eD
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cert-manager-token
      namespace: cert-manager
    type: Opaque
