---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cert-manager-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAdbc1sATlOdBIWIcgqf+2UmTfERtRvdNLXtaL+iZj4LcdDqqydC1JVptWa3PcxrEaTb1Qmr3OiVm0Ge1lLJHgc133x8ABx0RFBZUOuhwHCtHDeCxaEaJ5JG+v5GobDnF82XwWJ1qqQbwVDVNcIhpZ7UCSMxtUQeBlknkFs7cJJjwCe2sRybRsrauC+vq8MGnBf7PkIxAdNuZZPM63yYQ1nTVZsuEIpPIBescZWVS5vEtNQOxc3UaETyc6uIB4nx37DZ/gG3BkvKl3PbI2mL/1R075y5iFzekPnf3a1WAsOErSZIyXwNpu9P/A3bo5easWJ0+KnNLc62/u+d8kNp0LzxjMFH/yrjIGzJ/4clFG3kOqPPBkFjrb2lyr9zwEzGZoMHFwxKC5kg4fcqpEggKUpBuNLTXviqQq5xAcRl70DuqXY2exmWk2rwn2N5fxa4CP/HFR7wNs2HeotyjyUB85Kp8w2OE0I2Fj6aIec8yQyh5UPtamA32KujBqkfOkGjmHg+yfeL7xidFd2cBUc8UsUh8ODmz6W0XzlKmMjPnwjjfhJN7PvSNpayMFKb54R/7YwZY54Tko6e6Bbhx3QMjRlBC+yDRm7RhSCOq9FBTBUL8mb+heqd1MlWTEb04XIr8HUNXEkKEfRm3qqlhmKYMUZpvIHLUma0Xdi6Cpnz/zk3rIcjD80lweFPabBdRa11H0IiLNzbdYTpQouJnysrZzdqbNPruai0QOFYKzht84pXKIsZF8ZIT+6sw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cert-manager-token
      namespace: cert-manager
    type: Opaque
