---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cert-manager-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB+OfXzh7JkpGeTAu9kZuhN5Nc1SPyJ1w7zWSjN2Wd8EyO+RLRvKJkADEDOPvQZOfW5RBzJlOK2SlO9r8t2eCCvyI+hejGEsvHhH45prvjb1OAxo620QNhGCd8jetZTVr/+JBloxRfTtx4Y2BeoCGYZqHblwmXMJp/VnY3KG4WmYjukCQerHbPL7xbbS1z06qQtIQjmuH/qwjZhDkOwm+JQY75tOrq8jXTXuMJTvixMZqt8GNuFMb8xMzWYSBx2XjQrvh1crVTjXqL1UMsXIQPtZOcDlJU/UrsMsWJ2PtigRDiql4X3Vmz0uErKOS06V7Fy3eTlghCLxIwHd7vdw2y/KqabM3gWUuOAGNoGjtZtCHt3KKAH23AiYe59cWhA1XOzsCQebvTpoemdonzqs2a60zPzQ9KbqR6nUpwemuAa47sr1wb2+9qV4cF5F/r6xEWMLUCAZ4xznpWwFtSoscIFw+xHrnIfy8z5Zdee6t5KuhuSYKozUFWsOOtylmUpKHM7OTWC3+seSI07G7b2oLxvtFUhLtvWeysrMscr81UAdfvOLU1mqFf8givneNKG29tRFSolsBYV8eAfX2j82nZhwkRuJronNWZ6qoO0hfEyqApe0BwnCY+1tvx203jvOhnCGMBu0Q+acwXdQy0+cV6gmaz8jPwzOcvnFL1u+k5vocIo5V41CRwo9+fSRwN0NFqYRttg43bp+ifPgbqsh1ej+e8AnAhL1cmXHiTeJr2C3tK56eCUYieh
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cert-manager-token
      namespace: cert-manager
    type: Opaque
