---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cert-manager-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA4hFGYlqjA7asmz58mD7CrdgMqT9uw+bJlH69VbfSTEA0HRR3hhkImPAMLt60FUKHN7OcX46kDBW74Alzrpa3gjssN5pJjIXK/PEV0n3s4li/3GX+wchyfyxyGfYB5RVOzOIsHAvBTcH+bpFy9Za8NNqfjLfVhvkcPtvQ+23PYrjLChY+EFc3YkDCW7MRzi223yC8rdWgGyQ6gvj47F9w4xIG5yLZCttCoGKrc/+Tp7XKmDG+gxVr3HRRmAgHYParPABeCMFhwzBAxxOfBKJ5DF11hQLoSQt0VK0ZSwXzMfsqFuwMTMP8ZVz/bAULciOq/YeFgVQXvTaPE1fHRviEcRu8y+bNTkMGRChXKN5SOXc4efnnh/WsHGZgDP7mX3letdb1VPR5giTBTpuRUMRtXNY0oVrb6uG47iNMdUktnvQL5XKL2VYrl6AcjA/iZga+ductAW/Xjj37ve5aiA0+AgZ3azfW+RfSHGTlirrCes1t39EUsY5sbCX+HZHHgalyX0A0hZ0Hp6KiiIYU+4Iw23S2GEm2Z5/Zr6K2MqxFncOwZQDKYXYKt+AQC9yiyR8YeP3iI5oRFw8hJHbcxqGKpopMaaTDdbxgJhPtbTCY/kReXDG97rUQCyTTjzf+b8FSnhJveeNWo+dlwhxCc756zElE9t8DZOg+g5e6ZKQotcNt2FDH3vsf0p2pwIiTy//x57jIYoSG+J6dovH+uH1D9o5zWaBgqfY8gjFLrkRvzPMorgFJE3Z6TpA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cert-manager-token
      namespace: cert-manager
    type: Opaque
