---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cert-manager-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBYOJ8r8BtYJZiO84UuqOmUMSriOb5RLWVnKBLW0KDJq6sTmfJXAvU9HTV6FtVpcdfbM19rgXMK0ZvkivU0a1BsdcmpK9e1+eBke1Fqhy75JVo8fLqEjLgv/KpO7epiOB9Mi7R+Mu0w5PzntAP+slyCEBv4TMEm86kqMkrhh8wwCHN0fvtFuZmPCR3rXZpTESIjRXGsjTeQDVA78dtzvKmv7+FZaWaIO5NwFmys9SIlWlB920d/9Ns3iBV+Xot3fe8mvmN48WeqiCaWs+KUPRwqpCAMy5mJc+bzU1nfRJNSJHqemU404TLRbyEUcsahy1RTStHk6fyHRfWL0SKH5n6dQJCGlGNzPq0NFhy9R4QhmrpltIQkdwB7tq2C0EsSAscbbN2cnTVpuigHf0Rwt+Rw3yoL3wd8EYld1g/NqOjQn2RDQroiheSRfrJ770zEoaLIGsS5JKH9EPBoq7JOAVY1NgJqqrmKAsgAkQOTo637/MNqPtfJl+n9La1B6PdntAysdWjilFve7+zmnDXFpoFIUGo47iU8psiC7Z14aO0bVWDH9xZExovdky2fmf1n/EJwfOz98+TdUl94FmzdZ+HhcUn0wu/PWM5vKLC5b+9ZR2ByKs5+F3tWcAkuG+sCWANbXSKdYCzg4z3ZUBcxgfukcoTZ3+BeNtajidfrri2NYLg4eiaK/JNQZ5gPvRSVclD72BcxtqorLZh0qN0A6we69OEmnu1SVUxBc2fsU1HOSCPVhBAcTkNE5A==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cert-manager-token
      namespace: cert-manager
    type: Opaque
