---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pi-hole-secrets
  namespace: platform
spec:
  encryptedData:
    api-token: AgA8L9Zffcld93s8/c+SVzpUqmbn8GR6wKnOFeof9Wts0VhMrTgnax2BHkOgMLZLYxiuyd8Lh7TrMu6bqG59WZSWern/KNB/lACOnKp1TXPiWaq9mscGntoGS5eWwsgZegel4xFcEaJxkDLFvWilGYyO3uw1X27cvtSI7fsrbTAj83DGsmxO/9tDy3AkLIHhIEexvLvEm4Pw5iVb5fyrllmdAtaff29fM7u4unWQwZhuCvTcYoTThqYt2XpG62I0JyzCGROUgCRtm3I9SisXT8rpxAq2vC092iU2cvhqlUVnC2qKHv6XPcDo8L+INRxZ6R4GCPssubWGdfnaGmHieiTCg3ek4lka1iwtxprR/ssait6JQ2TiosyA5XQjivwiDA57FhSfVCurJbL5vJJTW7ArBDqbG8ug3saSX9zAVrAYTnAAek3cX7ww6jRLXQh7/1dzSjRAZTUomdPvp3aosX8RiqvjBywufwy3AKb+7EGmRP4kPOIR/khVojSgy6yAZ47vJv6q2RKxoh+7o+5qMQO+uuHYmpBrdmxfZnZ+mVkbs0jz68hADS0qT0KQ79HcP7Fnr5TTdUkCg6SjsjjHP+4Xj3c8I7A9TQ6AG5qgBaVxAmkPsvWImhy3eg90R+pzqYhg1gMEOu85lLovdx+znUOF2QzZKjaIRtjyx2522MSK9eDGmjf7m+13oCOqqyOXdNVq//T8MDAzPlj/sUwY9qDod1lkdkKpSkQ7fuiS/t9eVG8qS4PJP6YF/ym+WWQ=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pi-hole-secrets
      namespace: platform
    type: Opaque
