---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pi-hole-secrets
  namespace: platform
spec:
  encryptedData:
    PI_HOLE_ADMIN_TOKEN: AgBJvW+ZgDKwA7DR2qRSeoAYisDbLdloOgi9MzrH4U/W+96sJKHkr3ru6qq4d/huXsgoGvF2zcsb5WrDW0kYeYSI4fyh/09pUkVu+f/eHgsnqxbm9x9tyizc+bX9CNF9oCGYrEMnrCczx9LobWEYjnohSaaMvEjmyl9d/TW1qKINRWELX9FCeAnMP8sRuMuVExOH1Ny+BaX7lqLshv6u5F12aCP1jkLctuw3d9DKept7Fnix2B4Ubocob5E2MQZH2uHSD817evurYR+2QDCoXp9wL2kxYHERIyxJcOKTiJ6jUvQbMMwJdNRoyrFoAd92YiDa8nnE8H4oBaFbQ6RUOXE98MbMJENESju0psccPFCI1CwC2F6RtP+YUbjdszSHVj9wWF542xM2ndH4+sUGnMs7GbnkuCwuzVT6XYKCN7pqpjhx/uRnmXqix+DEof3tuO5vLo76vXAvPGSikWTucPKCNHepOUG85ysRnJv416xa8YHS5VyWYFj34U4KVhBUgb2tPuh/xPKk2PAEhNJ2WHCyzQIKbl424KlZC0JWEc7NWcQExiZl46hZSUh6o0Rsj8MqhXg69rrQHEHlvHOQiN1h7fmDaev21A1vsJGlbwABm3XpfgjaPc+5oCl1nvMagslg4SABIRi3bLr9f/KE7Ozn9anD9sXfw8RiqzhmWWoSgzNmZpovHxTF6aAP4AyWOQVr7rTB0gA0BM0b4afWwUIzcF62tcQyMRDHdyAxngtWbcavkjYON9hBLJV6HmM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pi-hole-secrets
      namespace: platform
    type: Opaque
