---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pi-hole-secrets
  namespace: platform
spec:
  encryptedData:
    api-token: AgAeF/1pDGtKbFJqMV+dl3+m0wFHAqfY/D20adLe3vb6Q9r6fbyq7+qBTnhPa54Si3kg4es+k9qCnWSrcCAw2pfBQSDJdqXZ5p2pT4K6XoRnOnM8tG6OAQ47EY0vUF8BYNcbhVdoNh2hRcvsGxqoyxzP9mWU6G6v+jp9DTMRjshYeHhpPmDx4HR/Q1M+Laktgx/pjbQxhvxlxB5gtG/zFffSRmkVqqrBqJkvOKrNBwvMBE5a9e6L1tNk7TDjp2GcSsrtnQ7+cNuHJWDtvtG5EH+aT7PkgB7GK5hUJSse3rWxeYGcpvlEmdSu8g8X560b5+HxeoBv4cWaZ9Jsfjw/q8YVuwzJ7PeBustgVExG3sMngdxkwBEzuuE6SeKYwYz7eJIboGiWXL+lTYUKhC9dlUU8R+P2d+z8ayzXZaFMv1bh2/rAe4cGg5zAktDh5xTlXdLijkh5/eT9vPmFZSryFmn1h0e3IUxaX4Q0nZ+lA+Md3W89tumuGIPhsftKEjmadrgqii49rpiiwUA69fkBVISooNhmSnrJHmB0EP+ljDzdqiHfxtHQlHTMjaMODpF/8YTe7GNB4WCk51UdUjIs71NqZKbGTZHrQ0ofYNXFSU5Vi3kqIFZfnQ1Zwv6tL1MBZWsBghTBjcg484G80RykIHZocRXQ4iJjgadIWGsdQ1hS+6ailspCGaaTrX8npT056e9K0wJgY1x71DhCY1hdCjNc8BLjJGpeETHZreCdmgyT+eqYE2iXz6tIO4dpLGM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pi-hole-secrets
      namespace: platform
    type: Opaque
