---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pi-hole-secrets
  namespace: platform
spec:
  encryptedData:
    api-token: AgBTT1SYOnwGE19RagyOEepCx7Dvbzf139CChnJihsfHfObkzdncpkJA3Bbpvmu16VorUvl1jebZP90WSSGvaidN/nzIfiQn46Gl92mCgdge5YAu7JtGSS9ArzMZBnmIOrhQCeqZrzIHzxrO53gfLWtjWFvyNPamSI2zd8v3aSiYrjEICh4Mjo554yjHiurL6kzo7P/Jqi+mnv/JryikMvEmPQMKNO8PfTyn9Uy6fu+hPDxeTo+mVHN0K+jseOFfDHGCkkyh+3AAk1o+Cg6pVa/eQ7IsgRKhoWoCQgEXC9lVg6oEjRJRiBsHgOjTKvvml97gV/D7zwhcg6lbXDbiYWrLc2EeeJagbjV43DgIllpKLJgkEHT+TKlgJf3JFtIFEpoUBx76Yw9v3XksnIRdBPyjtdndxKvuoT5/D55QNQWh3OIXyCp0RGB+ncdA/u9FMPMHk8jwGbBPgU6riC954/K2nLOmLCmpd6YGd194KphLdEnCvh5xAyW+cA5POW52eCooM0xVl1XKPqfAuC05iEEicNzWCN1jaG9v6jLlnZlTZhDhkuPXPlUnuDXHFtsTeZcyg9H6zPloRyZIalZZM0LJlAMpwr6G7t4LTHycsuWvR9Ky4UJ2posw9xxU9Yw/wfY+0KR9UIAKwTBV+R6c8RlpX4BLDy21Tb4NKNYiSqcOhF+eBs84lpQJ5CAceiAK4gc+cNm9hZ+8HVjpsCkKx4epCiXwUoTE5pQQvTJ0LvEffxkWqnbQ1ssUnyuCdEs=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pi-hole-secrets
      namespace: platform
    type: Opaque
