---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pi-hole-secrets
  namespace: platform
spec:
  encryptedData:
    api-token: AgALcKjIad5kbpG/IE/jZ1gDFE0iRRN6zydJa5zu0j6zgtxnORqsA5+7wBrnnfAtR2mJM/x+J6sB391RHUEfnow4UjW/HJpWimBFOgO0wYY+aOI839zujBIp/UyK9MTQ6OfFju+cPV0r7ps6bEnp0/0g2wpXhlCtdAjCk/gz6BDUtjbBLEPnRD/f6OMjHzYmESYiUO7wJXGicOTih/KHK9WoFit/Y9sllYqmpw80KJXuTOXbNneXZPINF7J9pFqRBeST7rdfjiec5GYzkcS6Z+Y2hasA7e5RVRLQHBq8Wh1Ey0KAe/cyM3HFKSEIfHZ/3bWiqSDb4KCQU//xwVP2NM1CT+pLgjSyVVcQP/IxIvZ4hE82vkrJY8vJfhIk2iPKbMgl9HjRI4GwfCdU0hueYkbtmqK2CMWgsqPjchqwsCDlSh3Bn1KWPOdGp9Mbn0bsWexsbP27al10LucrQaxB97mUpgDskxxMpGt9xTro939qL0xNmocYnrwGK2cNLASy2cdXSZkXX4Ja6aektGlLtCj+5Sh306IEyZ97TZhvLdqoA6RAvjmZmKqGBhZqoh7ZFD0D+CjWLkBeKwUg9JpKhBPjuMA8sybpLOQ0gFxElk0giwbKkiHVODDNrZIO/iPiHO9AdcaInJLJ+jEoXEs8LCo5BgnkRNHWigmGq09YxnQ2AvcCrdr3sRxkuXuW2ESdd7TlpDPec4zLAxSYUQopzJedSwvYgYgtyJ3w05U9shJ3brF4aHQtCNk4IAGSYw4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pi-hole-secrets
      namespace: platform
    type: Opaque
