---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: infisical-http-route
  namespace: secrets
spec:
  parentRefs:
    - name: internal-gateway
      namespace: networking
  hostnames:
    - infisical.${INTERNAL_ADDRESS}
  rules:
    - backendRefs:
        - name: secrets-infisical-infisical-standalone-infisical
          port: 8080
