---
# yaml-language-server: $schema=https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/main/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-http-route
  namespace: longhorn-system
spec:
  parentRefs:
    - name: internal-gateway
      namespace: networking
  hostnames:
    - longhorn.home.voldemota.xyz
  rules:
    - backendRefs:
        - name: longhorn-frontend
          port: 80
