---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cert-manager
      version: "v1.19.1"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 3
    crds: CreateReplace
  targetNamespace: cert-manager
  values:
    fullnameOverride: cert-manager-controller
    crds:
      enabled: true
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "150m"
