---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-internal
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: "9.0.3"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 5m
  targetNamespace: platform
  values:
    provider:
      name: pihole
    policy: upsert-only
    registry: noop
    sources:
      - ingress
    domainFilters:
      - home.voldemota.xyz
      - voldemota.xyz
    pihole:
      server: "http://192.168.1.4"
      password:
        valueFrom:
          secretKeyRef:
            name: pi-hole-secrets
            key: PI_HOLE_ADMIN_TOKEN
    #   apiVersion: 6
    # FUTURE: pay attention to updating this one
    # env:
    #   - name: EXTERNAL_DNS_PIHOLE_API_VERSION
    #     value: "6"
    #   - name: EXTERNAL_DNS_PIHOLE_SERVER
    #     value: "http://192.168.1.4"
    #   - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    #     valueFrom:
    #       secretKeyRef:
    #         name: pi-hole-secrets
    #         key: PI_HOLE_ADMIN_TOKEN
