---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: envoy-gateway-system
  values:
    replicaCount: 1
