---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  interval: 1h
  targetNamespace: envoy-gateway-system
  chart:
    spec:
      chart: gateway-helm
      sourceRef:
        kind: OCIRepository
        name: envoy-gateway
        namespace: flux-system
  install:
    createNamespace: true
  values:
    deployment:
      replicas: 1
