---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: infisical
      version: 0.4.2
      sourceRef:
        kind: HelmRepository
        name: infisical-repo
        namespace: flux-system
  targetNamespace: infisical
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    # cleanupOnFail: true
    remediation:
      retries: 3
  values:
    backend:
      enabled: true
      # deploymentAnnotations:
      #   secret.reloader.stakater.com/reload: &secret infisical-secret
      name: backend
      replicaCount: 2
      image:
        repository: docker.io/infisical/infisical
        tag: v0.43.19
        pullPolicy: IfNotPresent
    backendEnvironmentVariables:
      HTTPS_ENABLED: true
      INVITE_ONLY_SIGNUP: false
      SITE_URL: https://infisical.${INTERNAL_ADDRESS}
      REDIS_URL: "redis://dragonfly.databases.svc.cluster.local:6379"
    # kubeSecretRef: *secret
    ## Mongo DB persistence
    # mongodb:
    #   enabled: true
    #   name: "infisical-mongodb"
    #   fullnameOverride: "infisical-mongodb"
    #   useStatefulSet: true
    #   architecture: "standalone"
    #   image:
    #     repository: bitnami/mongodb
    #     tag: 7.0.14-debian-12-r3
    #     pullPolicy: IfNotPresent
    #   persistence:
    #     enabled: true
    #     size: 8Gi
    #     accessModes: ["ReadWriteOnce"]
    # I will override this once Dragonly is ready
    # redis:
    #   #fullnameOverride: "infisical-redis"
    #   enabled: false
    #   # architecture: standalone
    #   # auth:
    #   #   enabled: false
    service:
      #annotations: {}
      type: ClusterIP
      nodePort: ""
    ingress:
      enabled: true
      nginx:
        enabled: true
      inressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-tls
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      hostName: &host infisical.${INTERNAL_ADDRESS}
      tls:
        - secretName: infisical-tls
          hosts:
            - *host
