---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: infisical-standalone
      version: 1.7.2
      sourceRef:
        kind: HelmRepository
        name: infisical-repo
        namespace: flux-system
  targetNamespace: secrets
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    # cleanupOnFail: true
    remediation:
      retries: 3
  values:
    infisical:
      enabled: true
      name: infisical
      # -- Automatically migrates new database schema when deploying
      autoDatabaseSchemaMigration: true

      databaseSchemaMigrationJob:
        image:
          repository: ghcr.io/groundnuty/k8s-wait-for
          tag: no-root-v2.0
          pullPolicy: IfNotPresent

      serviceAccount:
        create: true
        annotations: {}
        name: null

      fullnameOverride: ""
      podAnnotations: {}
      deploymentAnnotations: {}
      replicaCount: 1

      image:
        repository: infisical/infisical
        tag: "v0.132.4-postgres"
        pullPolicy: IfNotPresent
        imagePullSecrets: []

      affinity: {}

      service:
        annotations: {}
        type: ClusterIP

      resources:
        requests:
          cpu: 350m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1024Mi
