---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: immich
      version: "0.10.1"
      sourceRef:
        kind: HelmRepository
        name: immich-repository
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc
      configuration:
        trash:
          enabled: true
          days: 30
    server:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-tls
        hosts:
          - host: immich.${INTERNAL_ADDRESS}
            paths:
              - path: "/"
                service:
                  identifier: main
        tls:
          - secretName: immich-tls
            hosts:
              - immich.${INTERNAL_ADDRESS}
    machine-learning:
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: persistentVolumeClaim
          accessMode: ReadWriteMany
          storageClass: longhorn
