---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-creds
  namespace: musmgr
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: ghcr-creds
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "acmota2",
                "password": "{{ .token }}",
                "auth": "{{ printf "acmota2:%s" .token | b64enc }}"
              }
            }
          }
  data:
    - secretKey: token
      remoteRef:
        key: GHCR_TOKEN
