---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: musmgr
spec:
  encryptedData:
    .dockerconfigjson: AgA9PjUl7xOrNKzxTtj/HkoCyNNVKppWYeg51xz8mg2UaWgr/4jeYUpwi8Lduq9/yXvVA5FT1qnvw5e/lOWkSA45fbIujK5MryNnQzDFAP++rOjpGqwa+Q/xpbGkWV6QWC7glp50cJF2nR/eVsdx/ml7y/R1SJZeWj+SztivvQoWuDkMOKoAyFaslFVfGC7vtsKR6b7r7rjeiVZVuDEPJA/IV3n09AwUxEssRQ9pcB5Yn+zrk2BD81wjvMDSzAckToBTNgAYT0xVhxLofGIt4suwu3awL4EYhRSPhY9Eh0vBoCFpJjuPyYIMViUvidBAycE0Z9Q/sCYNfww6vk7C0rkfnxBXHFOzMaq6SmdVLfNlEEaP6Bva1oZff1xXodGTKr31eng7Tj1Q+VZaoZSLcwN9Tl0ev2KSioInQLNDOQ0Nzjy68tDIlhG143MpmqJtB5t2QWX9AyBAT7JX4mIihylrsNpVkDFiAJUzGWvQeIQi8a6+CJlxtUsP/BuBMeZRgnbVeedS2ArQzEkw/ZLAt22WrhWt/WJKxu0cEqDswCr6+Vm+JSLqC4sYZr7sl8sFfkgcTV94Ehi1k8uu4g2i2peCG5f4lG9UtkSDRr+Ycu0dvv+5fwzy+5093/2jA9aeJAQx0X3MfwXltpUlI7IH9a3U8fXZ8eByRtD2sC9RVp10DJi9qR6M0qByRmrH+pnn1oomL5rcKHox0at/izAAZgR70G+iDWpeiky6CbyGC67qU1ZtyeNOuH7yF7616AOgL9IvNLvz4YCMLBRSp/Qm2aJrPvbiKliPiLC3TD+iHDBSKTQKHXGiREVvjoB5JnDPP7enbFWA8ElaZ9d49KoUMtXGRcQq6CaTtt8q7sMGPTYQm+qnY9Mppf2/ujASkwhIJlE0SLC1TQFVMF+6AXTnZp/Hec8WFaZXsIsW59b9QZOrxToZHrPDnvWevdyqVftN6kTpORzFbXBIvQ==
  template:
    metadata:
      name: ghcr-creds
      namespace: musmgr
    type: kubernetes.io/dockerconfigjson
