apiVersion: batch/v1
kind: Job
metadata:
  name: musmgr-goose-migrate
  namespace: musmgr
spec:
  backoffLimit: 5
  ttlSecondsAfterFinished: 600
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-creds
      containers:
        - name: goose
          image: "ghcr.io/acmota2/musmgr/goose-job:0.4.0"
          env:
            - name: GOOSE_DRIVER
              value: postgres
            - name: GOOSE_DBSTRING
              valueFrom:
                secretKeyRef:
                  name: musmgr-db
                  key: POSTGRES_URL
          args:
            - up
