---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - goose-job.yaml
  - minio-external-secret.yaml
  - musmgr-external-url.yaml
  - musmgr-psql.sealed.yaml
  - namespace.yaml
  - psql.yaml
