---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-creds
  namespace: musmgr
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: infisical-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: minio-creds
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: "/obj-storage/USERNAME"
    - secretKey: password
      remoteRef:
        key: "/obj-storage/PASSWORD"
