---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-musmgr-creds
  namespace: db
spec:
  encryptedData:
    password: AgCY6rozlMnWGt2IIhHRcuZVuTIoo53+yDGdnJmaUV4UwjIteWlE4lFqP5zI/TksV9vUBvc36DQhSmIFTq9O6SEUimAmq156ea4D3MjL1ZnUA8+PtsZKDljMxKynQDMgX12P/a6ENwE/nvYA91J17qqjaG1FvIfzSs+41WW/J6njxFIUXEdxtktocRPkofMJaXnX28i3r05FAEBS2BNkCiv6jubHLJqm91lsa7zAatfX/ngAhAhB6QCuuKgFir7RDDet5jnNtl5j2YX+T6rSvWMtZgeueM/CsvYV5nMlHl1WcBX0y/H5al0rPQToeYIMVJ+y3NbtfO3We/6173Y3PPwxQUstO45xBozQeRyfvB0IW2QPhnStfFukpnyE5QwYzmT2HnOFgI2Xks1PgnYc08PXHuZeqJ+A8rXh4Txxj8GqxMyJUiy3F4UIuXPtXymltX/WblMfhqhU0CX+sNriYSoDibsi+CfqcJ3cAHW8jeZBXuAoXk9yZVhJW5THYxRd2Dy6aL36nXXknb/luruysiS3OOAa0qwGcDjvUexkj8tRmxyBsIPKwB0FZuy2VhAg9Ut28sdGI14GDfigM0CckhQAOeimS07aZpuZfUtYifTDiJJBxIACnJWRs+2vHvlKDBdbfqwPUEC2IbYJGB99Q+s5X3ZDp7A6jNBChzb2yU+0S8Tu7s2X2FUwg5l/JQtN6FvfXQoI9I4=
    username: AgBW3D8p9fG6dHospjpi2ClWgfNQTJlb4Y7I/agQrcglR59pFCsV7VDpbankkKMwD/cuRkoKkEJMiGGfxa99CmHxZ1lEPwdQmByl38t0Zjo+M3SFkMxaptC+pFyu5yLQ47y3ibmhHzued1R6XJWwkcZlHfUdKLzbCjndd+QWuUGwZypq3sdWCM0a/Y3xxO3cOla8bwIj/JBUNScP7lDlruxnmrmNMkpNy0Hrgj0z3bPspj/Qde6hfoUlQGal/pisKmwzG5ir4FKQHt5A7F+BZ4sCR9fRos5zAfwtMOJG0enzD78242dGVGLjO7Cp8Yf68Ve/AQOfxEwVuLuBQp6X9WciX1uV1UgvFVZx6RT8RGDK36niHHWX+X3bvdqKKmZsv4Tt6KE311nExaB8VJwbIRvIlM2yJFmMj9f7jY5zdzyljRUJyr0nvCjaK50jF5hD7oMIuZHzjUnVSatL1cmCwvrseU7hAQ9ysNdun6vfmk4D8S+cMJvO4mvnGlU4v1DZutsyLQHuTABuaiNIDvITGFaY6LK828aOrO+mEj7GW00V/7+1qksDgKdow8Wv46FRWT7zWs1EsSasXddCCN3DHcnmijXbmJI7r9qGOZa/GOlqdtJfyqX5ngT/S+KpKlJG5/ixFUUE2LoeStPVsPCxxyIwtUpfj+XbhgRDUOMSexkRBmbf+YrkBkzUrVgfT0XDFJ4O8VMT+2s=
  template:
    metadata:
      name: psql-musmgr-creds
      namespace: db
    type: kubernetes.io/basic-auth
