---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-musmgr-creds
  namespace: db
spec:
  encryptedData:
    password: AgCZMPPzkbEKAVBoUKXzj7C32zQtpW9FFuadKBVZHhwjz96fKTh8D3ip9O7CWtwj0+VKwScOIAud056uGLwL9AsFj7hyE2/nvHbc3r/fApmyC7sWDqq5CT0J49EYcxzFpkEse9vcZCukCTe7NPesii/cpUlS7c54t8t6wGodvNyArCrnKWOJczV3d/awGRZkR692PWOiOwZA+Q8tHKtYI52J1NkvPcgjLaNr7/XAnM1ZKUMGtZNgElzXqZKDc9zOWNB8OHs2AlGRs+i/lsHIJ3N0G7acVu4Ab4Wx91xRfvaBv0+zDOf/mMmGNg8HImAq2ZTg+jEZrOLwVxzWwiASK0rO/a7LVcpYnM+rKoz872pcgIu/yuyTKlxKnhxEhHeE1bdZbh0CnqeVEIY/9f2yhvoP7ciz0OEnY9tfTcklFObJBkJG62UoMV9X0Yd+aGRaqKAatE6PnszYNOScu44kvcFH1OTYSoejs04+s5iVnsFV4WgAvrQmZQ71XFjVjs4VAPTww73PiqG9HbStXj3f/7pw0dqZnbHiEbi20uZxNBw/q/UGkG3I88m4de9zMOzcg4BGQlYwtaoD6rdIK+sMsLfMc3Os1y4ayg8R34t9SAidgHNdPqNJ+Awy0T6prnKzkzCBS6hH97fF79yixv4ETEZu1Kaw5mUXQDptcQ65gpYikE3OcovB+YaShts0/6kE3eMiliE+dk4=
    username: AgCu5sMjK01s/wrS1j/fq5GaJhHz4vNTLSSIn4CZut1cxmHiegpPZ5uWjEEzkT8Ixykk/9xLfoFmOVh29sbfTdpfpsJ+/4KykYGeVE+sWZfV/bFKXntecTX5drzzNMLjKNH9eRMjF45bdAiwFei+VtZDyc4zcShXH8GgcXR4unfx/70WjyuSKti2AmI02DL5yCMsGWKcIMc33c38x9JsLOMynM6Jxx83Hyj/pGzrzw2tkigYuzY2hhZK8aXcnI12Wmr3bQxEmrOL6EEiFkpNuTi40UrphYFBYfpNsIAwBJDGmNZiWicsvDqJr/Jrxqb+uwpOI1xyL/PO+kSL8oweyiAn9ZeCnjiGKcCj2DsOreflvknyRbyVhNeBkLyNmEvhcRx9nhZA4ZDkY8ggS4slynA8moli+FX/fbPeukd541j6+MCp3Ges3TT0Mt0k0IwsA1KGzeaatP1L4T5sWdn72eBvVRIwKrNBv4ZiYtHwdBUYmy/G6O/mL6Z/j7igEeH8BqgiwGYG0nwyRSGTRZc60+ZPuG9asfSSakbeaglIn8esgOluSk6rz/XOjedbjsv6PEm49q35cM6gcAshfUHaHcle9nKCQeHpd4jqhuJnr7uARn7eeqB42Dql8EUMYq6kPLJNToNTwXb84qZi4oLA6SPgL8ZEPUF+gY1bpEEyio9l06O8JnFbUL9Y6xesn2NongDcqm5Rpao=
  template:
    metadata:
      name: psql-musmgr-creds
      namespace: db
    type: kubernetes.io/basic-auth
