---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-musmgr-creds
  namespace: musmgr
spec:
  encryptedData:
    password: AgCiEJ6n9G0uFbw6jk1IiLp1UMr9bmXhj2kbSX+dxWs7LQ0cyf+3mRjw3v49NFfVwI7ryCfiHL5QB7z8q5+SO0m2YPsLB0f2K1ONW/O1U1tGxAuhwQvEtPNJf+xdClcM92Ls5fu0eISm6J76rdf2fYVXyWhNYNhwV761CnkTGbPqnpP0WhN6KB3Afgk1p8r5C0NQm56CFJhWH56MYCm+wttZUtQSqmg+PRctDbJGMvDOygHnBQV0a9ZDj7kF4vVk771WyMXObHdOoTY9BaQ6zBtLyvlFteJPnR7nQfou1tY1uSMUfDPGCWMpchC0+N2PST6tzmwHr5R8/EBciAe8RIOgcteGBVYbJ5iRzg7M4yCm/MljOdElnLqEmf0ZWTvcUXnGTlYeuqEwBUr+hhPvgNw+IyN1WkwXt7I5crIyIv4WlVkCKqxmQc8NpUE0GY3Cb+4zt9IYhK9w63lnk9QVvkNGuLKzcmRo/kpoCaRHdDubz2c7OI3Iryg9Ro1SQrPT7TCgvw2vGubMS41lBpqk4CjTGQu1aNRubB6+hrAdGhoiHW39xRtlDQpTkvzCPAQKb52cuTANPmB2XW/qnyn62Uzh86XVWsxMhC1jLY7BAViPbwX/APpKJPKdGOvSayc5GQS+cg1rCbCT/+1ceRNxNHfY2Q1wbXDmDq+6Yfg67jGy7CGWnPl8CAguVL7fRM1RtSUrNPTi1Yg=
    username: AgBQOyf+Q4p01JwA0Zv65NnA5zcxUXvSS0W5odpNj/FDBFKbVHszfT0haEoZJ9gyiYy0JIqCXNhS6ljmdUAvGS0Ip0+T6abhSg+dfj/3VxbhjGwQ6Q4d0iNMdzIbnmXTVEZfqYoW43TyqIIuM6VXuVpSCA8if/zh5cblVwspJO/pz/DP3/EHN94zEm+/ZQTm9U8kbRwtU4wbHZ6ZwaqmK4gxOqyG97xBTvSEyb7dBOV5Ud3YlnHZMvk8vL8c3OHK4eJoFHDDrPcva21v6tqy8q2UEpTOlkJGuiWHRmHiAB6+vVrSHXUm5/i9mnrEGNgUJzP1dAYoDT6p/3340Muf2gfHgTq7ld21fzLPSr2/+g6nwMTM/FpdHYh18DIdPmqs2wz+apXd6psPXcqd7EVuj5v2WawCZ6Nv6ghxrtulHYdOqUQMpOdyA2xAhnVjdCKvraERRoEja7WIzO8wVw4+MKUXZgb6hg3SezxAqZc7S7GLHIKfyD8nNH3/pPNowVPF8DtkXSt52kTVCUWLmDxM80OeCrLCImo4RbVdAbHHGeWE81Biq2L1aYeUswS/2nLqFHZ8SPcbFuGRyRE1sEbgelP7wMsiWbj7JZkQAKB2UTvUNHLQGwD+9n1AkBFF1/2WR1GLGaEF87pctXvRq0XZfcWg8Vg9pjUwuC37FLx5cTdH+JacgL7gcQcI5VXsFYvA+pzCchwlpJQ=
  template:
    metadata:
      name: psql-musmgr-creds
      namespace: musmgr
    type: kubernetes.io/basic-auth
