---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: psql-musmgr-cluster
  namespace: db
spec:
  instances: 1
  storage:
    size: 1Gi
    storageClass: local-path
  bootstrap:
    initdb: {}
  managed:
    roles:
      - name: musmgr
        ensure: present
        login: true
        passwordSecret:
          name: psql-musmgr-creds
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 200m
      memory: "512Mi"
    limits:
      cpu: 700m
      memory: "1Gi"
