---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  interval: 1h
  timeout: 5m
  chartRef:
    kind: HelmChart
    name: app-template
  targetNamespace: platform
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 5
  values:
    controllers:
      minio:
        containers:
          main:
            image:
              repository: quay.io/minio/minio
              tag: RELEASE.2025-09-07T16-13-09Z-cpuv1
            args:
              - server
              - /data
              - --console-address
              - :9001
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        controller: minio
        ports:
          http:
            port: 9001
          api:
            port: 9000
    route:
      main:
        enabled: false
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-tls
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        hosts:
          - host: minio.${INTERNAL_ADDRESS}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: minio-tls
            hosts:
              - minio.${INTERNAL_ADDRESS}
    persistence:
      data:
        existingClaim: minio-nfs
        globalMounts:
          - path: /data
    # serviceMonitor:
    #   main:
    #     serviceName: minio
    #     enabled: true
    #     endpoints:
    #       - port: api
    #         scheme: http
    #         path: /minio/v2/metrics/cluster
    #         interval: 1m
    #         scrapeTimeout: 10s
