---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: musmgr
spec:
  encryptedData:
    .dockerconfigjson: AgA+1DzXslYk3QeF4bz4Plw2bzGkWRDI99KYgKyHR8YR9WdgWKQmVDRpyRVFhAXW+mIwrC16j8ytjsVT4U1RG3gisZee0t6yuBzT2gzBGK89VBEg3lJrDnMTmsXkyXf7IKKkYPIgRnxngMt38NCzXHbTaZGPdjjBP2mSAKc26bowDQ5CfNZ4VOrAIwDCnICfGTFduaTmv+htcvsyjPIr1JXg/xkcLft2MhC02c98K2fNq2C+co/Hw41suLMjWfaAU5CRyBA1OkHN8iN7z9rI3cuoFM5gTIt6MC0F3Jef58PcU80yQ9PllxXSC1YThEoVNBGjNOtN+5c+4Nj7uqZT1N70XEIhHIIUaWNiu4blifJwKoJUJGoty6oW4MN8p4idNakEyHlrJp+F6lqrYAVVNdgDFpfmcl5J1B+/HT4uTCmmNf1WZxGvDdpRcCe7lmHfKQofgTfO2HX+JKkrQvSxetdxq5M3r8jCNJuFxxOO9KBBkRrHBCN7ATWjj/PDbtAJYb+p+OngGdKkn0jVZuF+bmoLAtmg7p/yxL+tq0KH1QOXFYoQAfc+gyLlxN8477c7JCFZ1Bl0Y3N5y4dLnj6pbyyPLrw0Zi0KuMBEmmZFYhkTkYlQkEBEbQ2N29d17na4/ph8lixyCrm7fWQdpeAh6C69aVmD34KsQAwWAiyIlinukr6ZlbnB4sWcmyrLrc6lz/5+rEcq9kVmgWWfxq3jHlXf3utEshUMyQGqXw2+xwadAJKX/hQU53MGoAJ5CvNxOTEjfvFGWUNfbdfbAkU+PGq7gTS+WKV9rHoFV2stjodmtx8vjOMkJzVXHn8MhPUZlfYzr2jU6FwHWZVW1SVdsheFmxX9Hi9vLbu7GzRKKS0ABZv3TIdEXiswgY/BXTnJcfPxqj35rhLRWA9SKUtO1rqc8jiBC1Gg2Yost6+wrPpb7lXqiJbxKhbZuRWmvGs8gnz7uHcF8O80uw==
  template:
    metadata:
      name: ghcr-creds
      namespace: musmgr
    type: kubernetes.io/dockerconfigjson
