---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: musmgr
spec:
  encryptedData:
    .dockerconfigjson: AgARL/L96SJDgh44aYpw1HHEY/bd2dCTZRd8iuMSDlQD2UQTHxtIyasFWjZdxsio6c+5LcqaRfet0ipero2/qPONtc5P5PpTFCSvarc6cHCwO/97EzwWhogq+0voj7dGOj0nK0gRlVs9lEvrBgkdX14tAgszvBnwGlGVUVMK6DfE+8aHp2ABPb/5qu26nsMxWO3Zuoh4PbfGO2iLH9jbJVyLG5WRUg3bY2iZnadYmZC8b+Okbn8POBzwn98ooP6m82s43OMSJ2BsKiQ6Nyy9sjiWsDgZg5r1UeUgOFL8l5x8wNPrIAj3VbVl8ywV95IF5DcrNRWH1Gmw9FyUOg7Lkl7MAGbIufx0Kq6LPqKy5ruOVsQ8I5ZMlg4cTvnfN7BNTH/EZhoaHgVuOLgGXOrk71W+uCF5xUGkHZLIDuhaiEWF/3pYZGsFkfuz3nWSN3tDYvxRyWewS2CvbsrXKu1one3eL+dUa3ECYiM0VNQflpR32Bl5/qtmBxR4usD0oNvxFwScTt/52OpKay0byAXF+NgHxXKKVkdU48+TY5m8d2RimdJuS0SDB1u5/yWckO385sZIWPwUQIUyu/XjJ9rCOOh0g4SDv5VapfYNdAZh3K1qYBqyIZZpsmhtG/5rxMlrVcCj00lIie17CWZ9naGdq8rwxun7pBE1R3Yd7+HegVqPj4Xk707ILRTujUJTvqcyrFa9CZ+hGT6qwyr56pe5pIYQEnsqMSAlEuM97a2UjKnPtgcD3yi8RLcPOF20tvF84RkqNBAxE5zf/YGKzDFtm1K9nXhfXIjOBX2dTNC3TViNaevewWqo/sqYxAn6eoI9H54K0j0noY4eq3VYCgyobjvxkidu+NFlDC1aZaKAYSR1DCYPzzeXI7k9tMfBkOrmuhIAUX+72Itp69oZpb0KMvgXyqNu5Wf6P8SqjSv+R0bSI24VSzPn3DYNPuRCtZnCgMQFuM4QiVcVBw==
  template:
    metadata:
      name: ghcr-creds
      namespace: musmgr
    type: kubernetes.io/dockerconfigjson
