---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      version: "1.10.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
  targetNamespace: longhorn-system
  install:
    createNamespace: true
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.home.${INTERAL_ADDRESS}
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-dns
        nginx.ingress.kubernetes.io/force-ssl-redirect: true
      tls:
        - hosts:
            - longhorn.home.${INTERAL_ADDRESS}
          secretName: longhorn-tls
