---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: platform
spec:
  encryptedData:
    password: AgCPsuCSkX3/ZXR71szKmzJxf7YVp40N7+jNAzwFXbUL479YHgO44F4FfBli/7j6LPVbykqIYReVzR8gBhZ981oyH6Ntm4we1Osq20Bq/DqEBe+gNacTgONoHkv8qA3k3n+6DUh6t/60gOuWfz8omH4Q4ojh0HHz4FoVztxh/diQjQAU/swi4AVoIQoS5xbY3Hu3bLqy35fAx1WoR6k1WDSDazyDdZjAyUgQviTAedDllxtR+0k6u/qJqN2UWTEpDNMrY69QmBtVrC6s5QHfozsvIpYp6sCORyd/9Wb6wy3woYBex0yGaPRky794m8mVOImR1HkRrm+1MiyCHWgpMJ2CkZSltc1ONjLBGHqBYA+vXRUEOYOrAp+D0CYVZR2EBED9seKObczusWgUhIADXOEzFXPzW410ZQvrJmuHzFB2WVpVw6isT/kWh2EFZb6DomIp97tbWohQrWU7rjVv5DB3V75uEcWRzXKj7UPwNBVVcu/K7o46h9H25qC9TfaEcL325eZgdhtHAi0M+o50TFaaBE8CYZss7A7sM8CM2zoDStyNBvZhA19D6AVKfgKgMqSFnLr0KJNahTgB7/C1+PFYs2hjbqZTavasdvXXkPLSRt4YLXtqUd5TdkJsBBqVtQQw6BsKXv8KYF4hm1dfQqhWDIi2LirWhAdei9CRE/pAyuU5ZQ6IaDBgrvflqWDntYRr2DhbjCmapA==
    username: AgA2cxpI8rVvUNpPtcpVZPT8EmJlUp2WWRZqZpFKm5vZ2FQmShaNLRbN544E/UmzQjs22yEAE15ahK4S99GA+G9HxL5N2TLuwxrMfgAkO0mCNfr+6c9JCTvM5mvQHl6adwNiAznVOmzuXnuIMfhz7S8ovymvecqnLXeOwfIdud35+o5lCpDKmPXAPPbWqzkklMnMNJQIBbN8PgvOVPSznvUvjkRkbWBcJUPeY+OWr2tSEhDfUEYOIuHG2jl454afVriYNxXGvS6Sy/o9CqnLGjnRkgUpwYAKHCmsNFn9iPxA7UTFbB3dog7yyCcVJbj51OmgyBpuMCjUk3ARPZfPZUPkPuRvq2X+QGjxSlvPedPCAUV316J7GJgrOGUkh+IIGQ2vClrDHbWsiaTNiInerftP0i2CLlTggpH7EltbFs9ShTxEfonZnRn8+UjacItxgGT6tQDgE5VOh11IPj+daBk3IkzQRp9VRpbmFKkk4xu+9NvhQff8UxrxW9Yr76DAy5B5e+42pzgUSmCovpFHHwOaJ4zaKRaHxbszcrlZ76vOTQ1jOIh87dBS4G+SZ52O/ykvXqn/WLIMDXNeifisJkGaaZJfzieQKky4e8wMlb8FDeqzLME66Ednb3RC959ly/McoosFFCNe0IA2ty9fKG8eZzjslVKBMOkd+A6WehNML6echIMq5UQuDyTbf4h2ldzn15DQjg==
  template:
    metadata:
      name: minio-creds
      namespace: platform
    type: kubernetes.io/basic-auth
