---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: platform
spec:
  encryptedData:
    password: AgBE5wxmfg1KqPBFpAQNsOs9/tSFd2jCLoJXS1KtoLwkDT3FkABG5MfvXuT3B1OP43V7sQossXWGHgX4Dg8aXJY8Q6cuuEHdnEQ0306xZFvq0p4v8ydgwvmst3XMxxZshXBAGhQf/Rh98/Y/F3QEe5WALmo34bK7pb5gHv6kgb4paf2EP5/ltAMwcZdk5L2Xm6rlKAxiZReGg/YbXNsrf5vum4uFTlRLZL0mjqGZv22yYe820gC7VzzvsmFVXwAIOOqoH/OwjJ3XzalCeuJHxdDqEU6/m8amsAQuw7NeADIfxQgq/8XTAnsuzh0QBjdb9QwRAt+r2z+29PSoeoLi8hNh9ZiemjHKcW2rXZNuqGMheZugkKW9mC9BhY+iTY7yKbhzvOBMh1hiG3kI4jLzw/LPdJkqHrBUCxIL8YF1ju2rENBTEzghZUso7ncSZGcTfRWaly95bBFtUZHRCINHmedvCNEU1IDlGrEraQCgmKFWwiV0pqb3VK0w1haX5AFBZRB0jAd41FWIWo1NvOfXOW63IpxGbs1Vnc9XjEupqKcSJOldeeqhDbs8HX7HrzToPk9oBMVsIWMsy4wgCGY8Rqhgjz3wMCCq3w+u2vTzVX9uRsvPXvd+7k91bIEOKTLSJj1jgbckT40Ti8+0xQdQaknadsorCzE1SXARvaJmnTOH7Eg9C//b92pnOByx1GFwglVWtv7oe4hQyA==
    username: AgCvk3Acle6+uqRQA2Lyq/wkxXD/au5yYRvvt7nIMNQMQsdvAm5N2Ug1fFq0Swsogd46Bz2Km0THrKmFB2h31ZFNw6+eqKtbl/Inz/6Pe5TD4a3bKjht1xKC4HMQekDxttilYli3rEvSofZA66JUQIlDM42lHB1RPPFxaVlK9/tI969L4n8ZV7laA/DSRDD3Vb0mCfTvcdotvqw/fCJLmI2R/0Mpa0kOj/zZXTyYDEKuLBrOZNT9Wff723MCwEiB5OSDxJVclO1HeIrlf624ZuNhpkP1i7t+1/yYwsOtILwPKeKh1xC8M7bo6BZ2R/7KnyHPLWGJDW7mRJVeoUc4rkMO1gm5GrlSA4R5QKneB+yYRAr1ap7zyM1o+k+hd6UMF3aZvvrasWh820vRD7anEnfog165/V4UMh91LS71G4suF+03Uv9zuLhclPp4ZhydnmRnGquAa7TZLjafvslcEMf2EfskkODhr0XbpliQTuN9gTRPfMjSHsBdgxUcDuKUMvuEyDyTBulcjDCzSQhCYFvPmfyXHNPOiKNf/abV9jfLGjRKRUx5WjF1/B0PhYGe6mI9BEA4bACD/CK3gKKDJqqLPjTizcQOhusOvflsggAl6xtNOyuC605Qyf6sr9Iw1KyqlEJryBhK7Jezp34srcG3ODe4Ic4TW2xySwzyNR8u+6WH3W4PlLQsWmVKxqsJqK9bqRA35w==
  template:
    metadata:
      name: minio-creds
      namespace: platform
    type: kubernetes.io/basic-auth
