---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: platform
spec:
  encryptedData:
    password: AgA7qKsf4ZxBbglV7D5P77n0+bUap3Ut3XzKmVNlqz/TVzZW/E1QPbdmsJEutFSvID3CP+Zw3HzZoRk4wDgxUsGOuvQ2RoUhUYEwd+d75+bR4tBaA9F4b4oklZJpCtVhhynYIfMIOPJwayE4ARY5Q3HFNSba+zn0RUJg2eK9ZZKtEuSAsgyRD3FePk7Z3Mt2TJwLijq6HlMcI2/FjcDcnmqPRZXRTp9mp2tMt2ZrjSbBxcCCin4VArgLM55QYngnJSPC9ZSMUhTbvfHeZvUJzKvRzoB+nDAovt8CVmbocY5kGmcb1pPgotepL9tUAZ++R7j1tsZT5OSEbZtti2uUYaZDrKeGYvzu799JthlnhqkecFzFp0t89K2iBfx2QgowAb2q+PrGmECJXJ0uzug0uCdPbbFuvAV/gKWlxVEIuYIm9SAwGR+R0HMAO9oH7HtjV3YWy3YWVkO4vAiDr+iViJcYMFKQ5Z/WkiCOZVDA0tH+al8vEvoPgsolOI4SUGisWFM8M01jTWKp0YkDXuW8bkmZe/3WIn7OuJjB6lniumvJpL2N72j2WtGDUgJf0GWulSssN40rk8glVhxLn2BjP2OFpSskga9FMtAe7ilI6XRgPgUNHwscblctA0RG2k5MYY1WCjV3RDGpgq/Cbgk04440soJc2THPeCueIqLd8Xuxe3jBitfi7GdL6zvw++gBzq6FIjIWJvllnQ==
    username: AgBv7quh8Wh+xzTk04pej1B+4kls+0xZEpJ9Xr27kL8w9MS/ZjXABclIfa7n8/0JWi4MmTFkMSdiqhkSH7w6UzL3LC6blbtaQ48nqIh8pg3JYpS8Jy2deq7e5AqNtv93nrXoyaop2RH4jPhUHiZoFIhqNKsNPAmMfmEhkK5IDJSo0LNSLK+TUMFi0OCleVkZvtwmVJ7m1+MhYLH5UJLxn2c8lVj9NSWmu7X3UtWdJzjGKbB5MtjNT1weh2VPaiy8p+48wcGRDaYMLGSfiEUXb4Z7e6tF5GL2DT1+1ZWl5P0w5LA/qAaxfc7V+ATdecY+61DOI3oHc/goGAQfjDIzvdq98YChSJHGx/kntVYKHn0mfaeDHVfQw1O6lMl6KVADVlMRVWO7zMDopRGj3rg1oYSa3wTKwbv2sd4bPFIRsgaMyJaFvl0vNJ20RYCh0TjYEG6jMuwDZJbh7StIR/uupH6U/ec11UWhq6Bps+yT3b88mZVhVczWag8RcKz649e5ggMw5IUuA7LdLr4DtqfV6EyZ+AI1DZBNzfcptZ66l1iiBm7jN85Ak7QmCFcvYTZjGNY9uZGlehJ5BxPXvRSNzjz1c9sQlB8OWCm+vyMrRr2dyql0FI6ooP0225LdikOw/qHRPx0Gu6QAy1QszSiYX4gC13zYs2nl/TbBorNp2mStNfWucy1nD73JzdxRr6VjU64fhp0CwQ==
  template:
    metadata:
      name: minio-creds
      namespace: platform
    type: kubernetes.io/basic-auth
