---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: internal
  namespace: networking
spec:
  provider:
    type: Kubernetes
    kubernetes:
      service:
        type: LoadBalancer
