---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cert-manager-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCY7pWnph69vl/6vmLe06YPM6lzVizaU161HlLDrxMdxpwVu48BCC0Vf3zSmsKK2ZdXra6V9buqM9vx4d+BF+nY7KK2pmNhIwONdMwL4X81aRMw7dqQ8utDYuAjJ4vP6LVXvarTcSfjGQxgJNgEalkXmLsyOWrNAH8AnvycZ8KZqin4j1oevKwMrxgJBMTPfNkeBNOb7O4sTU9aXUYLUJZSBJXXs6/lILanMiy24UGP7XGdkv15Hdbk3oI2bzhO6Jj0KPETEuwW9V/yAtlMyZVQ2+pBnijL8Y4xvKrsWKde9143fQfvuK/b+zFJ7agw5uz8ratHmGNJQyCqxFHGk3uJkEfPdGvIYOlmWsPO+xELMoYaAPNYq6CEceRDpM7LkYLF4xyo2Fz7RpSM9AZXvc4l+6M5bSBOaD8cMweRO3K7Lb4JNkHnQeMh4nabpVtonfOO9z+N7PrNIJ9Hh+nve1QMIF2kLe5dZ5VEFX8YOvSkYWkHNejr0gf+w/SGixTAO22og4rte4WV9zOzIsrQ0dE0Yxz8PqwyChoP+HLvYzDIJMK8MSwkPQjOcVsI8DF8qdwsn1I/QjuNF1ZC6aItM1/vbpptuKDykerI2K68XVaE7vpbauzwJc7MMFezOm00lBY5c2uKxSedQJbepjJTCspJfyvOjNRqH1ZSXgnHtsPnquUGukLx+D1jMfsAiQdx4uWWHiOccClTi5h3DrqCCN3ekpfCWFcBw1C+S4wgByVYOYJRyPhOwXk7
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cert-manager-token
      namespace: cert-manager
    type: Opaque
