---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cert-manager-token
  namespace: networking
spec:
  encryptedData:
    api-token: AgCkFEIlpK3RUt/dTClBpuhOfYfXQrzt7pEHa87DW5qN93WwLBwlsF4ok+tz7Vyi8JXu6l3uOOYd/ZH0dC28yZAOkQI3XtZMHaADsl5b/EzNugxYenTn40PtDRiFuFsfNRSA1SOsEDLc60oDng/ruCVFO3xGVMGOJ9iMXNV5iIObi/71t1s7igOdrPdLLHJddTzzJKcxL6UYkjAozAke5eHWzc8C+XzEhfvHPlkHAlZlNqIavlwUZcLXasryv6edNCOhLS+urLFseKPgZk2FvzM8/5fTdMGFTVuxTBgfzxBWSBQdeBryM3sWvkTnE9tewImfdA6nINfbqZpj5xaCpbORhZQEVoszmzWwWcU6I6DicGlS5uh/NJkn+8Y6B3078b7+wrgbr5Y5cIWcalkyYGKuwKxW4RVXzHYPnJVxbg2U1suYGSX4xGI7DrEuY6lHC278KR4oTSA5AydJpXE41qQKXANNXIRHuOtD+QxXwXeELTrZmNYsqIt0UCyV8qlGW6Mf2Jw6iyQC2/XAzR4jIwYLS7r/e3rwpy86oQgROdU43iMefKgTVHCOElJZ//fI8+PNkpZQ3y92s7GacDUn9fz5Zm9H3xbaAnqG2X/iIWIMgcHNdfkAq7U+aR9Og61ylUX4C2PBt/t30Qo1lqPAhTNFg7mwImj1gS/3qk2nhvFKx7xH8riC/2uOKlqkBB2eCjmqAJve4YoaZnOYoQkdAjHNKuShckLE6gEVmhnSsbwjrGddZ8Z8tG7c
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cert-manager-token
      namespace: networking
    type: Opaque
