---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cert-manager-token
  namespace: networking
spec:
  encryptedData:
    api-token: AgBrz/doQj2rM27JB6dqgbHuIkVw/wVmxgzS4IChBnnYAngsXKBV2MWyEjrWeKMFlhs+VMTX6QR5uTpRIZVhcQH8pDbPBTYETZhCWEbN5XZRAOruAay1HizjT3Y54i7bi9CA2a2oEtwN+UjFCYKK3RUlKsYe8dT68vMf8uuAu0hjhMlz2DFFNK46PKTAqZFNOUMUdVXctKHTzflkY9+3iYScGm8X78bdoFpR9kck5urVgY6VnkYnUf4XrZLXIGYt7Rjf2LyMdP3ChDY6P8KYkJndW+m/sFIYd4VbMz0VLZP3VwoVJwFYUIc89WPwAMIJTASgWxYd1x1CkiGKZrq/Ju49aRrI+ud2L0yjPAWPauHF9RR+dAynUfRGFVmrpBcnNBLMrz9hbpNE9E5eUXZ71KfEaXew2jgWz2OHavX0IN3CwlzOBadTSRBv1UbfzB50wT+fksV9O0J6qdXwc0ixyKrJ41B97pVNGq99dK4mvXjKzC4vCOpmtZdiwJZOi4zZxfuU+7HFbmfIPL/vrHfEuglz+E5gTrqbaijwkKUvj5yZnKSHRrOe1i8/mdkoJnHrT8cAEVmIvCygjKLGcCsVzM54ufaSHLkguaokS3OJxbsFHHOcBzDaFgQt0Nh1T3Yf2OfqjTyDWBxswfCCkVrjyc1RzRiYdxUc3XGMpqnjioBZRE2LpBhdoJg5fI2rc52rQd/Evw8C0TngRwS6JqX3DftkDuW67JfARwxg51V8kbUrcZpCTBxahRxi
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cert-manager-token
      namespace: networking
    type: Opaque
