---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: cert-manager-token
  namespace: networking
spec:
  encryptedData:
    api-token: AgCloJ4oTND39iY9vg8uLNeDWp7vTzeBGQX6dqfIx3dJ/ZBYkX6Wq4iYf84iUQc8GmXr0IkRj2oXOnksBGEZluq5ykOkJEimW8Q+uOQvALecIhenNu6ixpOO3j0bOJQNCxTlD8gP97hHzPlHVYJ8HXN9XQAFUtqiFI8tq1uQcHsa1ymvTgyuSnfJyiQbn3flVmM/uSN2Hshlav0BdJTSBw5crszqRJHcRj+hlxmDr9+ZFK3GoXcbZ0a715GZ4tPaRl8xOSz7Bo0DfJXT+cqPBzlWifzPJisb0UGWvy90guFiOSYmv6Esi4B1/7mqi1NHxYMprmtWWQR1CqnxW6P+3VKI071Z+rVjh88B5+Q8b+Bf9VoDZLiYMYpqWKUPWJhdPJGpRj4jGBZyQUYrh5Dr5dG4q2WaTs7vXkat/SRvuvTLv2CS+hxyneH8QFu0SGty8PGhN+R0imXqmCXmS3awerMl+iB60p3ik5dpfETFqD/OneHXZ76q6oX4v4K+j67ikVrBKfw5pg1Du30n5AmPTXnPD2chH5S2YabBRDfRzkEdMHRcMcgnXnZBOOq54agf8LZzq65KMrB+tqiuYIPhkNTH6w2u+CPRLlyOUE1HQ9lzpILPiRoQguIy8WXmRs42oSe6BSZ2s2QA5i/Fr4fndMqqzRlzZiOWPkPXJycLrI7zz05TDQNUp8uDe8AgVvMTLbLusvHRlrNb2H4RTMRelyyzDKWalvQyt7WS0xGjVdu47JJIg9MRYM3Y
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: cert-manager-token
      namespace: networking
    type: Opaque
