---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-wildcard
  namespace: cert-manager
spec:
  secretName: home-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - home.voldemota.xyz
    - "*.home.voldemota.xyz"
