---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: "0.15.2"
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  interval: 1h0m0s
  storageNamespace: networking
  targetNamespace: networking
  values:
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "150m"
