---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metallb
      version: "0.15.2"
  install:
    createNamespace: true
  values:
    crds:
      enabled: true
  interval: 1h0m0s
  storageNamespace: metallb-system
  targetNamespace: metallb-system
