---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: platform
spec:
  encryptedData:
    api-token: AgDMp4iTYjSBg9KuQh14LKhV2C0al7AC6W1Z+UTQH5p7kV2crvoNV3lGSAP8CgnvOm+zpUB5GI+RlptRGPy6NpM/kFHTKcct+VDRMU0wecmKTOdAcmRx6fE2fnIOufZBlmKHyfTx3lgSHeoGzVg7Y2elxrmtnIL5HaKJlJ9JtHChleNRiOr2dFd+LbmyK30rZDKk8yuiF0rD7V1BiTOIkniGxxxGi4JFLea/K0ZQWsrF+7rjtsuff4QsXcVUU55fNDSLWRpzenXmnFPN/pX2PIs/klHx53rl88m0nDKagwCsVg3blW8saDHP03Qf7Pb//c3FE6Z1A/rHuyc/BNmNh/+PgVOXf7aKxlK4SstED9wC1eQ9I7bfhhG5t9wdONh4ZjZGlLIjBHTRsYnpptQ4PhF2GcuBaHsitU1QFFh0rOeuAMUoB3oDYAlTnpDhEmXdMKM09M0e0mIHZVoqNFJOdO0JJhBK7nFNNmPFRvC8stO8YvEcVCvb/TABQDYigEXj7WSiF9h66OUq/PxOtBN51aKdN1PI3PHJBWd71mAZvH+HbhM86G3kLVKlQdQ0O4tMxICcPTC+5WzK0J9YfULc3eBztfqVZnoVMWMdiggELko6mzv+AeicYNsnWR8bVCjHdO/fWMTMzGJ1y6Q6QhzqXArCCBhvcPYQLnjAXqrJ+kSUO1ZrA4c6/7wqhF1lO+tr/AcoGf8a8y+1LTphlwzXnJP8E02oZZjc3Z7LZul0SUGzrVf7JdYBhgaU
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: platform
    type: Opaque
