---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    path: /immich
    server: ${NFS_SERVER_ADDRESS}
