---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns-internal
  namespace: flux-system
spec:
  interval: 10m
  values:
    provider:
      name: pihole
    policy: upsert-only
    registry: noop
    sources:
      - gateway-httproute
    domainFilters:
      - home.voldemota.xyz
    # pihole:
    #   server: "http://192.168.1.4"
    #   password:
    #     valueFrom:
    #       secretKeyRef:
    #         name: pi-hole-secrets
    #         key: PI_HOLE_ADMIN_TOKEN
    #   apiVersion: 6
    # FUTURE: pay attention to updating this one
    env:
      - name: EXTERNAL_DNS_PIHOLE_API_VERSION
        value: "6"
      - name: EXTERNAL_DNS_PIHOLE_SERVER
        value: "http://192.168.1.4"
      - name: EXTERNAL_DNS_PIHOLE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: pi-hole-secrets
            key: api-token
