---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pi-hole-secrets
  namespace: networking
spec:
  encryptedData:
    api-token: AgBZc+UkPGYXCcvmcwgQ9vI6YGiOrcd4FWlhYDQNrpIuolwLKB2zmmHunzWOAtrZav8odfTTHyEOFa3kn2GU6IC5+lX0GdNeKQP40hBdLyS9tHa6cMN9vPBhWM0RB0jO3Nqrso+PJwiXhhO+ZYTwwMK5RrWL1KrKvQgxTSGgkrQ9ldlvQxHJbj6gJ7+x0EhoYh5CkngN1a9tShMYAgwGUVDIeXchtTJ2/zknSp44LcYNWCN6nhxVqeGsxwT96XLthprsHPlztC3URMtZXQpmxY54Bd4QopHezwKHHaAYpdYxgX/SIXQqvQzSWGY2UYJwS4blt4/EIn+W887ovsTqDkrZjXCXnhTSirFQKIu6L2JXMoWzpTkLcDphFgF73xy9ReBbjUdOucjaSMNpnjyLqW8wBwk6m/G4tfCgzUgeIzJv3ySICG4XSgnb99E772Ji4QKQoAc10xAwTkVf3NdEnIPz8vpf4plm8qBG4Tg8ceH1aGZIP81eVlM8/2TIHRfHte+APQLM/IksNbbG9BSOy4ECv1pHUdreK3wxU4B186yzrv/3+gQdBa4OVIJc0upSu26aAmVFB4xzqAn2/yI5UPxrcXMowRxv3HoymdSfrVbSeF2c1CFNU7UbBV35Y4LmOJACiBSEJzKzVzuT4BikkP7LXZbj5DeHnL+ZmYR+7vtUn705JcaLpZ9rJr0uXkTU7G9Yf2JwuPwEdeoxnLNVlAG2oCp4UWASsmHS1VKWXlWlFHaF9NbJClVnQktg0g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pi-hole-secrets
      namespace: networking
    type: Opaque
