---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pi-hole-secrets
  namespace: networking
spec:
  encryptedData:
    api-token: AgBRQ0K1mYAJ8cUKjutCVgGo/7VyPWaaL6QMOZ5J7T2oHrLLQhl9QCOTThOgPzx+C+3jBv7di+zumw5eYLgfkF9yGfQ9vRxnNDpaUls7tGbL9FSdeZ4H0CNnuIDJyEMvwwlHw9KXde47v2nqP2yzXxU8T2zOCC83cfT31DYT7uJH09BeuHIJNYMjn+wot9qmUkzqR5qmLrZIa6xetZM57bAhnQpb6+MTVzKWVYNJksZ6aCZgyNYyM/oi74XqhqT+ejsQETs//MepwPK9NAQI3TDuhRfQBs5oyTV9Ys0MpIH8UUi4i0sYiFvISLG6UR6bF1pnH6606qHhoJ28L7XMAd825WF4pIto3Y0uLkxpracwrD1Pl/XZJQY5J3v8rnipcbYletzRksWaPm9aAFHgD4Cdlw1fTX9ksx+fFnbb02kNKf4+upfeRkPIJWoBP3aLGgRmI6ovCBulx3kBe7+4C/3MzPMSTgAqrSWC7KmAOIUZv/aMijoW4zpina2dLS3dp5MO5MauY42NcV7pCD9YkCprf7l01LH9kH28jJByHuxFWoz4DWWqm2XqrB/EmwJxCOHGDOPVqOs1q3RIOMzX2wHgQUHDyO8PDClM9Lee6XLzWsnlqEi0mLSrvH5QjoaoA+A2CIK/i3K8ZHzlvHaBjS0W+tshu0FrMxAqWnANQswhTu/pGiMeBBLFqxf4OoUndBjUVkWg+tbfOPfj1cBF1qOrBVN7Iad1cnSjjiJn8rx0N3bKy6a705RtJuRp4g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pi-hole-secrets
      namespace: networking
    type: Opaque
