---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pi-hole-secrets
  namespace: networking
spec:
  encryptedData:
    api-token: AgArv7kHS6nwQ1MJbaeEhbjuvytZcLoIUpHLH+X7pPOfQCO8DOfZ5tk1rRBu14LIPTm80L3hj1oXDCYT01S9BoXaoCQWIqiapGp7lf9eKdjyAmcXgBCHvZtqS59R5UBCJ2qFgCRdxxM538WBPnwqwwW898mtwzO6++icdjQhLOcKt5fAWyJL13D1SHj9dR58NuzBYuhtjkjwxlJnLjT0CdzrTW3LuGoOCLpUdhbj9lM+B/CWahxe3f4YVPJ3g3JDEQzRPuLeNfeS+GLrF96rkKoSgMCRVuJJEwZCtWFHsD5T2egH+bwLoPgobp/VXNy+7V6lA7dB6e3YIj1SxNUdiv3cp1dApvSmwZ//xrfxoVKE1e+oiMgNfYme2WddYZdKdVrLqRHygTLmC6KDGmgN6LJ1NG/FUFAGIFrpfytW56A6eN60e7N4dbYJfLV97ozphM4ImF4QE7kuyQQbTcgWc2lJjmZMUUIj1Q5USVfiEbCODiqpNSKrMnGoTaSYUYDrOwpg+8A1I50SP9qJTI2XjEGoDSH+jvCkam+wRnhgw+C7gcV+mjam9DDZFEBNkarpUOHRUn3mkmBWNFgeqcUV1Nc9C+7ThBDqOLwq/9E/X+xZO6lnmRkM8h9p1EM1Rp2iMC/xE1Q+xsEaZ7XDNUgq3ZeiP77EgclVCVxT7S6dyW8WmBPP2oORwnqPwhOry+oU0HwFYeiSYoheCXxbBeR0ZbJ4H8SnJgwv1WOSfkoefwEtwVY5sx6eZ5NA1oErcuA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pi-hole-secrets
      namespace: platform
    type: Opaque
