---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: pi-hole-secrets
  namespace: networking
spec:
  encryptedData:
    api-token: AgCZHcQajj0PqlkK96BQhCVDcIUZGYCMnUi8zfngEGfmYV18doiNfXIMfhxffAzCnK6z7wmcY8z0YQQdV5kgezv4DgB5oZsDYnnMizdotgsTzA0zBIxnODBrmP6fFubbWOPsFnpjv7X+gV7alpiaHOsOtkks/n+hkdnHuaW4oD5G8xXyMtnEgI80+vhlUvhs6ngl7Cw71NckzsCwAHbq/DdfsGKAJuQlpxex1G8RE04WT81HsRuu8cJXu5BCQw1XWvNfT2eyEAKZlkt/LVMNhHL9H0O015Q5ndKL4rF5b/oYteyjuW6ItsbAu1iX81wtOz49jhkFdpayILHOP7uOjRo0qcWa5gyihnF/2pTzQDxVLmleseK9AhkC3k6I0qtPTvZzd/hs5rCrD2Pa5DxOm1bMFHO/KmN97FxWdscjM9rxSU1P0RbM/Hnhm6ooCYH7XqEnIZwkjD+VStRgX5RFuyZXt6NJywquPfFfZHbksaCwdXJvWozqEXtQ6QM7DTT1on/r5GMS8WsVakIf8GnxE5QGH9Ysw6brZ0MPJg5++4J5UE6PGvg5e4DhM0qMC2mA3G05WhhyTKDItfkCiq3exNJ1DzM4EKI0hZycAsHcJOdck0E/sckLjS4uxoDymskaVxAeSlQO7HWNVSjdpkUnm4on85k7gmyO7EtZK1tx+r6hD2UvnXWYSGFsiZ3jnihmOZsHmbaLQ4BhS8vg9iqKkBVq6OjaGYP1XIgGL/NSiBvvBMG+lQ/LxtUUu+3zSA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: pi-hole-secrets
      namespace: networking
    type: Opaque
