---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbird-operator
  namespace: flux-system
spec:
  interval: 15m
  chart:
    spec:
      chart: netbird
      version: "0.15.0"
      sourceRef:
        kind: HelmRepository
        name: netbird
        namespace: flux-system
      interval: 5m
  targetNamespace: netbird
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    setupKeySecretName: netbird-setup
    setupKeySecretKey: SETUP_KEY # Key within that Secret
    preserveExistingConfigMap: true
    kubernetesAPI:
      enabled: true
      # groups:
      #   - k8s-api-access
      # policies:
      #   - k8s-admins
