---
apiVersion: helmv2.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.26.1"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-repo
  targetNamespace: cloudnative-pg
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
