---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-db-creds
  namespace: db
spec:
  encryptedData:
    password: AgBk/IyWHmbSi8kOP9JK2lTtg6uiq+8oIr/LRAnwmdYJ3nENOk7qkwi01HlvryAgn9NeLwbigO4fr7RhQva4aNHMdzFXDM/OrRqwD/8i7W9h81yHsvCgeW42aO8y/UVeBIOwroUyVoG111xCkAc3jpvdrAv810YgpNbyb39d8tbC/Vd32IRE225E+S7KJEz/QOUd4e8vzXRS5/RlgAcwdw1VN5WlomovoZtqqijSNBRLVfvXTiI/gc1TEf+S9atD2Sm5Y4uD69uhVXVFoCZLs1e0+kfXsHiYVLRCeUAaLA3aUoneiJ+C9zV4uhJr2HeAcoYWSU1jcfGdtzfZaiUd2BtQbhSprQZclOedQpExez3M5AN3Yb5iCYMYaCRUb9VOHqVkeycr14JIp7RHeoBwH6ZpcFLpiDJfG8rp2hKx+fEuw5xOdqubM1ZNq9r0dDDZ9H3vHkTQb9YZoFo1ugFf6AAfZOG4WGP3gqoDf4Cpw4A41Z5RV1eidz0oFqv2sU2C5sSLtMzG/l9QAMvv32GJlsqYqQLkQIuaXs8EL6pTyH6jMuhCqI0tqCLsmSUghYaicWJc1g/P5OtENHH3j7B5HxbpG3e2CjjrrqCNpPrs1gdCX/yXJ+cmK7fiROCF5H2GMxVi4Uc9jfja+SmlltA9ycylC1oW1exgLiWCMUXidqrJSsZOydL5NKtF2V6ibwvCjqzMLmTXlxfcWA==
    username: AgCVgeW6SwTyl41QyTQUXPI2WbMq9k2B/NzRSFXX/if1dmzKEzcYMlvH3Y5ZwOig8ofBNwaKiLAFUN3m8uX2qFKXNeebJn22dIvjU+MbFjvQFzGO8sQCFt0n36OUEOx0oCxaLdS/KVDNXOCVaOLCturltWr+bipAUK/GGKmcKwKLQv6RqTkF/JEBmJ1s+MlH7Z7dgEvSg53M3d7c5yBJbv0B2s5hN5YRtDfmjHJ6U9hPyIX+jb+3VV/XnzpliBnqgCbT/BGD7rumSvpv92spm8pPtYjol0zM5PpMb9KqWiWbxQhP5h7X5HV/4jS85HGX1gG2NLQBZkaSsNLb+xma5ktlKlT/TI6JWMqvWsV/d49COUSBVJmjidDHf2XLJCSXooduJmdDe925kxUmvsGf5wHHwao2wPNqNSkcOftHDuvMmW9lI/eN8ZhzMKJ+Pjiud1rg/P2dEZQCmVJsJnKlzXqJ6TKTgF+OALfGiSQYO7hEXvxW/ZRUtYY1tTsna+qZdQJVidwFl/7dbaOPgyGXGRPURnsGxYdMJHyC7G6Vk7ffHRInBaYnn0TZK69Dwp7pbqzC/K53bXZXqx+C/flSh1fPYHKV4GZtjZMle3xgiyQiD71gBWvvddyFzITD2Q1YAfc3AnXLYiruUrQf/navjDefvNFzzzY76ML7w2YVOeelJZR0W8bSzaOqJ8oxld1rYVmKAnqBpVM=
  template:
    metadata:
      name: immich-db-creds
      namespace: db
    type: kubernetes.io/basic-auth
