---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-db-creds
  namespace: db
spec:
  encryptedData:
    password: AgABYZ/RIFn5Isv3xUHqk0zIcLH0OX7M/5yqG8qZWAg1l6ol++jfPbuj33V22YOY88rj1Fkjumxb18gtqb7j3dQwq5AkXu0yw5dfFFluA4wCVmbzjZEmKz6M28LyU/DwKuK+QQ3OVsluNm1h8F8rFK70XWAe4Vn5oYvg0nBd81PwrAyy0Ij6EFufBZbRRabRet3oPrWVSDLk4znli3Zzlhytm0tU+DudJ/DZD9grKvdQyYZFg0UowbYZpBhia07eeezi0dIb6q4hOfz61YTS8jyMel8wm//YbgO7XEIpdrmw4TQ05utglAn3uqr5cNqCZls6nitJxz67ByQ09MQSGK9aMpQbU9FY2LxhUBsWm+2eOZvoYMYlKstT0MayTC/qiqVBvl7X6udx48tGnYkwEfG2/bwvOyuA+YIqdSeSO3M/JXWEzqDsz43dGNinM1NhgzvBdM1/3wx1Mpj3/kiKEf12zT1IMzFvjWV1eWfe2ksFG0VXG+dTYB9GdDBIBZ2Rmn9G2QSG3apF4GLgrXh5BDYPcf+oPp2QAp1UEVk3Ain75Q1qoru3n+1ag1WYrAgyboyEHbeE+4jHvkF5IrFMvdly3Su+zJXiLf5A/xLs5GFbB0tOkzvFc2JWlW4ZSTCZuDQ17Dabf7J+nsqmDlv8sQXNxsUbQAPZNYnOI19cZxoWvXIc2zgslyR/Pi2SKuvkoPxtp99lvTFpyw==
    username: AgCA2i2bTEfp+CCSckujjQ6zhZbfuw6wh0RRwWIoapCv/PDl4AMcukXfKGx0I2rTNbtLEKoeHghP9pFhIk4ek+wRUWasHidMN8gREWps/eB1MZa1LCUCe7844HGnB0vdxt8abIh/0KlkZXQHOdcLUpSu8+7J7wS3ok2r6rCY6S+Z5ah0RBJ9JRaNzGPZ78yyM0Wccy1BfEyOmxLEMIPNN7uKcfXqU7WLXm9ZT93GY7XnPDwokPcRB8Xk4UZLF7kwdwc9INEvnVUWmi5CW2k6dswjEN2g1Yoj8yisZp6+p90FlZMBDA4UIycfipaD5p7uMwwPoWusPgyLWlEpORjcQXT83HKMYBCc3i3fvRSHlI/NoFLpPQ/f5Ob16zM7peUfZBSBJ95A21DlbjdgzfSsvsB+x4CQI0HfdaG0vHGX8tuxdt85CmmLgOKnxA2/VCw5tcu2P72bdW8hARcHeXSf1yJBCyMGluey0WHq2o+U/UWghMcjLgJ7Qrbis68CefFsAAuk6EsDgE01VSSqwRfr2pBcnz0vKaptwr5LEekKmGxb5RdWhGTg7hwkrHMbcvkSfPGwd99YGSHzA2OyoXpBNnFdF4/dOwju1ov+LUJnyOcvwQAc+hslUaDRxoR7i/o1RL5MambTXvy4c6jAb06ifVyxr9zz9oByYFm6Jcd2S5+ncSUufTNFARI5WtA+UdorOXbykiLL7Fg=
  template:
    metadata:
      name: immich-db-creds
      namespace: db
    type: kubernetes.io/basic-auth
