---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-db-creds
  namespace: db
spec:
  encryptedData:
    password: AgCTIUYUlykghfW3RIyrcmfKiVnbjDEY4N/aYKedZBA7bDjF0YGpeiOURxGFWbX2xgATpIQCVP4ksv9/wViKB0n+mbcCSLm+1r/iV0svN3gQGDnidKF1bATaVZEb4jlnzXcjYPKYWHTD1K+97eQnH86lFc0omhoSH+I/eY+rieb2g1AN39YfRgDYtYC2o8PrugmJgJKhyc677Cs6vtGgn1x/J8dkzSHO/TVqA+VARaUC2zSqkOM/I8S95dzS60LlOaErAOoeaey33Copzmft8V6MPn6RTrjvyt1N8rHGJWxI0NyiFZlr1fIufbRIsv5IJk23GFVfyD+g34WkwhlGHSVlQNJRP/C5hCRz4z+iwatzZIi7LFuzxKuEJ3PyW3jXtFpqxy0erahJRqaEhFephqOmD2G5x0OH0OlfRLVFTtJWF6VuoPlwtbshS5CyXl0b6WgUDp+1m+Dd0eFP4a9TX2zvEX1ruy+a8ZUikq2qghSt5/uI96bT2RzQSmuLY/iRACccrlZOcFwNgnTC44oycIH/Z3Dw57HShEX+ZBqWQwkU6JCKxRcvff9wkdiRj4zAN5jVxrfwHKsHjK1x+yZ28K3L1XwEIDyaxiJ/9rtwCcw9NNL2xHNevdr8TTmIXOjwlG3EWcBlmjqK8G8NGAiAOyHYWvJxb87OzpCIPYWnw0RY+XRjCVlz7RP3+oZOSYzyLgKTGvFQQyd72Q==
    username: AgBxwIeS+Jh6XFm6TixVMgwwpSrmlOIg6Qj2OrpRxwKKJg3mmzEEJO+8hl/zFtGuG8VuSJkn4oxQHBUV6R3acVlZAWClr/T/lIIHrxEu1XmErq1mJPX+2wMZQoXQ2wYmKH47Go3PvaO7m69+0dHAvLqk5JRHogp4Y3GX15bv9LbEmEO7DWd6v6Hf572q7G3vHS7QqNJ5Lb0H3O1SQrMf/8z4vLPAHzYEL0uhVK7Tp2iY+dA580zwVdd+bF+YZemjcWtbTl0s0yUF21aklVbxvdTLftKHa85tufxxvpoEU9a0RkCnLhLx5ih9dF9BBJHuLNHFfCaTw05EPmTKhdylb7NjjAEwEWZx3aiy382RjhNR7SMz0sUZJlP0FB8GWqszBlyOnxZ0VCFE2uxcxOkzCcjnXiGuwtsPI6v018pMeGzknqoR3efEQgkeXt5sRT4fa8NuxK58hv5RaiWI9Mp9aiYMLNdI9ROceFdt18By3L0gfZVUgZt+kRNyYFdbXriG7CojLYbuc1AYsTSULz0jdfisDZnJG7vw+4YNFUH40VB6TJp6gN5ps20ckbM8Om7DEoHV4kKUgIVXqv2tXf7FCDwdVX+gaxL7VZocD71gulBDQ1LM05SIMniXpwm/6/AsyofYwKshyyR29sk/6ZdE5Xe532hYGCvrSOHTMLRi2ow+3hcW6ksEtnI+0p8GO34aif4UtFuAxBY=
  template:
    metadata:
      name: immich-db-creds
      namespace: db
    type: kubernetes.io/basic-auth
