---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-credentials
  namespace: secrets
spec:
  encryptedData:
    client-id: AgCamxM876pay4uR/lEdAyKAe0b9seTRfTQDoRxqS3ouZ06EJ8Ci0AAe1WUzCrYevvdDbpTrECdBUdznTJXia6O+xWe0o7COaAE2JvJMFIBvbLBQ5Hcg9UYoOcXEKrwTbNbScNmzh6NhZSI7IwIlpNRtK8dSDh5/XF7wSrC0SiRn0ddE3nQdp+DOC8/sbg8APtO623JjhzEMk2njsRyBjEdabSoSsePWBrZDuvrqI56xgubE/T+63RmUPED/Eg4FuWYBXo7ZRzaHb3dZCwIDHLBHlOjsStM9+UVDpd+LTJ5umrqhWO3teqXcebRUp3AIzKdTLi/HQqUDCv/eJI8t46vNqqCu8gMk3DhuW4LdoDkGrWiiFQiFOz1AcsqjoP0g2Yf4+bC7OdUXhNv1jWYhTTDi3Zbv9GLYFrgpXevcsyYgKRz/QED0Dp2oRIl2IzxoYsLrXxXYVHYZwjO6MfHZHz0OOJYUTudgRiLwOyPDzUq8ABC4dB9viHwN1+1en57/rOSyEh6rMaf3mMvzR8FWu9q6utmrn6qJmuAftDSstvU5dj2B0YTsRWZmxHcqir88OQoO6qD2YZy1S10klsZq5AmN0iUHP8dRByr5YpX8lHsaIb6Wzu6PTw4BjOcbfmXqgmMDkiinK5uxGZos8wvIQ7r5H7Btvqs3n4SXgDRQ3nkhlsObIsSsUGVWwaOzh2NCA0LMCFWnCFvcBkpI9pgMF2UQjMKKRQ+VIExObQlNXdkJDbZOnQE=
    client-secret: AgCGv2pvZjuVcFfedm7BX+72fsQHvSzWVj8DSrYdmec4t7Djippn5oXWoEMxChqeH2pGu4erA7Cjk/TOaAd+5YBxcjSmrijOpFHlQlEmURhvXeHutMu8oy2xg6M6S6qw1MRnkQPedQuhhO8Ov2HiMG9NE/i7WjOl69Z7OA2VUR8BjUHZhKv+upMSBcgjT/6+L/J9O1aWdrnlHGae18f8WQq/IoG+WDqp1dJpS3gayp7edJuVIuo4DYpinXF2NkxWRDuTxyqI5IVLAuO4JVbM3HbzZZZ5ZxlfJe5K3wKw6KlL/qMibQKLwx5HFpYbRoEWe0YEwp66fZM3F4LUpD+oSz4xbcatpBhL3BdlE3PZ4xpPzv+W+LfJy4YfpD/X3oHrm0H4CgJ5EcjZgaL71EVGMjIpZDcSEMkOtkU5DlSkDDZE0uAfGBgOWcPixOUv8KBdL75yeYcpMH8aesVyO8YDi69EsaEAgmA2/v7oGPjPUqPjRaXH0ugNckwA3IY3L4n9guU14bu4RYwn7fZcXMHv3Vzq5/b3ErPFUkcZyak532L301QSUdGwI7R3Rii57KR30xVV3IXPgUTLHBd0pW3dE+Q5gtBQKiIkhl/MgFp3Nu/ZUhrydrg1ZuxzhxkkptribGEv5Gzd/tapYmdgX1lktImOSFFvOnpsI/WA0I363tF4CpoLMDI7iS0rMVC3+A5P1WHaIepIS2Xs0Ql4aX0VIil2FoIgxtKbbyhLe+UVTDNHDxI0GyX38WM3hNubKre+LerGitLjJG7wvxsoTmPaZeOP
  template:
    metadata:
      name: infisical-credentials
      namespace: secrets
    type: Opaque
