---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: platform
spec:
  encryptedData:
    password: AgAzWFZSuHfaHBL+JPCMkKQLUhAPu0r6YwUHXiyLGp36TiwQaSW0t2B08ePhUHMhQun98mix7zsFuGHodmyC78Shc6ICuCwB2/J2l3VPRAVUdclk0C7nNHUsS7ko0L8NbtH0UHR75F8WWckIh7BNH3SUovY7WAyBMbQxl6Dshzm1ehB1hKo2I9jpOlSLiU7khBFLqSbm1ucaaZxce/zLZIMcn/qIxp/uH+8lQN7FQ7TCzE3HgSLgvBpLakmOXBTXSJCke9Uv0CKwcNwIr/0V8qb7ZXQh81hl0+kGcPMBtGdVvqIjhRfmETTmLndDyKAccvSw+5ZHrG2QlMjVuFyXe0PRlN5o7uBPChQptSjaCgs4PAjncQEhioXUdjrtL9/p4Y9XKNvbMhDPYhEMhIxTenI2pwMht6zxmAOLPutTpCLj8TGoUYprNVyCSKh3yAe3G6DxOB3y81xdQ1e1T6h33SnA/mdE2JqWo/zE5Khz4INx/3ZgiwJTroP2hizQG0Os7eKJ+NzPBTN2KZcj9U4BohBwvncYwRSL8rKJSe7MqFmiei+IPZcMLl3Doyrs0GLmePAGNWX2PL7X/DcBzm/L12TxRVx2s1i/t/4JxEIOyDa5qwPxeSnsmKDjjNl8sVJBeQ0VNDstaiZHk27/RvPjhc7qWk8J4/FsdFWj1iHc//GbknZSeVFeuW9ILIaNoC71ZMzaHhLpR/IjdQ==
    username: AgChaco98P7UdMYC9+jUaYYIfbZFcTe0HIRdAkRr7DkuOkHnF1EVXLgLmaaC2Na49Uy1t/HtK7jBpdMg1wuUhXyUetwu5EVyaJH+tt9hhCtgu6MvkdfeJlwxdsXlGE9ODoLQJtGAiQ7sitBLzGB5HOI/dMHTJl4c06Twv8EwB9B46VXLoWSfYs7sX2cvbpegb7zoLE9afJS5p7H3MVrGQ1yKtxklrJY3DVuoKMQPJXDuva64PaghFqUDLWoyUWEYsUljqhonG6C2cc1RonnS0S7ZxC5yDdgNuLXj9vG6yB8hab2gYyn+XiQXGyb/gyy077qrThaXWtKzphBOz6vKhV3RDGjqrT8U8El+AVPvVCvC/vWol8Yql3ubTgWFeh7ILW/WnGXgMJ4GX4fhQkYBurKc75tHLaKp8UD7/1y5gWx8YRjC5w98B0yFjDHK8VfKfmP4DTa0JDQhE+vO9uK3yjPp31LrjUfEA8VUljqzLaZPKY7R+dXAQ1pjogRneVtSM9ELO24KKO6Srylw5/gitU+PfrL16PxO6jSXsHYdgsi9YzDHaV34OeIi92FOVPgsyh64vzG2yT70wUu8OMDJHZlJ7UpTQQqgibYredhw6RT1HXlwkUL3qEBL3D8I4JR0DXEm26HXitHrP5362UxVK3yyPH2/jtQnzkxVY7zqtY+aucRPNXkwHCQPfSkZG4biA04+jB+nmg==
  template:
    metadata:
      name: minio-creds
      namespace: platform
    type: kubernetes.io/basic-auth
