---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgCKqvD0UF/yzidKjeZyRQOCA2J7FC3VhmRKW2XqZOnX0gljvqrrEkNqqzFNfPtKuVO/IhYbo9id94cS8VE+wqRjpavavayVWJSflIxyJEJqv1xdhsyV/cOOavabyjy2GXgM8WhA0gfmSMW/yTWtK5HgfcPkXGS5gGFU2aHXvpnyqIzpkLAb0BbyvVvz3z73L5bgDza6JOgH3VnrCgqVyI8jqQSC2xUktPf+q/1Yt1EAdP85SbYyp+RCPqCLOCdGKc9TkpKJdoZZCnri1BSqGdlKpgkVhtCGadoJvaid5gukYyWMwUlxwsSDVAQQxOuv2VEW8W50h7K2ezhVNY8xKtQY5jOruSXkXv599iZTwHsf3ZQX1SB6Veq2ms3L1Qz3m3OXsjBFfokU3qM7iyTiDl7ooIKNxv9Ulo8s3DpKf4Lx2Ia64QTVOyF7CKl4e+4hnKtrPrBzVuIvWVqPxK+iJHNg0U1XTfHT/Uk9S9/TZVnU7+TFk67FtFtzFkaTUfmiOJmB05EN1cXFGcWiWA6akIOl4DxfAc3QxCfVi1mlYOMobQOkasi+PFVZo5Rd3Gn7JIQvne5vR5RYtNq8uO1OcGPtnQEaN53lKY8RAL7G6rhRSvvo9c9x9Ve1Z+hN+bAH3U6dDbnbxFjNVFt//eftf/nA/XVPidKaT/KTH8V1ORgCIalr3UAYEwz2Wkbd+hpr+FF8XEskjtqpwg==
    username: AgCOeGfxk08BA3RTWVr8h6Jy4C5PWqWETFuAFG2o9Cn5RXSb+fdsiy6zB37YxJTwMisKjdrNjliAVFgYLK70SwRx1KYRS7YcSfomZwBFfnySzYARRTDQTlUaz+nsQiybE52msnAffbXs9gHOzwCPVnc0nY0m8En5iAfif40XLaj28Az8xZQOEy4dzKYlxyv8DbaLGGU2vCT+3DlnD1bQ5AmWB1gqKJeRljyzlza2W1E2LuDUcM7tKdXa78nKYJ7uOHOwB9f5OLzIA5yMzi1FtXUvLje5GidtoJ15sNHfR5ptYYSdKgaHpLVnsB+LwePW8NQsvEsd4pGnCu+YY/iktvws9dVJXkziTw+1v22cJaDT3+7z9iif9omq3/0fIGLyFrQ6UjeoDrXPxgfeUe91kIezpc7eFlbZgdWUBYI8eQTdfCmxlTr1ijOYGaqDiY+8r19dzn/svYo1BBbCruw5u+2dX45udCMSRdJ/7H9szFMXlPuEtVgPEfThe3Dyk1eGyrKV46BvOUROO+IUD/Q9yNuiBnkd/Pkpn99oCO5WTp8dcwPUE5oartD3BBPQMmv29RvhHP6lFhJsRd+PVVtXKP1KwIq+tuYuohSwX/0C4hxzDupyiL2e02zfQVlu/FhjOvvqExDju/ZJlW2hLV3syKh5kSnQfWTZ12Cmr3CSgpoYRGMhVA+mxKHC4OyVFU06YZxOJCvVrQ==
  template:
    metadata:
      name: minio-creds
      namespace: secrets
    type: kubernetes.io/basic-auth
