---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgCkpEpkRdYP8IbT2kTjdHLyjtVOPBEAZqHYnvH2H07372cVkyCSWxP07yLRdQUcOz3J+z5ACO+h+8Ev3uiqPn5ubGS3P1RQu8PavSrwfYUc0AAyYnHxYP5luqBizbZyuYpoIsHbeTTkokGV8mkgdoZjyxFOeq47JFbDZNkHwbsUu6VZzaNXnpvszuCwXA4Vm6gNUu9hPrJKQiLzHmVueKRNK9z7toAUnLEheHgaEVvQ2aYJqrQKBBFS4bU2Aigj87TNa0RJAsVagvAhSyYV3sTPKChjIo6d5qzTEIo3QKamWJNjMN83IgRj4cW1oDmsOWc+58ceyydPwduBJFfWW8OWS7JA2CdGElJxiYTfQc5PeyitBJW3grJjfKHAGHbELqXluM+pLzgaiAnwsucLfF2P9EKOnASEl6wCgikPSCjdtsAoB98Er1tjNoEQtHxd6+FhNlF+w2E093h9zrQ3aTu5g4+zrtm4vAjqtG751zUZtaHTcoqOKKxfeelSzqsWEAXyCYc3PzaRzQ2FZvVRpCFIQk+AFahoIPTiAS3msz01fdTKBw1OpULSJ21tZC6p3sQ/dqHYzsLUWHA2obhkjTsCNu0qaDM+ALSOVTsNNypzzSSC8ZIEw+3851bZ+Q1Ejq1Qe9z5gUaq4qGLxxMKVmuT36D/+0Fad8wIFYsPb1mWM8u1/NTP7V2l/Nn1wfGobRyobeP7vFngTA==
    username: AgALmw8CxLk2Qzy3RAOSErSH+Co+3xdKk0rFtKIzqDiJ2Mg9K7fYW1QqnfSHvh2F7fVDcHtMM9ckOcce3tCeRdFSmirlbtz+sj4P2n/m8bJblXbFdg61pGQ1gdXD7wPSPB/PF0R63jQcAvdwDxZe6p3KFZvAW0s7Bo6kHXxTeWzv36h+3DUNghO09BI50oajFw/tQbMSICEf0A4YvfQsovQBhduYDIth0XPNfrXv7CDDRFynniO4geJYgvv27ZYzywWgFjeNukKP+Thi/K3y3Qrt6u+oR+NBAEo73ww3b2ptYNHvdG9Pbfl4yBvLFARu9SJJQ5fnlNmJBkNIGxvRKaa20l5d6ovs5zTmc4PXEbB9efatylKidOE0Q+HBPtSTDH2DRG3GckpgzS8cRgYUkzIH95704tqX0MjzAGEG/2hEfN3fEiUX7lopV9y4qAZ2hGplxu8TcxiAL8Ku6TXFikqMrhVKIxC29k36UpM/XPg1j6iNWDCtFDBroI16y8J4wdJUuwpxPhJ5+FDhuBv4JzLkwM28yWBRWb5ntz9k6VXg2Jh0btcZVI3krk59G0yVjZhCnOsnxUqDuhJRWa0ovFfF7U8kXpDN8nvJybDE+czzz5OdCNeeLg2ykdKr8Kvh6UqE+C1wTdBWLlQEsypN4Pg7C7RbowEnNJh4tykHjDpkmFvXbCdO60grVAjqhp18Cc/I30zMEQ==
  template:
    metadata:
      name: minio-creds
      namespace: secrets
    type: kubernetes.io/basic-auth
