---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-creds
  namespace: db
spec:
  encryptedData:
    password: AgACJdPTYLT4+oZ/UM5aegCblCtHg58FLpOmjCkfKokADvNxSPPBzDcOny5PICGPz8E1zhDX0jUI+I4x1mTbUE714HQ+o8CE8fEpY4F6uwasmbqMCE9lfZixZyZDR0ds56tU4A1hD7qthUgdlUAqRekhx0NBIm+VvoyCvb9SfGJgqeklJJDQ/Ip3BjOISd6PuvtK9pHcLGecmZrN35zA3XWU7oiqfUaZsldeR0ZT0AA0WuEe4xsyJFQZfiuzIStHEJVeyq4LLED4waWrL23RoblhKC61RG3WIdxX+VaG2/bgM4CCk+UmRCpsuo/5RcgVzjwpTsm86/1Ot5qctf5T6jY4wfG+AtZY20mZoVxioFW6+NftJ3ATaSFJ7OMO+w45rRQOJqY+3rQz4NWRQabX8KDM12k1AekxO2hWQw+0AxM7j5LBS47fhjZuhY0DV3VKGB6uZMZjJbA1+zuGql/M41bTgtqpS9OCSOIBgBYZh3Fa3WX2ZE0+ag5Qze1+qlteidgfgO67CBwQQV8B43Gm/FTzd4p0wVEb2Qokz/ETnH1es2yDUTqC6G5ONHpQ2V2jnV9Bft3PkCX0HOpbPkm1VQhUBlF3hvKm+wKlsQ8B+tQyy+KXwOl9dkjz2LzCcbPsYHbVTBMZOhfU50cr3xwvyQ3ZWgbo4teHJUcsX5vC58tKB035c4599KsR0m8taZ+DLsmarQuBeSVcQey9Ndx000v7vFg=
    username: AgBi7lWl/r2yYxpr+wLaWe42PwA7J3olnuySCBec/HU5XK/RTqn4Hzo4NJ+8bZYRhtAZt4f9XFQQ15eJNt90ulb0EfK6Q/2w4UAsUtK2zW2PJAqNqHKRUN9vMec9L8dze3CeVJBmsCdj1E5AYikCG9ADv82kJz7oxLC9l5a0y/kaTUGzKgJOPJZrpmqe5y3PFzT+s3GbOL+eMTYsYadKxkyJAijX2EoNA70S1eAYPC/Qfgmwu/Om2bPnUy/Q8aYDlu6mybjlzUMwp/11XkIsTGicN9aosQn25S1LF8NjCMiV07q6j9FfG/GU3MnoH+ExEP/nwotP06QNc/nvdnZegcUR9DuCz7YLGO1LUOlDo6dv4+6Lbvy53gWoKdZNxD034DRXowySyx9hTqHbXk/jmixj0mZvFdOs36Zqe8xvWl6Ga7J4qJfwW+s+q8B4Etv1pLyYF6N4aSlWRnW6o0kY5eQvCO+TAX4flsNSBvC5nXbEcdEpYSkjOqPZBvwkR1Nq43xQWnlR8Us+vMK6mNxnfH5Z5BRdlNtjUN/tmcOBh8r9KCEkRT4/OUEGRTpPCM2uU7EKYZ0+tpJqjkZonpSOSSdiSQinu/pELVt1tvVzowNyhb7LVE2JJuYLXxIE19wlJLN7avWSppqskITAFoiqNdDEiaTeBFSwyL08C3osk19BEV2X2XI+3+T8Bp89vTP0v/pJHuhz+q42UA==
  template:
    metadata:
      name: psql-creds
      namespace: db
    type: kubernetes.io/basic-auth
