---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-creds
  namespace: db
spec:
  encryptedData:
    password: AgCDX6cviNR70iH5qCk5MC60tMpe+d10GQeZNZvHee440hk/oHW7qBaQ1EDQ2urr6ihV710KSet4N0UQRWvhUrJK7unTMiff0E9wpWFMJ1VX8uSeKFYuHluoV6YuS3wATathbLWFQF6Z8+uEJ7DOJR1Tcu3XOEzeC65f/AkDWyLENiMEg7LVNe1enYcSjvRMoTw3ZNRaSgKuwhNrnfPlhg+t4NG0tbGmBrpvFoQKBbcrH94njNbGE+T65Yup2tPo8kvGz21sWQth3UjLhqk3FX3AFa9Mpp4Y0MAHMfxYhw+rIj5KfXyqboMs1rUu56+9P2uXTC0rGg1ar7rQINFY4DpYZHWFlv7DJEft+fAxkimaGUsOWtQ5bx+0ZrbEVUh25Gxh7cdLBEfvZyRWY+zI7kduGzH+ImdNP5K5u/L6RQzH08SoUaqOIVLM8L7guwkoQxKCuOchI7ewhwGl9v+4d07QumT5Lr28Dj1mbPZO+PQqI2pobUvJuhXuqpGzpLBOeMqR35eRxUYu7fUeR3lT4FHp9ZbNODNTLqLE2oWfVTPfBqndGmElyoZqfAiIJF1SGkkR3GpNH8EtI8i3CvOO+R9ULVyJCAizKMp6y8W8J0F/Gp7KNGtbEn3MWt5snqYjUjRuY/SM9acT9AEIYeCereaP0TxruvahKkTgItN43C+Y/oN9NXW/oSAxpoxAtZMMCQ+ADHjbNxmaT5ReC0sQMXZsF0c=
    username: AgBEAePum6DHdFPdOpjBqDo9p7zlnm5fLJj8AUVYqYvDcCJQtTcXWKQqREmUlWzcCJJfF7CotwG9wU9imEygzDnoeX0tNYvwg/nMVs8KlpzbDmJ+D7R04/GVB4ldz38qPCe54IrI8dG8+rqb92V8b6i3lh4VdS8xiHZnQONHKM/bLNYFwlwLHgNVE2AlCa5vrKeXrfQxLS1y8NCN/2a52dh+b14WtgZS+sEsxViFp+74wDFRoGfzPYhs5QSeJ8nSOLpXln/UKGEyEwAIh2ok9zS1+m4WKYX+AbgmiN0FaOmwba32YdXU7MHALttBb7+eYct5C2oe/KiKhvb7ARY9aURkKiKSESHb0jJZppxQPX8zasJPjKKc4EoLVQ/Y2/UumQEGze9Ld+kn8lYjOoLUO+ISa4MU9VKSGpmMv3bdry2C4kUcg2wO21baIrIyACewXONttGZ3EuDj22o+Ly0wbsPAsumWvuOZwp8rB2O2IojmA6FanE53vU5DQtRos0JOrsfnHe8M9kHdxeB8bgedp3TEUAVxSAX9u7hBEVc0z1meSPVQZ9S/C4zIJyo973EDQKgzmTxHOJfAdMG+sjV0qkhIs28fJDWRxIvGYNYmQAF8211snacpY3hfxEsJ7Rc7+eWoCvyxkiXed2o5N0NneUyIH4KrGi8A8SsCuNXuvQFta3iF96ldQfSQtx3cxk52xPaLnR8bfGFxkA==
  template:
    metadata:
      name: psql-creds
      namespace: db
    type: kubernetes.io/basic-auth
