---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-creds
  namespace: db
spec:
  encryptedData:
    password: AgCkpfE8gJdhgLzzSHVL6W0cRS9HwpysMCkma8EPp+5ilMtZikkEa6hoCWJL7B0f739Y2d8kAG8EknsNfhPDZtMwNRrCar74VEjvBzGWH74SD7aKKbmNfRKyUNBI1UQE4kurl3o5NB5ulBFayi+NXYUZ7FMy6xVOw2FDMvmXr3eDpk4wD2shzPzp9+856d3bdpHkWNOYyhEV49XI6NgOSl5s86/ZpO6dst+6GZoGapupas9FfDDUTBioVlQ6SEUTyreZKKaUpZ/eXR78GdJj4cy2GRmMQ+JuupxSwC+RcRSud0FfyDLeX83heUy60B7OtfOFDNpq5SYU6Hhi3a9eV+SzJ8kemflkfOr2UxL5BsnMAWusiFA3KcJc0SL34dH0vEBHqeMOhywoWsNvCHNLH3pqbMNAIJXrwJ3rshRYx4OheUvVqz2mnH/hFVLpWK801D9QZyW+FuQPj1VfOQ0X1t9bZQwjyTwzj8B8RdpQKULbF8dbZ9a6lWD10MVhn+ydKfXRzI8V9swnkhNxFNbYudyzWuXoDEvWoDTdls4U82Ud9OWpZxxTnWCkIBoNVISMsQvcijkF8N0c/CXP1UEgkSsCIHVY7Vpai6bWb09/P5oWqoD+JpvSa2vN3feu56UFwAXJsVoXo15shCAlPvMg8Fh3OX9/rvAcb68WhdEbKNDPUrmric2WLCRUdFjqf2yNcu9pNIqqq+MNdYXC+bLhpUJDZ28=
    username: AgAVBcJxwlOnC3uauS5dYEsqCEy02c7S3qTg6SMnrn+aP2ygQtwSTx6czoNJa4U8NReXaTYjmx1e5ORs9206jEFlb+3C5fGBXFmgJsY9SwrGBAkrfMeuiN9d8YZllvEiHoUSg2RBBvjO5bWJqhVXsV0fqAND9tuxIDr9rc6zT8GUBXaSEZfBfBZV9F3chH6urRFTaHiZtbobLh1BPcgi4fUUsg8XDgsWDcv+hFuB8jh42CsG93nDtKuGlnYz892bb8QIOfc90rEXgJe/4IX+gfwVXqRzXht4BXM1Jo36ypeqxu683sXS8g7xD/hL8RFI/CHf3e1y9KfaOm30awK5Ijvas1GkX3crsjvjAUP5WafTlDVb5q8QmiFi+frSpPMf6MD77rDcd4YHWCYEXuoH7wZlji7Y1nJCwtVxuRizVAxfaNEI1EkNfWoSQEIQKq3TOKcBTiiyDG1+kG3+fE3S1uzyP6l+D81bg0eyOJ7NRHpbYSs09zBOw75AZHQfA7j/GIFt/cm+T2cxUINcE47vqpfpABAbObwtPudSAfuuD7d7uqyrreezDNPT4F0YTPHQgJtoqVgMXP0Pw6THvaeqOJP6Nu+z1gWI2nyFsznOgI1e7oMEfdv3SfSSRHTGTQ9vvAjU1HQ2Ytc4s/FWAW7NVJakg29WWAt6uQCGDVAo+ZY5tkI3gOj079VkyaS0JZa8qqs9eehMY17gXQ==
  template:
    metadata:
      name: psql-creds
      namespace: db
    type: kubernetes.io/basic-auth
