apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: external-secret-store
spec:
  provider:
    kubernetes:
      server:
        auth:
          serviceAccount:
            name: external-secret
            namespace: platform
      remoteNamespace: platform
