apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: external-secret-store
spec:
  provider:
    kubernetes:
      auth:
        serviceAccount:
          name: default
          namespace: default
      server:
        url: https://kubernetes.default.svc
      remoteNamespace: platform
