---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: platform
spec:
  encryptedData:
    password: AgCVxpG/z8FR4IFeF84hU5BBgQYmdg8nJn7vC5CNk2vUSCCxCmV+0nxekZeqF/rBsEpOHb622dNerzbxynZGXArbHmPnQIZmNsCOOV5v77GPmHrch1UEbYPDsItlQEuwi2D7qAqfb2iSkhiVUygtRCfJJFdvb11IwWrFW9EVxFVjGqw+MuHzMr00UL1k44yZUz9uOijSS7onN0A6miDdnwt7t8MsL3MXhVfyziZdSGjmNm2oQ7Ov0ZeJPZsU1Qh19l74Ibw4DJuIGQCo2OWRHk0ldxx+zHangkRd21r4o855SoG5jNgyegzIz/ilY1XwnlFJbeG3kb8dwvr8VRjppCOVfwFM6S6yjEkZg9EMoriaeRZyo4WIeg9fDnPX0/dCEkhF1izoFqAdmKRocYyqs0BHQDYKY+yzUwjPNEmtvC+3TlAurryQ3vy5TGAkp7mjalEiSYlm+/NfJviT7+zu5vexm+3OomT+J7PrlDHJcY6iXNiU+B9IbINiWut4cDqKGPbOSAvYRWPOWCUC6MvRi+lHj5d87ltAeXgiWxHLAcZWRTGs0IHEYaoB6R/C5jBGxO2CW8TWxyx+l/9j5dT6vvwK6GdPU/uxhGu+X00vLh1KxwstSc7RIWjpdO4DNLM+nM5XxyoST1MKmuYGUqaWCENIvEsX3mwIchJFsn9rYtXUyvTcfZNFG2KZCpc3W1Rfj5vUQYfxb65P8Q==
    username: AgCVnH+yLx0PFnn0plSWByCCO3xPSmwL4hfn+6uuOBiu4/97xFXhHd31lKo77Z7HVLQU4zShQ8ko/atygvL5qBcXSoJ08Uw9SjxGZGq7rc6GrcP4ZQ2WF6/WTORXigBmJOhxDj2A+ngV8+ou1UmiaqL2XETWh2I41Jyorg1QZQpOr0li1fou3INwx3uH8DpqY4KgZV1XuIl/Wuz4cSmKDxCQ5udL6ZHbj90XV2fyvwPJVXyb+nHd/ONrZunKAymgFyyh1U3ZDfd62/D1FW69Lf0PQImDU4tLzKETUvGogDJJp0Cq7FeCAmensbZTied1MTXyliZxQcfJhl/fbCtUQ9SUEQ0SUXAcYhmj7/qg0Yj1IBPzmVO68qIHP6TADUrizSEHXZFEAbZT2m4kJD8hzIFhqJ6bVNiJzNNQTaPosQs9wkUuMEg8gNTQfVs7HHPZOBN7Se+sL/hq9OB4i31hE4cFpY0TLzcO9sOxQbbYLA9MRLGdHRgj4lnmnQKPgUWw0hDFDWYN+uE7B0EUGcQsDHBAZz7kc5UXRiUe36O11AvMWP3MidHe1/duFPOA6jumQscldxEoeGv19hByakwkx4cDFSbojZI8bpJbnIVUputXQk5dkN/O5ZMIs4yLA3mnAdfM0km9itobePm8BLqDDVxehr3jYpDREWNr/UD8//K3vY1ntpP4QXWbZa37oU/XH7RJyqIcGA==
  template:
    metadata:
      name: minio-creds
      namespace: platform
    type: kubernetes.io/basic-auth
