---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: platform
spec:
  encryptedData:
    password: AgAAhiObx6Y/bChSe8MXSsSWPgE6we1T4/0XDCROdtQgXr8laK400qNqRsOoOQMeiAT+zGoxwvW91yNwdIt9RkjR5+WQne1M3MJJPmoPd8WFdvK1dP6k8XXpsupdok/Vk8OI4CgcVv73KJrj/D65TfcXTfdM8UDbVh8OY9rMvI5p/Q8xrrSzz/4GElNMzYPQYjj9ChmG2kgj9Dx2RK7OxXtbAPMma/rJ3O/3EgCUEUvd6kQBEPl0iASs69lO0Y9HxQQ610wNEiMh3DcLsVL/3Vd8lAXB2l8MZZLewi0FnFdG9HXpHpcP63cJSWpY5tuQGyISQsQvXhTCeujBiBrWmCjsWM7h5LI1WV95Zr5FjFZZlAuuxCaUNUjbJGFD9mSfuPaw26DdtZk49HK/E6MBrhP/NT2AwkJFQjvJseei0N+odAvO95pP7sRFhASsW6l2ZCwwHaE8135ifInFaTwudX52V/G3L7ETHqjGsew+K6t6yXAAZqBREFRQyTSJXJYKWW4KQaFcapv8vItQEXi1MH51Z5/GMF/YMA3qBbp+wWNvP17Qw+BKcNW/KQNk6XvD/duQpxrbfA1Hmi45m27h7NCf/HApGa3RwXBXKO84srZbmQ0puV26trFfQtAeQMPV1BEPhBNSxa319EpmJoy6YmPjAbaeFaylhWNAkyI40e4gwgT8htJSjBMt5WyIJtQQz2Y/zJee7/w7Vg==
    username: AgCU1P6WVlrYmuNJcdfd6OxonJoTWw1T1Tux8ap7W6X3Ilw+AKWriO/rklgcQAIY29QbfVNvF2azZGakbVZ5iHCVGQ7o5lm/lYsOa83luanSJ7QC6CD5cLjKIyWGdIUh+XKnHxV2MJFz/ZiQBXD617SaHiK943Cs4PLqWf0fBNcw7XovUZc0ip7onpuRSElyhas8l0RZigez5pAyuopl1aiGxrdfwfBWhc59DZ8donBUi34PUsUFvMyXh9ttrO4ldKbEKa2phljRw2CFvLUXPiY+lhbB5na2cPKnutjriT1j7hqaPh0utwuxwlZRj6HvTHNM5uNjQaAkjTLOY3FD7Chy1RhC4UIO64ag0EmF4CQzzQqf64Nv8KDGTRgfHbdKpRd4sqjIMA0VmmTjIqr5WEnpJLGE0TYzmGnxzlI4L1Q+nmAJnVMLu1OM25LqhHgiRgcwvKTBAms8MJmVKw+GLh8ogaYq9bpWGrm0LEkvp3cVnF/NPxXeImOgC0G9LEwZZfU9rQxNxxDAYkn4RqdqKGDHtAjSjm27eoI1fYHTiqj2xKYCWDT5c4P/pASlaoeWSvW52gQ0n1dHQsG6ZA1Y5uNdjRgUrsJRALI12slxJjH9iVmUvYFqRFPmnMN4TrX5E55Zq2k4gUxh+bAOMXIRPNo0oMGmVmMK1qKT7D/I38zCdCG2VtJmKD+wyLdejFWe7jgJ7eTdcw==
  template:
    metadata:
      name: minio-creds
      namespace: platform
    type: kubernetes.io/basic-auth
