---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: platform
spec:
  encryptedData:
    password: AgBcOacIgF3CeOaCVOYjJZXukX6KrAwKlt1k9N/RmLn1KGQbc93495nsPKndrFo7Um7ACQKLY3cykxK/ecYZomzGofwBzW2dgZDKerI0M4MCTIntK+5dd1nnrc0r7k6JxhoPZSM15nvG6XJ9uk60wxwaayvqfIWntbdX87SckvdK/vI1VjBkOfp9kjjZ4RtCdNGBztHBrRZch5Nj9s+Y+Dmux8ViriD+gvHwCxkjdjFNSlR+BwtUdF5WQC/LIFCtHHz3P+t9a84XoNDNVcx5asoMLQmVKxgyl9tu/yWYhtFznFH6gRhf1bmPQxbGSRlQzq3Mx7uz/6NsKHEsGNENKTjkeKMdMLZtV73UbHWUT0dIk2j0xt8Sd0irojiGCUrH5Hp7fYj5edtDwILtraq8XqZGlV3LKE2BucOw8v0AweRPXq+RwBqBjsrA5qaQ2LfAB+yVsXQydcAmVDxusPFUloVY2hiVnwaUeb5DmqbCyL9AW4q4ZKxnVN64PZ2s/GU5LFssniylPOpuda4cqJra/0kT+a1p8hTGTyPgTExSTSJJmPTRpP88V0WOsV6mMNpGkVxgHyyChSKCOqW6LNzdlYDvgdj7HSu7wBsSZhJrsaYb0XOVojLcItv1QTFTc+mAl4C0Jr/nqxa3PIuHsuoPccXD8oNqPMjlL0W9qkcqK0PYSX5SvoXchXa6tRfzEdeH/4eEs/HdJRfncA==
    username: AgBlI6BiHAnxuPwt6ReqvwFX3ho5HtXFjYvuVs/sL/ILXQ/YYKC+YZty9i3J4CQ3cIeQnJLLKc3/hjgUKXhYKgkKX5EwGo9JGabJeLPmqFroIc88vSGHyeurJrGZezO/05Z025pWNtu33f8sGlHo3jTnE0HClgTZ0dC0kxfjElvubCRC1kY7+6dpj+UQbxMpgFlctbvaZ7DAQZJ4SvYBqAoLGKONGoXEsaKrIXBidHnevMY6ORIbCJ5kRlcjUf5mOjg0SGtOdavq3UsrkW59xFaslKgOIitgJWSaOsGzgmSJ/HeGl/ZVtUP87eQE0BsjYnqt+lRdIVWiDU3PNU7+l5lKUXMRE/bfU7CNWuw+EuhKPAok5OjQq9Bcfqg6DkZTi2vFUnvpf6Sui5/28USbq/bZ7T/qe0PNVrY51W2yRSncY1wGpuAuNadweQylR3Ze43+2Y5WgEXP/b8Y3b8B9V2h/vQTVE1XVVF249xq7lsan363OmVsfW8zwRu7wC9cXLo8LOJEgjYaWd39BrEuFEssXWujUN4g+XM2o5QKi5Jh92CJQdxQDUuwJpKS1cGM6vZIozLcG7tFtbYHAeUaOYpkQ459+s+Wp1THDCs3AI9EGsNPjfGg4wupPUCw+ptdI+O+U1V9bHcIz6/3UnkWuWOQWRUvmKbV2EDw43XraHeH2tfNtGTuxYy4DWzyIPkA4Dcc/Y/V9dw==
  template:
    metadata:
      name: minio-creds
      namespace: platform
    type: kubernetes.io/basic-auth
