---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  values:
    persistence:
      data:
        existingClaim: minio-pvc
        globalMounts:
          - path: /data
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          cert-manager.io/cluster-issuer: letsencrypt-dns
        hosts:
          - host: minio.home.voldemota.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: minio-tls
            hosts:
              - minio.home.voldemota.xyz
