---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  values:
    persistence:
      data:
        existingClaim: minio-pvc
        globalMounts:
          - path: /data
