---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: flux-system
spec:
  values:
    controllers:
      minio:
        containers:
          main:
            env:
              MINIO_SERVER_URL: https://minio.home.voldemota.xyz
              MINIO_BROWSER_REDIRECT_URL: https://minio-ui.home.voldemota.xyz
    persistence:
      data:
        existingClaim: minio-pvc
        globalMounts:
          - path: /data
    ingress:
      main:
        enabled: true
        className: nginx
        annotations:
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: &host minio-ui.home.voldemota.xyz
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: home-tls
            hosts:
              - *host
