apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: your-app-namespace
spec:
  interval: 30m

  chart:
    spec:
      sourceRef:
        kind: OCIRepository
        name: valkey-bitnami-repo
        namespace: flux-system

  values:
    auth:
      enabled: true
      password:
        existingSecret:
          name: valkey-secrets
          key: VALKEY_PASSWORD
