---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name docmost-app-secret
  namespace: docmost
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: "/databases/docmost/APP_SECRET"
