---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/self-management/docmost/
  - app-secret.yaml
  - database.yaml
  - external-creds.yaml
  - ns.yaml
  - pvc.yaml

patches:
  - path: patch.yaml
