---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docmost-pvc
  namespace: docmost
spec:
  storageClassName: ""
  volumeName: docmost-nfs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
