---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
      version: "2.17.7"
  interval: 1h0m0s
  releaseName: sealed-secrets-controller
  targetNamespace: sealed-secrets
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
  values:
    fullnameOverride: sealed-secrets-controller
    rbac:
      create: true
    serviceAccount:
      create: true
      name: sealed-secrets-controller
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "150m"
