---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      version: "1.10.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo

  targetNamespace: longhorn-system
  install:
    createNamespace: true

  values:
    persistence:
      defaultClassReplicaCount: 1 # TODO: change with multiple nodes

    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.home.voldemota.xyz
