---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: platform
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: "1.10.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system

  targetNamespace: longhorn-system
  install:
    createNamespace: true

  values:
    persistence:
      defaultClassReplicaCount: 1 # TODO: change with multiple nodes

    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.home.voldemota.xyz
