---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: "4.13.3"
  install:
    createNamespace: true
  interval: 1h0m0s
  storageNamespace: longhorn-system
  targetNamespace: ingress-nginx
