---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-credentials
  namespace: external-secrets
spec:
  encryptedData:
    client-id: AgALJS9T5emiRUnqNW51nmAYAUSxk1jpZQudPs2skschPsfFpTg4iPZktYXscNWz/+gLfYhdW7T9kP/e5rYFvxXDhey64v+36+TEXbVbEL/bMXGrakYrHruNv9+YJarox6cEurHzf7TXF1SkcIY1lEISj8cijVwHcNaYRC0T2Le7nqm/LiLeg/zoOYzKlinzv2e8gRpFepU3zU53zhqhPlTcHTxM25SYGdZZVarAlpUtAjZOlcg0bTfT9fBU7+pBlUiwRrrzJIivmkwphYHkI4krr9/D8MsUKUoLcJndhOyDDQfiKYrJHcs/CdCE7lRPLf0whvXa7DgXcwV2JtgtAbkGOBCpU5t8LITIFaWecW6H4Eev8Q1B2mP+TBQCW9vJ8nlqwC67fFAdKCOsDCTcQJkxoaWmXb4uTYCtb+ekN92oxjyuVjXd4TAHsQ5josUJUmQ5Tf/uD9BoRXVxKDWMpWSicVBB1Q7Gmns+bKiWzt+C1cBe9OecbGlAUpC1b8ZDYYFAXCFaj6Ouzfp4vvNPDVsxB0POaB1vojNEvOPJC5slXitqvXULxy/5Pd52xKBAAJh2/VWVIXiOpogcxZ5RNDulIpxvHcEzK/jn2M4CU/yH5+KYYW31OyTOfq1tv0539VaVmXgZgci/Yo831k/L8H2rMb3FWWLvogJ9xWizMivunjShP3G2AnqReyXj8vSor9LaHW/RGvkZrS5zEyBF1PPG6U38aVfxocDHBKC/uz+rcVyeDJs=
    client-secret: AgCjZgOAHm70TrZac81rihwu2meYK0ewfm4VCtqubZhndDAhPID23prmG9Gl0I6tR73BKbNs9nzx0uMmUSwBfwzoCJe72c8aaCWCmzDSRY/oaukd0g24d3dXvrWQGA/Y0FHPOdy9U6IfWrh8jBhUZnd3vFL0+Cgn0lUejUbYR5A3HdrBSuZwa/36Y2GpumAv2uChL7U24OuCIuZ7cSduT7x/dqBVDMBPCY9wKVC+HCTJVQV3oXZbNLFjGnGNfbFJBGZWE1oJ+FsHioMJPd6MRRqgQWqLj3oj9CT/C1di3B3lmcYKgdtn/VaYpSJyd7xDWxPfhppi61PIfHQDLMKm2JVdTKd2hX9pE9jh6rve18fr3V2MRU4gUboSOc7ITAjsz5KoZiJ+fBBqxx28j6N2xh3Ed4V/r6zQ1UIErGMKpjX5L2LeOYys5dtp1F4V6ivfSRfA+v66xFko+9te7vCUJ4n281+0wUwTJecbbLUOKXFcxpf+Nk2zoPPlOi56ywlmkci0AOvk44A55ezlQlOlpz/uG9lP8UZ5bi/tc0Nl8z5L6uoyAhDwVa5F9RpUH9BHXSRAu7E15knoM6HwIy9LyModk8ZEo3QkzVraBti8A56SIgiraHQb5dvX379sWbTgl1IQV8MATmF2znxvwx7On86rWkq7el1oC2vgYdjH6eYShyeyR71M6RXwoKd6Y2b9x/fXRPzAS8mgx47Rw6AP6qY3RWiSUKTZSRz3cltFG3xHaJtIFjNttwH9IizsFZzOQibVNfn2whpn9R3WW57AW9Ol
  template:
    metadata:
      name: infisical-credentials
      namespace: external-secrets
    type: Opaque
