---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-credentials
  namespace: secrets
spec:
  encryptedData:
    client-id: AgBulJDjsEcHe3OQStQMXGesfQhQ6sYz5yapX87VrCHTUlMaWTgz5KG4piufQ/xCTsvWRhQBqBTWvLcbEsYLJIf34Jr2DaUTmp4i8GrRJ/O2+5HqGeV4xXEDT+bO2zy1QNREli+vHVRcKGbXIlSpT/fRi1oah2yaInRwk9Pl7WzY5+aISMABiuhe0AdG5VOFWbMP81w0HEpkgiB959rE9P3r5IDgxlF7v0IRMD39GMucSGyae64tLuNgp/vV86oESxAvVzd7HOI3rh/eELGQpN2do6XFkAGBQrUvoE8ZfM+4+klaocLvJozlaZtplOYLzjaB6t5uf+pzFWkQN1iTJLH8o06I+TOpd8pEnAZjTnyK0WfVOcDRYtPas2YvL/6KpcftnCDdSKXdKjBWoE6/h3+XJIDp7Paxg4ig263XGPEpoWEA2j5yP100IMId5XRd8d7xZXuiandKy85eSlSgLa/5mzrEP51rAr3Wlv5ef2g66EIOnN/68EuOvThNP4+VmoJAMsIcTHlcVXqW120oMEaMyI7zE843ZYgvd0hbkAFfa2SGYZRaOKaNO96RInqbtuoNBxdueRgnP1q4Pmp96fdOoigYlWRrYvPhcM1+gkiIMFb5xWlOpNa6xkSR1kILLRTOJWE4vWzFwuzoLQyNEJcZJg9zTinhlqsK2houGJk+vUZWTiJqM4FuJR+SjCqtp7MEP1Vmgv4gOv+zqbkRNNG+5rYimxeWH0IwaZEoRkvyxCZok2k=
    client-secret: AgCZf9+e8V3jZh+GbAqabgEEOL3Mw4RwcmGUi6AjR1ccXUrYq53H00OCyQfFvOlcdO3du3V3TWo49SJ1anL5fylqGax5dvqVKpOMBsJh51FDkdx/OTiR/ycjkf0OFYD+KmwT1xSj8LbLdKS5GsZTmpmlI3jnjiUcyJOuxNGseKnpOINWP8ziHiVB6x6jwMcs8A2DsPDKEq1/v7l7ErwR1nJRNtmU7MCM4NeOl0LCvlLl2Ty27S4yhPq5oFPw1zQ4uQy0N2KfiHPAllemKoq37+4tqh+1AlcnKh2P0CL42Fyk//dE5lxqF52EWdobPqDWRh4NvK0K1wJSUdokY0BqTYKgQuteXGpXXjFNXqVGVFTlWf1vJ27qCaPWxziF+R6Lgtcq7ZelxBTsxvHIR9iOhn+MqOCm7IvCqXcSl7jD3EU3S6zY9q96JKFatpwVVg+ExDBxmPbyG3hfrIDf0062YW38L6CZxfSkB6P6sUYO1ikUdYWUrZab7W+5yG3Iyw+1fT8APlyAvjMwJLIbkXkM+LpLkFCKffvWFoj/RgxO//fhAAy9o4LHOzvxlmDH2BjwQWVeWt9Z0VeSocno+9Ll8r8ZA1gXukb/sjr6cpxCEfP7AQuDALi8WVRqMg9OyY+JwozGod8tBxhKtIpz+JNbEIrKQls5oOgakduPFv4UN7Bmyp8f/Fgu1nDZnLQaT+xt6HnAc76b2PoVLXJiZvlGKguO2nnhS++F3kERcUu+u3QkuodnqX50ITyT2YLlYZJY4aK+xZo+KaQ+tG+3PFVG17df
  template:
    metadata:
      name: infisical-credentials
      namespace: secrets
    type: Opaque
