---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-credentials
  namespace: external-secrets
spec:
  encryptedData:
    client-id: AgBZGNDz67W7j4lryuesMouMKYEIUcpeVjs0eNfGElbYpMhEu9AKLykb75RqsagFCdlbZF4f0ZR+2xoNhrBtvzb62No3DdMtMAQuYeHFURqdekvO8jILY8aeg+r+Qv7gETDQP9hvVxXhNB861oMSm30D3T4XyG1hS6EIRtEiY+SQ8akbKbjrcEqAp6sbiIMYziNzBb4LVWSLpv3OXASaAW8sdoSstdm0jcaeLbojtrNeP/43b3iOEMGfEMXkCkoOps/gvJCiQNAljHT2iGaUq/k61thC4dW5X4qm4cJje7syGX+3DJsUgiE0gHLNSVMcow1vqYpakQDp1J8G4ZUlkVd70ocaOrd1FzgyJNZZoodeyh2QhN/UQbAxD+aH/kMNTem8fI7lrze7/o1QOjowj8HqfdASPnWa4Rz31FjxDvo2L2O1+7cDG8yoJxFzwaEymBRP/zWqXgIHyAR72wYd498zWbs5UBXDTzytZf6x6MDkSE3aaNjIMOCXBrE/i2dw16NY3nikamd4dLvTfpniQHclsF5Zb0q7UStztGippY6VCtMpzvKRTLKE88pEDC9kAYIr3eeXFtMt+sgq2SYZNZxjdYididlJFSlUr5VYHtA55amPoeCCm+OZZsz88jsJH14ey+wZ/OSJEvJM+hNFXMyQzj4D/VuKVNwwcVOVzylLEzUuJVUzwViD24mnefNObJiuTyD7qvRAopmRMTwnu9muJTr0tZFvuo28zd4ZkQoXrBx2Wa8=
    client-secret: AgAfykSvdT+K68ONShS5x1HUNchyPbR/IS4+zbn45WQoS2HzgVmvsEa6J0l90m7a3lr+yNPp4syGn/Fjey+LoVzr1gmpVtN597yjQZhwC4Oy3W73SWmAJ2emoRxhA8yGBNDypQUal0J3Z74PsO2MuAAtixt9KgSt4PVIzH6sohyZvvoC/YkX7u0d8xeWMVLOUzqy2smeyy9wUWiaeB/BLTCFRwLpaZDAI3LueRmeeqb+hydCuQS5lx7zVzh5ieZz58MIPGglCX2lIrLygIQgyp3x/FbT+aXvrZFDc753kaiWw6fkCowdMcXih3i6LPBJOMJlMwL/9Wm46Ki0sHNrAMglgo0JmEfRj5jTILLYuAbz7R76Hs+clkIfBFAsqpbScq2VcAJ0DrqIY8hdcZs9RZOd1BhWyQ9qoEqvvGAc4UKIdQkCxvWfIkQ+rmnb2NbVOOJIrLhVNEdoI774HfGaM1AWu+o+/6Y8tZXq4cPXcf1qQ1/8cmaG3mSl1tZKu6Kg8FyN5xBaqIehFYXxsTwM11NcLMqyRnxJ4XJUf3yT+Y2vjAUgaTjIfuIxHStR0xDcJCMbcYyDEOXfWSH5iS8lVKjizqtF9nNSTFpPuGdMwgzp8hdIYWmnvLF5VlXsP+hoIt0DE2cZuRlD3DZMvTRomSfvKmLJ+BeAP0goywmGnBNdszpDqcrcTvN8krOhrCPatnjlqCFeu+Fwe88ZIee+udgeAKodmcpJHdC3+KYr0JuRvOYKkTmLffJk6wz8EBgIsr5CdrlASXLYDaDHpp1q3o9u
  template:
    metadata:
      name: infisical-credentials
      namespace: external-secrets
    type: Opaque
