---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: platform
spec:
  encryptedData:
    password: AgCVczcXs4rR9sDZBogDOKw44BuHTyx9XAXMCc0t6TEFGIRxxmPZlkKA50vskP5fDPuLjvpDpmTTdsU3S/fRVxmZr81AKOQOtSGQIVNxLqybAUxyv8QL3/W2hCojs3d8fYiC1rTQufwJ00ssFZBCQAD+wHGr+4e6zC0q3o+qEw28sK6rbgTF6YSxNpAt9xSwzP30ML8pOZpvx94reaubBn44DzRz0XzrO4//DYpevHohvtyxgMDGNyYlk8de2xLGQtiOUHC7WQ/6PJSDBVoIMQ0Q8y9dSV1PROtC2INTXR6Bowp0vjInJIPZiVPdhy4nWstKdjTOaRUz9sW4dRfviYOQpXdHkUSMTVvZMDruV+7X6gbqsQEcqsiXiAKLecdGuS6R9XUnd4zIMrmDlGgdGi1Zqy56pckHOTkCj4dXkT05MAOYiofbtuifYG/SdR11AdqYGM1p8/bQlGAeQbFlCNfH3Gxgbnt20yJlv9qmm/zKidc5chGD3i4WTSlyFH7jIWAhHI19HABPqZwO492xGaMEG9I7dsTuHU/FpixLGESNsaEH5S9FOZg/NWw+5m33jBvchKAK7Rx5WI1Z4go4HrfWd9oY5ZbPDI2jPmHKOCw4QDhIFYQde/ppaAHStj34GdKMPGzxufhQ4wIqZvoAbQxX8hrChHbie1lYBMgThY6042f2U++C82ru1gMC/ZMpswzSNV4vzJK/yw==
    username: AgDA2of0FVZMmm7U2xyf1JscXKJl2rCj8JfL36djfiEGmaY09o5bixnrnTB40ZAezDbsn0IhSWBenHkgbRVIq3GlXQEv4Marp0nBZgB98IKsINb2xkK41MMd3ylrZukEsk2UNPPNZWjSw+7JSzAtzRePxjmHC9qLJ4UyDz1JMjByRniXPqLaT0LBRbOwQGnlWkztXl2Khpoq6ZO8XBo1Iigu4VEQ3jvfRRlyRA7RAgQ12ASUBDZSItaG+UKeA0tyBmmukRdqvezT38fAOsotL7BaQhLJBOLtDum1WN4c6RTFwLSigobOR5ccbOn8z3OYOcUNMUgIqwcOowDJ7xgB3pBZapHxbxDt9LgB+i5PhcNyxNcbn+Edu/ciejE3/7YdNjjqSv3gdDD2jgdJGjqscKWEiaC0BrfbbirDCFKxi/RHecUeELuLWAyBbFWBna3dm0ON6DYe7i/F148uP0eZ8f5/OTPltD8GPnPc/UYByn6LEXYyGrg1eldb6oretxOcMBBV/f67qtTNm/6SOSM+vagIlB6LoHjw1v/0RbwOZzMf4SNygeEmWGlvRMEfAeA+N9N2eItsmJ0gD9vcD7SQdiSsUTVuzTaZAHv6CP9EYVqdyvsioH7biphmKsPXClXmvLg3gKgGVin3VwAkpTma9Y3x8DNflyR7EMBvHp54LBSYbKeBOGHValJ2IAdkaacQroDICFWVNQ==
  template:
    metadata:
      name: minio-creds
      namespace: platform
    type: kubernetes.io/basic-auth
