---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgCfRxTxZlu85S94TnHGKv/3I+4KTZhueFPPsmtqzKRmiaMsm2Vyc8URPRH+87T3H1G+aSDoQA36hXsRalzn6TOhSVp02cTMt9H3zCHQJ7BtZb6ccUjQpqFSWKnUB24/spMhNAT21nciSpvvgPu2fivdX7rqlfTdJnoy7+ZY2/yEKWEbDIjlAQcx7UefEWRmZlGLCraUz37KhzslNBSh63byMZuZOv4vVoo6qbL0cXQHfz95RuZ02dPzNG2jH54c1CmPyhmO7UQGHedI1TVgWHWjgdGzgsNUzBg9hIZKQxRLLRms6kP9blZ39OVJR7nUyilFvXze/61JzQwp208L6iEMj4SGLh99fdm67TuaZ7jWS7C8YwFRqAWy+UDOpMOzclqnPUUxpSn8ydqh8nXQZpQqvDvqX5YjB+Go6fqBWB+zv8eFwIAkLEVyt0Np5O7vlAKe/3qxjztgh5rWJjvrQCxfNIeUpi92QuWLiagOlN0lXBQriTldt1VCFWpxo8ppktcu1ARQQ8aHp9HsLWczTbOkd93S7oIzB5Au+iGGai27N6EoH3DmUtkTNquYj86taXtXGcG+044kBFJkqZoeinT96KyAsJ4UCnwAj0MKremmjfBDC5/f18hLtH/JU+CU5VRNThZUYdxB634zWk5WRCjcdYkkfD6fPvRpajfdz6K3J9E8iu8XmMQa0KE2//jebtawxXGFnju0Fg==
    username: AgCJIEU7H82Arj+5xEHgLwLV3VCaL28hD9b4pnF1YNOCEQYQq2tQosVYPT59BqzhVz/qbuyt1/s81iLtGB6w78RSM5Fl91OdCJj1WqsWFTuE6JZSSDt2d4MrDTjrGkAEWZJrKtcN96J4Fg7z1RWT0gfZqMhaaBskgW+dYWD43UpUv5/iVh4J/Hf5tBZnqj3UPFlsZ04mbkk8HjppScJf2xeCyYByeAu5TWfjhyMWLljK3DhWzIm7X8tihUW0/ne052U6c/pao2tq+ny8QfIj5/NnEngyP/wlp8fUbQfd3RI6WEADC/VqLslduzj+dH1z6TAPCNKBLU6aiVrvfl5YSJxn2sck2+gbW5y9iot9nCY4sdTW3rDPxAJU3FUHgRX29xKM8sKZYAnQz6R8XpDdqxx7KDhBb2CKbL6IvGCTMDn1+CnpLSb158dslVlEwsOGlv0aa5nBxXpRrI1d9q54C24M2SyYam3wRZV9XwWdB2odR2kJ9Hz/Yr6Irufn1WPeX5ETcifNhhkO6JONzY61dQhrLkVvauXfkxTb5aP1iwgDkhCJXCoW9yrI3ndbSNPWHBs83aDXe2Pird+/VCvAiFdqOQ+ftPvdJUORyeFysQVoz1MMDJ1wu/DhUTBtw8wyuA7d4s+EDX0OnT69NFltt0WRk+las3UiOfDAs4KavLOUo4s9vTarzHWX8jg/TMp1fhgKDI6rHA==
  template:
    metadata:
      name: minio-creds
      namespace: secrets
    type: kubernetes.io/basic-auth
