---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgAsTqJJzy46CSuVKc2OUNXNDTUCG8M4BgytJn9aTUmIO+zw9NvUjLk/ojBN1X4Z+BZ4UUdM3ys9dh9JJ8+HVND+wwTbh+/EBA1uJRPKuQ2OCGm3JSJXABHHVYcVLQDJt3j44kehfK6y0x+iJYlqYEhYN8SjNQfWMCCEEHHR9gWzmdCPP0/ZLQOFaLshBx1gUzGDtKf5JRxKsLQ2Lui0Z0FScs3bxJ96aWXB6CTLGhtiGyHBug0picsNsQmAzFMTC15p3/PdFa+nmiWeVGWW6x1M6NYRv5CzQlKH80s3ljcKCdfO6yBDzz4urSg7Lr1f9N/wVRMXKeJR1Wres5BKwVgYxhNYmwNTEzcTE4ixr4s9OajaK9rBjtzVEimhGBIhYU1PE7YTjDtwidZBVhmIgRuitmHYngNNWM+W6T9YCSbm45ZlNJCa4bPApvOBhOgdIcfXy+XAgUN9di8YkQ3Sn7lsZGi9lCuGUf0r5A350D4OmVI8dw9YoONF6lmstBaUDVavDVi+4NmaRrDKGu4Hw+KVgnX8itRAdIQu0++hIwh261gl3CVoKiByF9QPmVzOFxC6xg/UkfO9Kf0smMdbdRB3mGY6qf8RFss+KqmvtZHaZrYR7siLJgloiFvhLbEDvS/6qaLbqKy54OTAoplzsRFmHvZ3AXFxMEr3DeL9FA1ALzrbm8dB6OSVl7fv3AW4ld5thLLxDkswow==
    username: AgCkBcaqGYuAB7DE1i8c8h+hQwUTw9tsY0QgEq2pAldabsHCeu6TB2y6WEsfuwBKnuVw8H6vMYEbBXIavAwpMQd9MgeLlmd5cc/cO4fYtLOKqUn+tIS/QZiEVH9WVzV9u7SUyuiFZLR/MGVhGGkTLSBL6bB5uF35/ByoViOPCU+Z7bXy0wU0dLwbBxnl+UNHnzIFxSvUz+RWLMf61v4uI7KDvAbE0txmHYWH/5nCC6QpQS5gGbhXEr3xSRKxO5n5cl4x6FLgduz+qSpwnywvH+mHZgs5LYZX9MDWp5+OIzvXOnhzmoKNhqhjeEh/2210fS/yf/DEDBF3VtohhUhNe3siObkuJEgrEzUPLrfxS1Skb5hscY+UqtSBHo2Q/nhUEkVK7CExk5Euqbc/t5Ca6LX9SmzKw9rRTWo4IaleY5OXoRxAWdz+Z4lGAPJUj0Eg6g5EWm8fFm9if/i4gRnBfz0jQfYWjOJRFaR5U+x2NLaXxkH6iaSYTvM/oKggBe5Te4AXn+fQHjZ+xKOnWnRYEqNum26BIiu65wM6YzYOFngg42DI5P6hs4TU+thA+UnThja4UCpHzLEoyVcQDVkoiGfqsBfAsDKMoIQJSsLvUkL+v05wL+YAYFDLtyMgRa1WMUimDEhBp53y8kuxMu1gG0Npu2Mepbk9MA7q4TxDUDV2LPVGvQp1XRdSvOQV/ZLqruFDseZBfg==
  template:
    metadata:
      name: minio-creds
      namespace: secrets
    type: kubernetes.io/basic-auth
