---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudflared-token
  namespace: cloudflared
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical-cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: *name
  data:
    - secretKey: token
      remoteRef:
        key: CLOUDFLARE_TUNNEL
