---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: db
spec:
  cluster:
    name: psql-cluster
  name: immich
  owner: immich
  extensions:
    - ensure: present
      name: vector
