---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name immich-db-creds
  namespace: immich
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: databases-secret-store
    kind: ClusterSecretStore

  target:
    name: *name
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: *name
        property: password
