---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: photos
spec:
  storageClassName: ""
  volumeName: immich-nfs-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
