---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
spec:
  storageClassName: ""
  volumeName: immich-nfs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
