---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 5m0s
  values:
    immich:
      persistence:
        library:
          existingClaim: immich-library-pvc
      configuration:
        trash:
          enabled: true
          days: 30
    server:
      main:
        ingress:
          enabled: false
    machine-learning:
      persistence:
        cache:
          enabled: true
          size: 10Gi
          type: persistentVolumeClaim
          accessMode: ReadWriteMany
          storageClass: longhorn
