apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: your-app-namespace
spec:
  interval: 30m

  chart:
    spec:
      sourceRef:
        kind: OCIRepository
        name: valkey-bitnami-repo
        namespace: flux-system

  values:
    architecture: standalone

    auth:
      enabled: true
      password: changeme # change in overlay

    primary:
      persistence:
        enabled: false

    metrics:
      enabled: false
