---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: musmgr
spec:
  encryptedData:
    .dockerconfigjson: AgBzsgUq5LSH2Lz2iorKZzhuh9tzhNnStRBsqZs7wd6U7+o4sXX+yANc/UKC2F2Qm0hS23uvTkl/M7g9ePTOtUMnEF1EVTIEmaNX1fUC7cd+smO/S3/oiMPlZ1IaThqHO2Ma95cJveP2B6AQcQJguToAf5Uno/cB6zV/KOJsobYEFin8LK0+tr4xwoQq+04+lu+wfbQ++smFF9zOssEjGOOVW9SFSP/7pZvYFJVXe5bgYGnES9MPO3VODi65rMjTT8wweNKGWNX9zWYKrk6vyhowvym51MDt+IyuWIQELCEE8DEfPWYKfkFOigRUAOHhAUJWzs8SeFehc7W/+keICGzsn6tMsttnnGzHTeyJYSwsgypxnYAXIy0KFfC2Ow2JjIbqMvz85Oe+ofK1piZ/o0VmY3ZcY1DD+LyywLIcICODXqliLe7REseaQy8DWzLdatxaMa943NzEeqEa/QOaonJA5xtpkNk2Gp5VkmjYtAyS8IW8QS48UPdLH2TeH2YWwKsafpHeSpdpk/azcy85SiTo3r8HKTI+hFF92Nuf53sxjitDhR9fb9EO21O484oq/iE5+HFlNHcNAQ4jGQfLo9z2CD7ZDHB96vKVotCcZ9rRfJWSNh5M8vtA4mtgD5Gr1NuKs0e5VZXVsZDItWQWz6TdNkSrU7yQyNOUf7XNVb80QXQxZEWwAz5qF3J3QOLonYHTCkq/bBL6jZq4faGdWb/p27WYdoHC8y8UtvKFpkaGh6Wejk42gnVawN5kmO0yl3XfZrE3VrhVhA3Tzd3yUeuFCvllfpsap+cRqGwskfvdP0HlaKr+ostATT0SQ7VkuI+I+icdz+K3Ze3Km5OLhdIbtHKe0lNPCWR7067hlCz3bNQqjyfC9Hxu2JhDi4g4LY+AVsfXZFhQRPCZ3anhaKgTyjxTBsvb7Zk4XJsFzX8X5CC67rgqsiCTH6aopITd0TJ5ALrJ9KHC2Q==
  template:
    metadata:
      name: ghcr-creds
      namespace: musmgr
    type: kubernetes.io/dockerconfigjson
