---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: musmgr
spec:
  encryptedData:
    .dockerconfigjson: AgAsqI5A9LUeMDD/Rr7k5Htgkg+JBcSCqajdj2bC0OwbgqJn4EeCS20YGrZW+Wy+2Zx/lmwSgndItv4syivi7B29xv3hmbHY4CT8RQuMzjX5XG9BqIXrGS41JERNJALScRkVK8HR5JfWyENhN3E62OZFDRqdcop4jnSjuGMuqOFTiLLV23hX/xNQpDxxRJYcnBLy0bD8uQCmo4Wt1jMboN+WONc0+1mxbEHlP6Fnx3eoIOkEWwUfMxW+vp66c323vQEIvuPCspINRMPehYWXg4Ili/E93H/UR41oR3bYy87o9UrNCHGe8vz9KSvi8XnyPPw/PxjWtb406vjxgUt0uO6eh2E+Y3yuxl7rUxxcOVdwKfHxbNaDyvC+aSuKpxNwrNbH2kMouQLwymHNkeC/gTGeETyJZ0ITGhO7tpB5/yVVAB2ZnnYBBTn+Ebc5ZHkN8GPQMGQkXQxnEOFqvFIDW3XQuGLiR8dkVg/z87y4f81Ro0cETrs+scv3eieOiHixsBsrUWLRh3t9cot803QUYlPw45hPUGC8sLIc75SEwI9R8IsZ8o4TmRZ6FzJ1Yiv/soChlomTFbkt+SVs2lHkWN3uVjWrzWb3pABS0DgQhuRb8C2qBFQN59V+7uM89WSFo5BNRnirKdf+4nRvveMPiefoHdjg1a+UGfcpz1eiCMfLoM23o7F2Y3MDCJOWV+55k4JlxtBBeg25mFkX42YbJGpenyoiL1L/ldw+wXuC4Yor517HoIj0suDVE8YCEOVT9CgCmhy0BtuenXKNUpDu9Tp2vN2r49q4hRzEKildi7DrPgyZA+ao2AAeP9vFNDzeKflgp+5tC+4yMZNQmx2cJMThrNTioSBWjvAQxCS37Rw2Jgp25YjvmRUOcnkPDyZY+lE/D6QpufmFk0mkXykTqO0zkJINRiGrVCNzcs4UXhxlNIy4R87MtTBkZO3bnW0AK0ekfpeKiuU8MQ==
  template:
    metadata:
      name: ghcr-creds
      namespace: musmgr
    type: kubernetes.io/dockerconfigjson
