---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-creds
  namespace: musmgr
spec:
  encryptedData:
    .dockerconfigjson: AgCeL4cNL1Kr7EiXbTxC9hJc/jWnIStdvTkC2S+pCb98022qgtilUeof2Q111uPwG33Fuq8WvHkQTaSrC6YkJSpApJs+z18WylmFZdaGqh8ykM/vgrbO+RI8pFgOMAbaXLaaGs3AKY5uAKVz/iI1x9j+ht3lkwAtG1G7TUsxA/kfIC8pNz/36ucELD88J0+yL02TUCLcJmujBv0wmWhpLhvzVshVqi9Pg7gacKcyBImryra0thcNPWqLZrioQ/vo47MNam9e+4Z55tsq6zdYhMxMspNARqdOkaMNn1VGP5Vubkdqhl66bDxcuPz03n0sgFYm0REigzjLiyHWhGMmbCfOT25HVaS5ju+ARek7DzU6FctnbFJZY1cvwWuuP7d0VPRKPsmuXQylpoERibq0zPYI9yXWYphmPCdlZjlY0EGD4UQ/B3vYkHgX69Lr0d5IUkFHP+ICB0UCGqszs1TTHkhCEmFBULAusr6OoG5pbOSziHR0JJMCoBWBn2iMHqTlaVB4JXs2cZ/4DEvYArrkN6zETRuQW940QcH0OKfozxcsL3xbdzUZ3TYmRC7cZaQ4MNzkS6amaiRU4LC6nISjMKFEghcBuxineLytuDOFBU2KbhGxLY+YIiD8S4Ca5vP1xRPydSVU0q6QbkyPEnDRTJ17iyBceH0Qdg2D2wl17MdCYzaNac3zv2JQrfoqNhXRqrnzHW4+fUNI/gIdNJhYNe5GjJrbMfz35+4lYAmwK4BvfMNO9X9HLZh/pv7qCHZv6rpHEV+70Zs6Z0+8yphFYlhlY3qOdBjqiDxdUMbxCR/UWXo5+XFTi/yN+O6aQfNeqBROj7Yd7WlhlMfG8ZTX7aSPv73z67D0Iu+wH/RSkWABNHRImOTnYMMFLTnMwqkcKbW9B+sufqXk1fcLHwo6q6YpJkNXOk10KZ0w+cerAQoSicRZmvlT+GIr4zdCs3Ysh4uEXzqukzwnLw==
  template:
    metadata:
      name: ghcr-creds
      namespace: musmgr
    type: kubernetes.io/dockerconfigjson
