---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-musmgr-creds
  namespace: db
spec:
  encryptedData:
    password: AgA/+sVtbfStlElB08sZvD7CzXyjxTFdaWj6GjbVjZINr6OAuBN0t/yCu7rQs8B27snbkVjBYBWwqAuV+O+lP3E3Pu838Tq6PmhYmEfPacMi4IT3RLwdMetjX1JxUy4SyFUzsNbMvGmvl/Z9OdT3PrCwKALanrOzGl7Qm9cvAE2+qp17/UiQry9iCwL2UoTG9omUCzZ1lQ9ZPo8WS6sRF02V8JiF4PmUHN3YtFZDc2pNt8F7jbmpIji0u+BPaKkdbP6PHtslJhqXZRfiQiZcJ7H3qbCA2+6TvX16HjdNI2+EvwaRm2tKOHGFgRlLurpUMmFl0qxRU+XndIh4vG6GD3s1OgWw0AR4E/Cf/woChkAWC1FLe8z+dKX9H0VCQWMrAg8jwkEC4LZPYz0ao2BS9rfk1eaviZQR993BJUyVpnCJFMBxrU3tjtLkI8gZkwPVJs+yQom2uDoQLGULfz0iMjBgEEtqNMbmrQvlsQHysoZyNJBbYbAWvRHk2x23V3OarT/NPqv298wKtxd2Iyn8vmexDMK0pTOuen43FCeHZqmAIITqZsaY6THT8fG0v7UuJZ+wFGaZWSDa8XCtBtnTLJhP8AVEDUzKqwQHM3Gw2H6CPJ/8i8atG5OL9DEisn2O0pME1YCpdMBJJhUg1+u3BUs5v0f8W0AVLAGZmybAUmWZgbby9J+I8PC2NeBR+66wHCEjFs45f+8R48RNA68U03jOPIRWiE+3bkU=
    username: AgAvhBqlESR2bjXGGrBtEUfovjr6kwR6vdbodhyM2CFDH/oQiwrH3R0RutL2frGCktDzEAKPGhmh0XEaBxCmy1L6eH9HtV3UUmiaM4GjXCQjK2xWUYKQa2UFWXP6PZasknusEwxppckX0AX6LV93ScxrUlJG9xAs46lE/o9ZSget2lqirjJiH2enBMTTvQiWHaNvpZD9DblZSjPh2dlsPf49jKCOBslHg0fhJTOJMEgzAxTP1iT6NkgZlG/TLpT0q23fA+rsu1ZGDGFdlmB+sAbFnObzjvkZGp5dUg4a11G9H4gYpWc6O5jhW4+mktLDowXfWzt+f/qOHJNar+mUZDWqHoLsA1EDhTf0xoc7A1c/xxYdsIMtKuFtR3K3x8SnyFqlrE9/9pK5VN/SgQ05VqIfA1TpTQB1TMJzcXveHazsiFnnEsiPD7ALUxhltVFHBn/4dTDABEFtiMPCL6U/QUjrl/rRX5/TRH3umUAjp9Pg3uaHPlNfcMXT0kn29GjtL0TO0HTrmkRyut+oEAag28tNRxgPNefOoyFHpy/TFiu9ie0bzNsXzLCx8SfsdFC4GIAlco1vSBx5937D5kOetC57Da/ufvTA/GLSNhw2BzxMdWtw5PaDquW1WXRVf2dNwjEIOwE0SimBmq+qBN/VZub9V3o0Ba3evTFCwE65K8hy/b5R/7BP1CySgUIlk/AhtAlWTCkKuhQ=
  template:
    metadata:
      name: psql-musmgr-creds
      namespace: db
    type: kubernetes.io/basic-auth
