---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-musmgr-creds
  namespace: db
spec:
  encryptedData:
    password: AgCjVM6jHOgWNbF2OwwioXCYdAM0OGkfDz+l8Ad6H+9QCoCCWdfFFWF8H2l9sPeARvKwKeLz98xjie9gS98oh1I5gHrUbiEYS4u3uVP9VpTnSaKCxLiU31gmtHSUDj4wIfCF8a0mteDvozl8wC1vdlTjcOAPwIKHgvsP5NHXkWd448ILHheOdvTB65OawARBuJTz3/3H9CLI41kq7I7Fg3gYvEPoZffF9+I7mAQXLqU6IKTbu3OiUXNPLLlbAuTlAd5MbaRVuOyV57qzUJKOeJmMPd7Xm6Ve9WauZgBnWpyivxAh3BzXozZWCkjVuXPLLZDqwSSMgnPB1iTCxaToGEfXWOwgQrqhOd0o8Pzatgm2lyT4GaDhipovHcQ1ww3p+kdXm1+f6oakHvWeyVTP4A7jl89utneMQ8g8iWsB4dXRXakp5wNjelrE82Ria+fvbI90u+fVEOEDlxOgbhwoZwKb7L9OPUqM2TGfbXk5/VF4iYiSYUICZPnvQXxL60J4xx3ksMswR2RdP2ukDe1L9hpDPb2WIDRzdTWpRAxFh1yZ6uHlRf3OKee7DE+v2y10zSs2ScyPOD3Tao4piod9KE66E3a4/kwHXSWKU94pxmcUuVheQQ2DHaqx1b2Q1mam91B3KGYZy7vK9HuV39sPMH8fe2qOpQAGhBPEIux4Ij4cezOfOtOzHC6NvUFimuiar4H5hOP9EFNE7Xn45JTAcvBjPl5jVFoyVT4=
    username: AgBlS9Hd1vGLKwjmMCrdFd10zqIR5VrRowgFXhshKrfnys13M74KO8CXuUmP2v4aL/N1YWEuXFK+ccXqemDzGgmmrnuHf3FO8NW3s6fwGnydlKEQW5eEdDIXqc0LiVWSeKIE7IVNe4hI2Fycv//9yikBHgOMFX6r/8WPUotP4LDsthLRntcIS2VuKwOzrkDB9CSc96yuhKtuW0HOhaXENKFHtRcw1Zexl1W0zMJ66ApU/AAt0gnQkZ5zKTB6w0NsO/cACAR5ZiWA6SyM6smAT8iQUbH1VaSZJeQRb1v80RMV//HE+U1fgw8yDfIe1QUUDJpsK8e5AUsfnPpIOZxq7a1IODghdxUytXO2P6MFKQRXf/jv5Z2A5+7XZoWC/085GOKqOkW66Cb2+vD3jmzWppvav9CyK35ql/zJfOPvj56jGVmXIq72fa68Uvst6kp71ahRlDMOXnZMmEXjo0zEDsdlxX7WVJ0CSCTI5nKQ6MdMtuegxNJMgSN/rYm9gAOwiqsO6Y3aKwzRVSmGUOQ9O/6ZwI9PzBckevecA3EpGnoRNIyUokdfjk3w3nTtWA0hMy/ua0IwgjQcyTWVmZ9i26/slETFcedlxecjTpuJok3WxtoVheZo8b8xrPDV4APGjS92tfxJrsk90etCv5e7pKVlh42CL9YInBUzDZ7BYysN1rDu1ln0zRR4/PffOi2iKekv29Tbrrc=
  template:
    metadata:
      name: psql-musmgr-creds
      namespace: db
    type: kubernetes.io/basic-auth
