---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-musmgr-creds
  namespace: db
spec:
  encryptedData:
    password: AgAKCt/JoSseXPFLJZ+saRQ+ufYDJUl5U39tbpxhS4skSqY6JvlsjB4FJUcugEzqHZE0ITcpfd1HYmK5/e9YV7hLiamy9B3WoBLfwZvYqj2LgdAhsfL529+OUKcAHySrLqAaacEGluNKtmsXiqgefA6q/OsXjmVzVtRD8js5/e/XMH9Z9Q9yDxHbBgOBSLeK7F/QsHl+77XdsxaP2YQsOZzsXUCJJIWQJlIfbjhYlutDlHGOSXJUyFkiaJhuqPmnVYOnngUa8v0SIaHL6b1dwf6A2eZO8ivGF0ecU2vM08cwmKyqkkxoqfG3o3dPbuuW3lDTceSNN9pLYeuBXMK4xVUBhVbojKLfkO4ZYCr0L07el/tLpE8T0tFxaWtzvCluDQYbKBVJOPPzWS1VDvo0n6/GTWEncFBJ4ZluIMdgqM9Hnh10Ydj+DgIkXDT5p+OHZOgO27mz+4M/xoM/WRzdsuyO9mezPfdwar92aMNeU5C+CRGxilbl+Lc2o/w9G6U+6mz1DgDhjhR7ZxEjDt8MVVBA6H1wYvgCAPZXG+dEQtHCppmclCEdh7hqz//CbEs4Q2MhwYGbmYd2Eczc0R55ag8NpcBN9PY/Pr0KeoHHNdhXE6fSOl0rjtgcKPIbN8bqtNBbw47qbr853OI26ND/Xa6IC26epGvCjpUfAOT1rV7GWY5BcHJ/NG1va2wJ8Ym8482EdaoCrLqqnRKm66SztC8udXUOUyWdQ48=
    username: AgAKn6pnPR/ahfnFEo8GffGPEiJkrr2r5atjYUsAdabdtC3nBWtKnKOWBWltDl9RK6lYJijZ/5QJJVsSSj9DonA+n5x/Ln2oJ0wYkn3+Uk+p41/+ew073zeXbGVKLzoJRZK+aYeG87z1t3FvLW0JRGpovhaqVwrUi4aVLf4vro4a4CwmX+tw9wsr+tWJl/fK/D7iIWuT3LmgkpcOKb9lY8oWBuie/5bNJIknS7hIkvUwNkpmcD8SkaCNIGoHSRNsQEhW2jCVJDFpE0+rCQyQnCxdffue+nvifspdfPzJ4qESp8SEzfxMveKcO9xxza5Pvvc6E+vOWcgYZkesevdlyKXf5Ch74kbMz/y2O7Lh7/x5vkv8VLzPW0p+KEYtjUfLlPagnWuMsydqMv6J4aM7P0yYXTtaxBn+GKeRVX0o4UiMH2nfypeda2Na2tnKS6QmGYztNulat0/sHbx4iCD+xnhAEUlBRdppon9OWjYNysVtl5YS7UWNzZtt5pBxIIafpvEkpSEheDYODJNcojjROVX9n7UFEyTUPxw4rmPQp7Trn0HlWx932nUsCUudE2fKasB9TgdCfN6pkEFLGtst48UT5RBabdh1YxajiUwq/lyzPUswPCnjkJ9RyrZz4Fu8oNjqEL47kQGsKsWB5Fr28937lbVf2fU2XGuWUpjMTX8ky4mdBI+lt57eR382i3tazYmdXe2b/iI=
  template:
    metadata:
      name: psql-musmgr-creds
      namespace: db
    type: kubernetes.io/basic-auth
