---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: psql-infisical-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgAeoviyamkSGP3bdXx2rbdJklo6cVdi5Z2j3vRcJqPL+1/Ex6snA42Jv/CJpPup6cSk+86jBwLS3eomMqlcriZOib/hkc7stqRMuqA/nKJRTEjzyePUOULkhtnjufIolrAxHs8m/wAlyfSi9NAJZEFNFKaaUzPN9xRLZOSbrVnmvKgDJKCwX+1A5+kL/XLWzVLhdRPc0X0UAPocTpU2MINdwUrDWlWi10jFTElJCVS87rCkCbZRJ4tslkff4D/fkPwiBgitPHbaJ4+y2iByy4mKFshnyE+9uJImxg74+fZrEr6ShbyzGK+pOmJGMotvtTXTrbEXZhXUCnF8Xk+pe3TovKiBd2q2nh53MCw7+662P5pX9o0AH0KmOQ5wZS3wPO0k9lAAROvP5LICUsel5Hc86q9c6KMURgfhBMQVkcEVyw1+NFRLcA89huflc/VDMXCm8qJB23v7Sh+QpEzBYk4s/Kbgs97sXMt7yvdJJvPMnxvjIIakym7dlYUgRFYcZw26YWGfTs6UpG3BvhtqLmg+J+YhZQHQ98NqUnoCv1qe1s68Et+YRm1BAKPSnlQywQjhLAbD1YcfEIgY+q+hQ1PTYW2sWxZwmkQ5fFYeJveUoFArNBSo/UYgMFg6KGrNsZ62uI5RrpbJNPEO4789fAlhdBOJU6Fbw9RcMWkbNCQV4a7Bie7/gqAhMHTundIUaOldW+/jYY9NI2EGacvQeZLNx7/zEBAK8mw=
    username: AgB+8kOd/6NSL8DWo/iYAy6oDwPpgaR9+XDA5qnbzqTRc+l4arapqOi5XysRD7ntqcrWtWKhpSmAqWGhv9mlVg+nkxl8cG62OuO89U6V/uMAFZk2c5UnsSen1WjE0VDZYhMznl4v7msDY5KpHp+Ho49r3PVVUSfl8dhFCxsedv754JIze/jgKz6fvVYYhHSe0xDUyOF9p7h7kmVgssinW0geshDOF0HKSxAzgXdH0O6QxwJ4qGWdoKsByrB5mM/BVangnv9cijSztPQ/HLnA/71dXynnYVamVIfotIKT5+DNknvef2YNQKndWMVdOPDlb9WR846o5Y6jcFmxRWNKwkUwO4eoNmLOfd/lAFFjZvaNYeoBb43vwhePSk5DclEPue6++s2aAWz4WA+uCbbFP84wpJfTAvt3EELZHJMPTC4HyblqmOfYkkLAR7r4fa8sG4bisjufuyxE2GuZgiD32wU2w0Y4MeVQZiOSl4Xk0iPp1nuYXQIajZ4LZ0vSknC4Mlm5Rh3GeV0JcZ9vQ57zCOcGvbBSpGu94IXqCiDBNJTnlYDoGE0LmSym60mvcfO/9gYGRCcdPc3a58xVZIDpuxvA51CqljrUo3GlKZ3q+3RIG1uu8SMLy005yM9XZ+li+bOCbfaNs2UGETzx51FznsfuIMn3RaBOWPnCiPyN6cRA80il4e+fmnPuriDrqE3MKzbLeJDs79wSVYw=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: psql-infisical-creds
      namespace: secrets
    type: Opaque
