---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-infisical-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgBF6D9moMebzqVOZR8zIAPwlbaTcrs7lDw9kzBOS4sBWm/Xl+mk6u1VXCZwXfJV3tyNOLK6rru9FAL4HtOKNAFXD6WVJ+N6NHc8Ns6whgqGqcq4WUAzdftqxEdV/n9Mk8Tnv5kezgsLIcFW2NAaItljCvPZO0R96zMvdIrNAgZUaohobtp63koEig69SyChKA9r1SY00xQ02uGvwmUuGNaoRbvW8TH/CsttceudTZtxwKr/Pw2Z0SProfq6fE7T0ONZ/73Q87JnTVWXfeQvnwapwfDEgwfv5Xu2CqBT4mMEAgY5g2RNy89CHcwjarClfyry2k2mINbAq59SsbZDcZL/Kv12giUtvpF8mfXFVvQ2DSBdY3AkJnelTF76QwSWelU47VlPXezpdhicT4+/YnRF37aAF/KuVTSbIYh9yjZqhrh4BfyNnfM9DG0ZLVOjb90+sh/ZxkxpVhVChNeCN3x9P9Unt0Bnxl8x0kWOKekqIIXZNrZO5nyqY63ysp8wOzyJfrZ4ZVWNr7zoS90jtoeFZgc7c1MFkoY/PIjaYDyi+lk3ANdsSzhYpUW2XkjM3NdfUd2I2rO7Theg/YFnQ09tdXpVdGR9PNK7bucj1MjMif1nk8+aCAAny4xmTczctwTffEGBw7eo+VU8FI3WYfpjsd7tkdumVOb/kKgBv1RfxLZcBHcVHZ9OAUm8dPzk02zD+MM46rhL8RPRVq0aMDyy+pM=
    username: AgANAWvpAEHAxMo2YvCrUFrIOI1NvX+IIUDxIIoa23WQQcI0X8fIrjCIYu2w6XVhWcVemuT0s2nA/jhVulTBgi6rOjC1+SKoONcGcmpUM1I5Ja1Fu2m96JFLgDrZTCA0zHn5hZuqepqDI8dFww/UncqdmkN50egeD9uSNqhgqh/vMnr9Nth7h64TI7COS1hdDNqlmy05XRhJni6fAAt4zz8FcTZSWHsgcZlYt0WnYqfBJrdyhz/CCp0xkuRL1zHNxxLa0VbIBjLDafE6oAPHQ8+sXPJKK0NooFEsTLZzEmcP7pHIGq4MIXeLgN8hzz4/Qv1vwb39I8NK//eg2BzEnD6L7JCX75v3RIdO8dN+iMlwVWFkHBbeHiptUacEwzcAf1mY8TKtDkcfxigGTAEBL18BW4vLA3oAzrVFvk7SDBlSLBF8Wv/9U6nRj6ljYVDmuKxgbaQXlV1rUbZJYtes2+KQgqamCU7pIG2b+VOefZtQNeg+5Wb/ay819PP8r+zE5+qnbnxWVwZwfvImi/cKBHsvcCYTrF/veliYVxx1wfmbqiWxFNx12CC+VFqjgBzYpppPTMQHQuDc63S42pVJK0j81Wzt8MhZYs5sqs9OOJMFai5L4aGGWx2DJcCjGcbzTAynscIqT6bsi+NzOK/IW4hXJ4blBe+KqD7AObabicwAlsioOSBDj/PCni5OnsnyGABOREI+f/5ZEAk=
  template:
    metadata:
      name: psql-infisical-creds
      namespace: secrets
    type: kubernetes.io/basic-auth
