---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-infisical-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgBMZ3CLCasrOgOh9JsSPR7RbgqjEVxMVmz35qIs7wI3jKiNUklsHx62aWn5PvPYcd4bxvlQ6vF8QPNOFQ698S7ti3P4ISwWXMDSZ1PLtUmp+1vvwmFRJwdGie6DsrKEi/cdo37LmEBAFEcO8e66F4HS1u8YPCetEB8FJWRMrdwtwbn+pfSEbFqEp2nG6iJrjLzOlSW1y3p76+RqMlrIg9JZ9s/d4p163JNZVN9V5bD3/Qpvw8Wrn8PiV9UPBAoIF4D44TCBRlAe5H8oh6aCKzM1FiX1QoUrcNYQzRuuQjKfSyD6aTqY5km0IJeIP115P+TkrocqjH1M8bxtddwa7007D3lILHNvZ49HLjRXqS0ALqnfgzcx5C3GxCEiLW0DvptYVsEuK4qj0nacTZxGpsHnsBGSxAunpXeBm3eyXjWdnHX9dkqWhx1tNhO6CeTFC3FMQYnjkNL5rUWPTcVD1B9MU1N3B860+ZvMdTolo/aju2U0qnu5T1Xnvmxw254cy6O9SF+vlcOwBovkruINhVTe2VYcarjUtlmDGFzHOkr0EI40eO/CDPXdAdaCG83wr0pdqHlYUgFL+tsKqTLuWSbrZ+97i54bgK1QsF20qxJ/cdt8mkqhv6jxRylDUXi2w4+RdUU3CR2oxmTsxkKIqby4ayxtJKasUL6gm/INKvvBlX2VDrXN4iuaK1FxpZv6ObDGMlpqsmKXrp0+j53YiPAo5x0=
    username: AgCJ3f4oD7V3qIUhc/v8MTLL3rwA5An/gzDbg9FyYML8hrKEhSwqahhTL/4OXkll7bwvlKTNd1O8VfUn42mZV04dxonf5TzbzIR5pam3KqTuRfplRH4qaVnoGrv6zazO7wbG9ImeUV3VuS4UQgTGN9gxj1mtgHr3Hpo8MYT4mEYrb9/9hO/F4pDF00En2mNLI031FWYs4nxswlOcZBNzFSux2ujwfv6sW6JDZCM2xQ6MnJzh87h3s8Uee5eNmi+7lA7/h7RGhhgQkYFsrecG5EDOE84aazJQSfUBmCPpPHbC3ttDfLjAzfv4LRUwXgmdA5DXE29F060LFbYPVKokS0EXUn0iqz7u8pupo5FVzwz/l5nMov9VtkIX+0wh0wG8gmU8JtnViKMNaH+qIvR0kGD+KX58vOP1eOKz+olf5dTmRa6FdkTfPVETJmXb7sFOFw+JXWD6hWHv4Lf0wHQY14K2EPRRZ/PBxXmCpuFUu7o+YzHanS3/3wDdJC0jRJ47hsQhWkRYqwVFbJNuU+xHk2Mh7cXWt1csuWSCZK1pNUJTJfnjCwz8CzXrAyM/idqhbu3MGPMFeCoLAAEzgNcIa6pnHBxjoxd8Af445Y5pl14JDDWE3UvgK2va87Oh6VgfWk925SX8EQOnxgEPJOp9qKeAhDBZPJi6mMjcgevdQon1dFWE5rwIZBw4ozkv7/vyocroVCSN6fSQzS4=
  template:
    metadata:
      name: psql-infisical-creds
      namespace: secrets
    type: kubernetes.io/basic-auth
