---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-infisical-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgAhShI10MI4JrE7RENIXQ5NqyG8yb8SVJ5ASaqkAoNiH3H25HIxRHpFOWzVqDEid6gbPfZ2dRcXWK1mdfvmGeuc1zlUa5cO9QohFatizMzeX1+fsE8Ew3fNnX0M6ND81RnuQGos9IzDU0uTBI+XvUmgj2PKu4TCcP5FKAIhN6qgKWXYJJX9o9DCEoWUGghR8u7VDAZ9x9/GgWKt/nxg9vq0kX3iw3bPVJK+BFLeYSVwT8htHejQg5weFmZrLkd7jDDESfaIlGT0UFPBmbCgJu2NZyeYp+CzJLlSxdkMJpHk9O83I13zh8tDC3pcjgiHTKELqAKmrwdSjcDYl/9qkYc5bpg2LPPLlDo9yfwYh/HrIftmP8jvr5SRg4BilLak+2aLUwLAgIPmFDpk6biClaBs3ld8NH2wulp7xMR5oSQCWgNKkLNR4kjTk5lkEpr3pgluFeUHV0R64//mY1CutvUS3+zXmZlPAFgug1xyO4tObR1aOmNun4VsA//0Xg0YUySqs1f4kAW7Vftx3liaLM3YC4JATyaOopG3eCefcPEoq3jF8DwUzrLp3O6y/IoHdxLNqfWUzwC2ymRlD0IB7K27D5fIH+PqPjSWk7lddY1l5Cs+msYdWmiI1ONyFzEEOJCwqVQ2QuFwMqU1iqJ/yXRL6+cEAC3l7sXSOYOzTtEisyuMXpMpG1eTeRBG+Sfe8mtcECs5GdpG/jFy/eHkkGuz3XE=
    username: AgCyr8313HbTDuH9WSlvOUkP+/rLbqxJru/EYaCPj+NqX4KfjlnA+ZtYX7wQSI41FiK3/oaUSPDxTNeZAgt0mQTm3TdQfHSJ/6nnDXFx9+RG0y0oJ+YT9C+MxlUwAdbMz3gmhGOPn+aGx0NPqLLvPC66v2Tqxmy8baxzrJdENmsn8NLbQuKBBJW9787ImmCYDwm27moKEmY/l0AKKPLOHOGpibOaX2Slfn+lZQXU9IFqfqmDORLoHOvsq6hT2otJ6K3DYvzCzPJEjle0RCCbhtOyl9v9KnUi5hzjbjrKC7qkodt3/8dnKQhUFHuFrT2MPRYIYkvrLiTLpeYnBU2L7OaczZl8rgxWWn9u06i2CR7jVXEHEDzySynywGWYmT5j0lsuRNR3v7Lig46747vpIB+Sa/Kd5yhzNaGH65n/aIanBRDQB4RIY+/DmGov6zkUhHbs+ir4WGN6HXt+RqVhlLxWzEzXZTMEsmBOFuu/gJfLdTRyKXTwpWl3/eIQTMtP8ETJFqDYSPUtdRndiXfvjYfL90LObKgE6G0FrMyIIhCHCDlMC4Ynk8H9nDU2L0DCppqmDpNXTv+ZYM5ttdMJyw0gBibgMZK40X/LiFC9veaBirDIHDTUpKWNYr10rrCqxwfsdYB/YWhUsx0OMQUEk3/7tdqOHyuCtFt2QyM9Ew7N/6i1dMhPFa6dAOu5LoTQixYLZhVnrBjKQcI=
  template:
    metadata:
      name: psql-infisical-creds
      namespace: secrets
    type: kubernetes.io/basic-auth
