---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psql-infisical-creds
  namespace: secrets
spec:
  encryptedData:
    password: AgBR8nzDlUHhom0llxTelJ4PIUoCMeHViSpVlh1+WSdoNV79CyfgebBvHac/2ZGaUwykhKnl8xzgA76xjvtnx365gXg+0A9Ng0n5h6vRZFuRkh0dX88yzzOBx9eD0jFCoRMgKzYT+Asr4A3Bg/6rwj0KX4Vx77Yjqr7n+hZ3IXJrFUtFeZOv6L4fR3u47tz3dsnVxah8CcwE6Cb/syU1jdgXfj6j8kW5UButZ/Cns2YXV8OBGWvtLcFx6iqICSGzdnogD8NQSOlbl7Q6TvBOV1skUpBEpDtjLEpj5fhsUkqc0vDGPSbVFs3Be+cYSbhc9L935iB6CGBhddT2iAz/Y+5H/DDBTqFzLiTjgLcOEDsbHkchWy3RnYHPz3b0ZkFOBiwHQ3B6f/0MECvK6GTQNxetGhBeC0ir0195KCL86ifXY5QrCl+GcIEfr/poTpZHt6DkozMlm0m1F/yZkApk/uZBuOSdyaZgiJ/tSm7KbEft27M48s47MfciHuGD4M085WOW/F12QEYaN1g+DEany/HdN33mlJQoKIta3Xia03HCVij8zg41DD/kYwe2atYXbfVxc9RIo8iqWVnhFRkSfg8L4FqOgBw1JWTpjW11Q5eiVr7iJjMYt12LBknTqztrl0W4mN5RswaaaAZJZOHK31dKBnVsHsGzyUyNacY8dm3SxQE2rGGsiFINYOs5nqoARVS1G6+/eGz+KPMwabe5t4yl004=
    username: AgBD7ym9guIV4L/okHN4X5ziV3wjBNGBB+XtlcXCkaGEduYjEwe9Bd5UoAvSoig4Aap8iKMK+zIqHCiYK1/Ysw/r/mmUGxqU1wOw3IXMcGVdBqAk3xnGfgo2zKL4v8aNmbJ/gMNl7UwMr+lSVhDKGnGHqo426CAhAPsx52RV/WSVS0eFv92h9izxq00ylrlN7UGgNImzkLFI0uPlJUD4bREbl/B1fbg9c+lpFBdnBY+jMw2AEmXVfXCBklf+L2zD4BOS6GMYNSKtQlvuk+4SkYeuxUIW12uSJGWP2b9d0dxcqSnJsn/5lrSMK3TF4Fk183vslOiNH0LBOOeTWag/2XbKRhixvM/KJi+5n1D4h0AOsEovvO0izOnP9fNhdxx8HqMLKAhNaDcpRDMcMLlCB/zJLBu/YHLhriNfQU2JXVRCOtcWxdMuydLLRApMQhQVJIeiR3fUqGO2Es+wNekvoFs77QFd0yl431N780VoEpB7m7JZcMuZEdKopIO9SrX7cFjOu9U6Ph2mhfxNBwH19hlDX/E16Sq9u2oYUN4G1Y1VRfhcEyT4hcMrcbP42NRAnRFuYcxSwAdTkIeCR9wKec18yDzrJCkU+o84DEzBpq17vsrz4IoePEbLIvcDvk54cvqXa3loPfP3jOmomylC+Dss2RW++6vaWWkf4NrY6o88520hW0a54RUGEoTovgBATWFmP0IXCx8mV/E=
  template:
    metadata:
      name: psql-infisical-creds
      namespace: secrets
    type: kubernetes.io/basic-auth
