---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: flux-system
spec:
  values:
    infisical:
      # -- Kubernetes Secret reference containing Infisical root credentials
      kubeSecretRef: "infisical-auth"
