---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: infisical
  namespace: flux-system
spec:
  interval: 5m
  values:
    infisical:
      # -- Kubernetes Secret reference containing Infisical root credentials
      kubeSecretRef: "infisical-secrets"
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        cert-manager.io/cluster-issuer: letsencrypt-dns
      hosts:
        - infisical.home.voldemota.xyz
      tls:
        - secretName: infisical-tls
          hosts:
            - infisical.home.voldemota.xyz
    postgresql:
      enabled: false
      useExistingSecret: true
      existingConnectionStringSecret:
        name: "infisical-secrets"
        key: "DB_CONNECTION_URI"
    redis:
      enabled: false
      name: "redis"
      fullnameOverride: "redis"
      usePassword: false # set to true when setting a password
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
