---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: infisical-psql
  namespace: secrets
spec:
  instances: 2
  storage:
    size: 1Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: infisical
      owner: "infisical"
      encoding: UTF8
  monitoring:
    enablePodMonitor: true
