---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garage-secrets
  namespace: garage
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-cluster-secretstore
  target:
    name: garage-cluster-secrets
    creationPolicy: Owner
  data:
    - secretKey: RPC_SECRET
      remoteRef:
        key: "/applications/garage/RPC_SECRET"
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: "/applications/garage/ADMIN_TOKEN"
    - secretKey: METRICS_TOKEN
      remoteRef:
        key: "/applications/garage/METRICS_TOKEN"
