---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-pvc
  namespace: garage
spec:
  storageClassName: ""
  volumeName: garage-nfs-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
